// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: voice.proto

package voice

import (
	refs "github.com/ofabiodev/osmose/proto/refs"
	types "github.com/ofabiodev/osmose/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake
	RoomId        uint64        `protobuf:"fixed64,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ChatRef       *refs.ChatRef `protobuf:"bytes,2,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	Endpoint      string        `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Token         string        `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{0}
}

func (x *RoomInfo) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *RoomInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RoomInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RoomParticipant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake
	RoomId    uint64 `protobuf:"fixed64,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// @snowflake<User>
	UserId          uint64           `protobuf:"fixed64,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Muted           bool             `protobuf:"varint,4,opt,name=muted,proto3" json:"muted,omitempty"`
	Deafened        bool             `protobuf:"varint,5,opt,name=deafened,proto3" json:"deafened,omitempty"`
	VideoAvailable  bool             `protobuf:"varint,7,opt,name=video_available,json=videoAvailable,proto3" json:"video_available,omitempty"`
	ScreenAvailable bool             `protobuf:"varint,8,opt,name=screen_available,json=screenAvailable,proto3" json:"screen_available,omitempty"`
	Banner          *types.ChatPhoto `protobuf:"bytes,9,opt,name=banner,proto3,oneof" json:"banner,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomParticipant) Reset() {
	*x = RoomParticipant{}
	mi := &file_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomParticipant) ProtoMessage() {}

func (x *RoomParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomParticipant.ProtoReflect.Descriptor instead.
func (*RoomParticipant) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{1}
}

func (x *RoomParticipant) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomParticipant) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RoomParticipant) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoomParticipant) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *RoomParticipant) GetDeafened() bool {
	if x != nil {
		return x.Deafened
	}
	return false
}

func (x *RoomParticipant) GetVideoAvailable() bool {
	if x != nil {
		return x.VideoAvailable
	}
	return false
}

func (x *RoomParticipant) GetScreenAvailable() bool {
	if x != nil {
		return x.ScreenAvailable
	}
	return false
}

func (x *RoomParticipant) GetBanner() *types.ChatPhoto {
	if x != nil {
		return x.Banner
	}
	return nil
}

// voice.requestRoom -> RoomInfo
type RequestRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRoom) Reset() {
	*x = RequestRoom{}
	mi := &file_voice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRoom) ProtoMessage() {}

func (x *RequestRoom) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRoom.ProtoReflect.Descriptor instead.
func (*RequestRoom) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{2}
}

func (x *RequestRoom) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

// voice.disconnectUser -> ()
type DisconnectUser struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<User>
	UserId        uint64 `protobuf:"fixed64,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectUser) Reset() {
	*x = DisconnectUser{}
	mi := &file_voice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectUser) ProtoMessage() {}

func (x *DisconnectUser) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectUser.ProtoReflect.Descriptor instead.
func (*DisconnectUser) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectUser) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *DisconnectUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// voice.getRoomStates -> voice.GlobalRoomStates
type GetRoomStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomStates) Reset() {
	*x = GetRoomStates{}
	mi := &file_voice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomStates) ProtoMessage() {}

func (x *GetRoomStates) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomStates.ProtoReflect.Descriptor instead.
func (*GetRoomStates) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{4}
}

type GlobalRoomStates struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	RoomStates    []*GlobalRoomStates_Entry `protobuf:"bytes,1,rep,name=room_states,json=roomStates,proto3" json:"room_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalRoomStates) Reset() {
	*x = GlobalRoomStates{}
	mi := &file_voice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalRoomStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalRoomStates) ProtoMessage() {}

func (x *GlobalRoomStates) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalRoomStates.ProtoReflect.Descriptor instead.
func (*GlobalRoomStates) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{5}
}

func (x *GlobalRoomStates) GetRoomStates() []*GlobalRoomStates_Entry {
	if x != nil {
		return x.RoomStates
	}
	return nil
}

// Updates
type UpdateRoomState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	State         *RoomState             `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomState) Reset() {
	*x = UpdateRoomState{}
	mi := &file_voice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomState) ProtoMessage() {}

func (x *UpdateRoomState) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomState.ProtoReflect.Descriptor instead.
func (*UpdateRoomState) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoomState) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *UpdateRoomState) GetState() *RoomState {
	if x != nil {
		return x.State
	}
	return nil
}

type RoomState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake
	RoomId        uint64             `protobuf:"fixed64,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Participants  []*RoomParticipant `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomState) Reset() {
	*x = RoomState{}
	mi := &file_voice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomState) ProtoMessage() {}

func (x *RoomState) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomState.ProtoReflect.Descriptor instead.
func (*RoomState) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{7}
}

func (x *RoomState) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomState) GetParticipants() []*RoomParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

type UpdateRoomParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	Participant   *RoomParticipant       `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomParticipant) Reset() {
	*x = UpdateRoomParticipant{}
	mi := &file_voice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomParticipant) ProtoMessage() {}

func (x *UpdateRoomParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomParticipant.ProtoReflect.Descriptor instead.
func (*UpdateRoomParticipant) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRoomParticipant) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *UpdateRoomParticipant) GetParticipant() *RoomParticipant {
	if x != nil {
		return x.Participant
	}
	return nil
}

type GlobalRoomStates_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	State         *RoomState             `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalRoomStates_Entry) Reset() {
	*x = GlobalRoomStates_Entry{}
	mi := &file_voice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalRoomStates_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalRoomStates_Entry) ProtoMessage() {}

func (x *GlobalRoomStates_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalRoomStates_Entry.ProtoReflect.Descriptor instead.
func (*GlobalRoomStates_Entry) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GlobalRoomStates_Entry) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *GlobalRoomStates_Entry) GetState() *RoomState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_voice_proto protoreflect.FileDescriptor

const file_voice_proto_rawDesc = "" +
	"\n" +
	"\vvoice.proto\x12\x13osmium.client.voice\x1a\n" +
	"refs.proto\x1a\vtypes.proto\"\x8d\x01\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x06R\x06roomId\x126\n" +
	"\bchat_ref\x18\x02 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\xb0\x02\n" +
	"\x0fRoomParticipant\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x06R\x06roomId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x06R\x06userId\x12\x14\n" +
	"\x05muted\x18\x04 \x01(\bR\x05muted\x12\x1a\n" +
	"\bdeafened\x18\x05 \x01(\bR\bdeafened\x12'\n" +
	"\x0fvideo_available\x18\a \x01(\bR\x0evideoAvailable\x12)\n" +
	"\x10screen_available\x18\b \x01(\bR\x0fscreenAvailable\x12;\n" +
	"\x06banner\x18\t \x01(\v2\x1e.osmium.client.types.ChatPhotoH\x00R\x06banner\x88\x01\x01B\t\n" +
	"\a_banner\"E\n" +
	"\vRequestRoom\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\"a\n" +
	"\x0eDisconnectUser\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x06R\x06userId\"\x0f\n" +
	"\rGetRoomStates\"\xd7\x01\n" +
	"\x10GlobalRoomStates\x12L\n" +
	"\vroom_states\x18\x01 \x03(\v2+.osmium.client.voice.GlobalRoomStates.EntryR\n" +
	"roomStates\x1au\n" +
	"\x05Entry\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x124\n" +
	"\x05state\x18\x02 \x01(\v2\x1e.osmium.client.voice.RoomStateR\x05state\"\x7f\n" +
	"\x0fUpdateRoomState\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x124\n" +
	"\x05state\x18\x02 \x01(\v2\x1e.osmium.client.voice.RoomStateR\x05state\"n\n" +
	"\tRoomState\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x06R\x06roomId\x12H\n" +
	"\fparticipants\x18\x03 \x03(\v2$.osmium.client.voice.RoomParticipantR\fparticipants\"\x97\x01\n" +
	"\x15UpdateRoomParticipant\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12F\n" +
	"\vparticipant\x18\x02 \x01(\v2$.osmium.client.voice.RoomParticipantR\vparticipantb\x06proto3"

var (
	file_voice_proto_rawDescOnce sync.Once
	file_voice_proto_rawDescData []byte
)

func file_voice_proto_rawDescGZIP() []byte {
	file_voice_proto_rawDescOnce.Do(func() {
		file_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_proto_rawDesc), len(file_voice_proto_rawDesc)))
	})
	return file_voice_proto_rawDescData
}

var file_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_voice_proto_goTypes = []any{
	(*RoomInfo)(nil),               // 0: osmium.client.voice.RoomInfo
	(*RoomParticipant)(nil),        // 1: osmium.client.voice.RoomParticipant
	(*RequestRoom)(nil),            // 2: osmium.client.voice.RequestRoom
	(*DisconnectUser)(nil),         // 3: osmium.client.voice.DisconnectUser
	(*GetRoomStates)(nil),          // 4: osmium.client.voice.GetRoomStates
	(*GlobalRoomStates)(nil),       // 5: osmium.client.voice.GlobalRoomStates
	(*UpdateRoomState)(nil),        // 6: osmium.client.voice.UpdateRoomState
	(*RoomState)(nil),              // 7: osmium.client.voice.RoomState
	(*UpdateRoomParticipant)(nil),  // 8: osmium.client.voice.UpdateRoomParticipant
	(*GlobalRoomStates_Entry)(nil), // 9: osmium.client.voice.GlobalRoomStates.Entry
	(*refs.ChatRef)(nil),           // 10: osmium.client.refs.ChatRef
	(*types.ChatPhoto)(nil),        // 11: osmium.client.types.ChatPhoto
}
var file_voice_proto_depIdxs = []int32{
	10, // 0: osmium.client.voice.RoomInfo.chat_ref:type_name -> osmium.client.refs.ChatRef
	11, // 1: osmium.client.voice.RoomParticipant.banner:type_name -> osmium.client.types.ChatPhoto
	10, // 2: osmium.client.voice.RequestRoom.chat_ref:type_name -> osmium.client.refs.ChatRef
	10, // 3: osmium.client.voice.DisconnectUser.chat_ref:type_name -> osmium.client.refs.ChatRef
	9,  // 4: osmium.client.voice.GlobalRoomStates.room_states:type_name -> osmium.client.voice.GlobalRoomStates.Entry
	10, // 5: osmium.client.voice.UpdateRoomState.chat_ref:type_name -> osmium.client.refs.ChatRef
	7,  // 6: osmium.client.voice.UpdateRoomState.state:type_name -> osmium.client.voice.RoomState
	1,  // 7: osmium.client.voice.RoomState.participants:type_name -> osmium.client.voice.RoomParticipant
	10, // 8: osmium.client.voice.UpdateRoomParticipant.chat_ref:type_name -> osmium.client.refs.ChatRef
	1,  // 9: osmium.client.voice.UpdateRoomParticipant.participant:type_name -> osmium.client.voice.RoomParticipant
	10, // 10: osmium.client.voice.GlobalRoomStates.Entry.chat_ref:type_name -> osmium.client.refs.ChatRef
	7,  // 11: osmium.client.voice.GlobalRoomStates.Entry.state:type_name -> osmium.client.voice.RoomState
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_voice_proto_init() }
func file_voice_proto_init() {
	if File_voice_proto != nil {
		return
	}
	file_voice_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_proto_rawDesc), len(file_voice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_voice_proto_goTypes,
		DependencyIndexes: file_voice_proto_depIdxs,
		MessageInfos:      file_voice_proto_msgTypes,
	}.Build()
	File_voice_proto = out.File
	file_voice_proto_goTypes = nil
	file_voice_proto_depIdxs = nil
}
