// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: auth.proto

package auth

import (
	types "github.com/ofabiodev/osmose/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InviteType int32

const (
	InviteType_UNKNOWN   InviteType = 0
	InviteType_COMMUNITY InviteType = 1
	InviteType_GROUP     InviteType = 2
	InviteType_USER      InviteType = 3
)

// Enum value maps for InviteType.
var (
	InviteType_name = map[int32]string{
		0: "UNKNOWN",
		1: "COMMUNITY",
		2: "GROUP",
		3: "USER",
	}
	InviteType_value = map[string]int32{
		"UNKNOWN":   0,
		"COMMUNITY": 1,
		"GROUP":     2,
		"USER":      3,
	}
)

func (x InviteType) Enum() *InviteType {
	p := new(InviteType)
	*p = x
	return p
}

func (x InviteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteType) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_proto_enumTypes[0].Descriptor()
}

func (InviteType) Type() protoreflect.EnumType {
	return &file_auth_proto_enumTypes[0]
}

func (x InviteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InviteType.Descriptor instead.
func (InviteType) EnumDescriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

// auth.legacySignIn -> auth.Authorization
type LegacySignIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Totp          *string                `protobuf:"bytes,3,opt,name=totp,proto3,oneof" json:"totp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LegacySignIn) Reset() {
	*x = LegacySignIn{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacySignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacySignIn) ProtoMessage() {}

func (x *LegacySignIn) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegacySignIn.ProtoReflect.Descriptor instead.
func (*LegacySignIn) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LegacySignIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LegacySignIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LegacySignIn) GetTotp() string {
	if x != nil && x.Totp != nil {
		return *x.Totp
	}
	return ""
}

// auth.signIn -> auth.SignInResult
type SignIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignIn) Reset() {
	*x = SignIn{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignIn) ProtoMessage() {}

func (x *SignIn) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignIn.ProtoReflect.Descriptor instead.
func (*SignIn) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SignIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// auth.completeSignIn -> auth.Authorization
type CompleteSignIn struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// Types that are valid to be assigned to Proof:
	//
	//	*CompleteSignIn_Totp
	//	*CompleteSignIn_RecoveryCode
	//	*CompleteSignIn_WebauthnCredentialJson
	Proof         isCompleteSignIn_Proof `protobuf_oneof:"proof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSignIn) Reset() {
	*x = CompleteSignIn{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSignIn) ProtoMessage() {}

func (x *CompleteSignIn) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSignIn.ProtoReflect.Descriptor instead.
func (*CompleteSignIn) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteSignIn) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CompleteSignIn) GetProof() isCompleteSignIn_Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *CompleteSignIn) GetTotp() string {
	if x != nil {
		if x, ok := x.Proof.(*CompleteSignIn_Totp); ok {
			return x.Totp
		}
	}
	return ""
}

func (x *CompleteSignIn) GetRecoveryCode() string {
	if x != nil {
		if x, ok := x.Proof.(*CompleteSignIn_RecoveryCode); ok {
			return x.RecoveryCode
		}
	}
	return ""
}

func (x *CompleteSignIn) GetWebauthnCredentialJson() string {
	if x != nil {
		if x, ok := x.Proof.(*CompleteSignIn_WebauthnCredentialJson); ok {
			return x.WebauthnCredentialJson
		}
	}
	return ""
}

type isCompleteSignIn_Proof interface {
	isCompleteSignIn_Proof()
}

type CompleteSignIn_Totp struct {
	Totp string `protobuf:"bytes,2,opt,name=totp,proto3,oneof"`
}

type CompleteSignIn_RecoveryCode struct {
	RecoveryCode string `protobuf:"bytes,3,opt,name=recovery_code,json=recoveryCode,proto3,oneof"`
}

type CompleteSignIn_WebauthnCredentialJson struct {
	WebauthnCredentialJson string `protobuf:"bytes,4,opt,name=webauthn_credential_json,json=webauthnCredentialJson,proto3,oneof"`
}

func (*CompleteSignIn_Totp) isCompleteSignIn_Proof() {}

func (*CompleteSignIn_RecoveryCode) isCompleteSignIn_Proof() {}

func (*CompleteSignIn_WebauthnCredentialJson) isCompleteSignIn_Proof() {}

type SignInResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*SignInResult_Authorization
	//	*SignInResult_MfaChallenge
	Result        isSignInResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInResult) Reset() {
	*x = SignInResult{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResult) ProtoMessage() {}

func (x *SignInResult) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResult.ProtoReflect.Descriptor instead.
func (*SignInResult) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SignInResult) GetResult() isSignInResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SignInResult) GetAuthorization() *Authorization {
	if x != nil {
		if x, ok := x.Result.(*SignInResult_Authorization); ok {
			return x.Authorization
		}
	}
	return nil
}

func (x *SignInResult) GetMfaChallenge() *MfaChallenge {
	if x != nil {
		if x, ok := x.Result.(*SignInResult_MfaChallenge); ok {
			return x.MfaChallenge
		}
	}
	return nil
}

type isSignInResult_Result interface {
	isSignInResult_Result()
}

type SignInResult_Authorization struct {
	Authorization *Authorization `protobuf:"bytes,1,opt,name=authorization,proto3,oneof"`
}

type SignInResult_MfaChallenge struct {
	MfaChallenge *MfaChallenge `protobuf:"bytes,2,opt,name=mfa_challenge,json=mfaChallenge,proto3,oneof"`
}

func (*SignInResult_Authorization) isSignInResult_Result() {}

func (*SignInResult_MfaChallenge) isSignInResult_Result() {}

type MfaChallenge struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId         string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	ExpiresAt           uint64                 `protobuf:"fixed64,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Totp                bool                   `protobuf:"varint,3,opt,name=totp,proto3" json:"totp,omitempty"`
	RecoveryCodes       bool                   `protobuf:"varint,4,opt,name=recovery_codes,json=recoveryCodes,proto3" json:"recovery_codes,omitempty"`
	WebauthnOptionsJson *string                `protobuf:"bytes,5,opt,name=webauthn_options_json,json=webauthnOptionsJson,proto3,oneof" json:"webauthn_options_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MfaChallenge) Reset() {
	*x = MfaChallenge{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaChallenge) ProtoMessage() {}

func (x *MfaChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaChallenge.ProtoReflect.Descriptor instead.
func (*MfaChallenge) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *MfaChallenge) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *MfaChallenge) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *MfaChallenge) GetTotp() bool {
	if x != nil {
		return x.Totp
	}
	return false
}

func (x *MfaChallenge) GetRecoveryCodes() bool {
	if x != nil {
		return x.RecoveryCodes
	}
	return false
}

func (x *MfaChallenge) GetWebauthnOptionsJson() string {
	if x != nil && x.WebauthnOptionsJson != nil {
		return *x.WebauthnOptionsJson
	}
	return ""
}

// auth.signUp -> auth.Authorization
type SignUp struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Email                  *string                `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Password               *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Name                   string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	EmailVerificationToken *string                `protobuf:"bytes,4,opt,name=email_verification_token,json=emailVerificationToken,proto3,oneof" json:"email_verification_token,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SignUp) Reset() {
	*x = SignUp{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUp) ProtoMessage() {}

func (x *SignUp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUp.ProtoReflect.Descriptor instead.
func (*SignUp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SignUp) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *SignUp) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *SignUp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUp) GetEmailVerificationToken() string {
	if x != nil && x.EmailVerificationToken != nil {
		return *x.EmailVerificationToken
	}
	return ""
}

// auth.createEmailVerificationChallenge -> auth.EmailVerificationChallenge
type CreateEmailVerificationChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailVerificationChallenge) Reset() {
	*x = CreateEmailVerificationChallenge{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailVerificationChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailVerificationChallenge) ProtoMessage() {}

func (x *CreateEmailVerificationChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailVerificationChallenge.ProtoReflect.Descriptor instead.
func (*CreateEmailVerificationChallenge) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

type EmailVerificationChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExpiresAt     uint64                 `protobuf:"fixed64,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailVerificationChallenge) Reset() {
	*x = EmailVerificationChallenge{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailVerificationChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerificationChallenge) ProtoMessage() {}

func (x *EmailVerificationChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerificationChallenge.ProtoReflect.Descriptor instead.
func (*EmailVerificationChallenge) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *EmailVerificationChallenge) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *EmailVerificationChallenge) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// auth.authorize -> auth.Authorization
type Authorize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorize) Reset() {
	*x = Authorize{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorize) ProtoMessage() {}

func (x *Authorize) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorize.ProtoReflect.Descriptor instead.
func (*Authorize) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *Authorize) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Authorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Token string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User  *types.User            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// @snowflake<Session>
	SessionId     uint64 `protobuf:"fixed64,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorization) Reset() {
	*x = Authorization{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorization) ProtoMessage() {}

func (x *Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorization.ProtoReflect.Descriptor instead.
func (*Authorization) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *Authorization) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Authorization) GetUser() *types.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Authorization) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

// auth.getSessions -> auth.Sessions
type GetSessions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessions) Reset() {
	*x = GetSessions{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessions) ProtoMessage() {}

func (x *GetSessions) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessions.ProtoReflect.Descriptor instead.
func (*GetSessions) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

type Sessions struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sessions []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	// @snowflake<Session>
	Current       uint64 `protobuf:"fixed64,2,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sessions) Reset() {
	*x = Sessions{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sessions) ProtoMessage() {}

func (x *Sessions) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sessions.ProtoReflect.Descriptor instead.
func (*Sessions) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *Sessions) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *Sessions) GetCurrent() uint64 {
	if x != nil {
		return x.Current
	}
	return 0
}

type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Session>
	Id            uint64  `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      uint32  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DeviceType    string  `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	DeviceVersion string  `protobuf:"bytes,4,opt,name=device_version,json=deviceVersion,proto3" json:"device_version,omitempty"`
	AppName       string  `protobuf:"bytes,5,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppVersion    string  `protobuf:"bytes,6,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	LastActive    uint64  `protobuf:"fixed64,7,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	Country       *string `protobuf:"bytes,8,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Region        *string `protobuf:"bytes,9,opt,name=region,proto3,oneof" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

func (x *Session) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Session) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *Session) GetDeviceVersion() string {
	if x != nil {
		return x.DeviceVersion
	}
	return ""
}

func (x *Session) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *Session) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *Session) GetLastActive() uint64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

func (x *Session) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *Session) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

// auth.revokeSessions -> ()
type RevokeSessions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Session>
	SessionIds    []uint64 `protobuf:"fixed64,1,rep,packed,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessions) Reset() {
	*x = RevokeSessions{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessions) ProtoMessage() {}

func (x *RevokeSessions) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessions.ProtoReflect.Descriptor instead.
func (*RevokeSessions) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeSessions) GetSessionIds() []uint64 {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

// auth.resetPassword -> ()
type ResetPassword struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Email         string                              `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Confirm       *ResetPassword_ResetPasswordConfirm `protobuf:"bytes,2,opt,name=confirm,proto3,oneof" json:"confirm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPassword) Reset() {
	*x = ResetPassword{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPassword) ProtoMessage() {}

func (x *ResetPassword) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPassword.ProtoReflect.Descriptor instead.
func (*ResetPassword) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ResetPassword) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPassword) GetConfirm() *ResetPassword_ResetPasswordConfirm {
	if x != nil {
		return x.Confirm
	}
	return nil
}

// auth.verifyEmail -> ()
type VerifyEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmail) Reset() {
	*x = VerifyEmail{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmail) ProtoMessage() {}

func (x *VerifyEmail) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmail.ProtoReflect.Descriptor instead.
func (*VerifyEmail) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyEmail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// auth.resendEmailVerification -> ()
type ResendEmailVerification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendEmailVerification) Reset() {
	*x = ResendEmailVerification{}
	mi := &file_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendEmailVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendEmailVerification) ProtoMessage() {}

func (x *ResendEmailVerification) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendEmailVerification.ProtoReflect.Descriptor instead.
func (*ResendEmailVerification) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{16}
}

func (x *ResendEmailVerification) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

// auth.LookupInvite -> auth.InvitePreview
type LookupInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupInvite) Reset() {
	*x = LookupInvite{}
	mi := &file_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupInvite) ProtoMessage() {}

func (x *LookupInvite) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupInvite.ProtoReflect.Descriptor instead.
func (*LookupInvite) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{17}
}

func (x *LookupInvite) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// response model for invite creates, for all community/chat/user
type CreatedInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedInvite) Reset() {
	*x = CreatedInvite{}
	mi := &file_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedInvite) ProtoMessage() {}

func (x *CreatedInvite) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedInvite.ProtoReflect.Descriptor instead.
func (*CreatedInvite) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{18}
}

func (x *CreatedInvite) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type InvitePreview struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// @snowflake<User>
	CreatorId uint64 `protobuf:"fixed64,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	// @snowflake<Keyable>
	TargetId   uint64      `protobuf:"fixed64,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType InviteType  `protobuf:"varint,4,opt,name=target_type,json=targetType,proto3,enum=osmium.client.auth.InviteType" json:"target_type,omitempty"`
	ExpiresAt  *uint64     `protobuf:"fixed64,5,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	Creator    *types.User `protobuf:"bytes,6,opt,name=creator,proto3,oneof" json:"creator,omitempty"`
	// Types that are valid to be assigned to TargetInfo:
	//
	//	*InvitePreview_Community
	//	*InvitePreview_Chat
	//	*InvitePreview_User
	TargetInfo    isInvitePreview_TargetInfo `protobuf_oneof:"target_info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvitePreview) Reset() {
	*x = InvitePreview{}
	mi := &file_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitePreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitePreview) ProtoMessage() {}

func (x *InvitePreview) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitePreview.ProtoReflect.Descriptor instead.
func (*InvitePreview) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{19}
}

func (x *InvitePreview) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InvitePreview) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *InvitePreview) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *InvitePreview) GetTargetType() InviteType {
	if x != nil {
		return x.TargetType
	}
	return InviteType_UNKNOWN
}

func (x *InvitePreview) GetExpiresAt() uint64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *InvitePreview) GetCreator() *types.User {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *InvitePreview) GetTargetInfo() isInvitePreview_TargetInfo {
	if x != nil {
		return x.TargetInfo
	}
	return nil
}

func (x *InvitePreview) GetCommunity() *types.Community {
	if x != nil {
		if x, ok := x.TargetInfo.(*InvitePreview_Community); ok {
			return x.Community
		}
	}
	return nil
}

func (x *InvitePreview) GetChat() *types.Group {
	if x != nil {
		if x, ok := x.TargetInfo.(*InvitePreview_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *InvitePreview) GetUser() *types.User {
	if x != nil {
		if x, ok := x.TargetInfo.(*InvitePreview_User); ok {
			return x.User
		}
	}
	return nil
}

type isInvitePreview_TargetInfo interface {
	isInvitePreview_TargetInfo()
}

type InvitePreview_Community struct {
	Community *types.Community `protobuf:"bytes,7,opt,name=community,proto3,oneof"`
}

type InvitePreview_Chat struct {
	Chat *types.Group `protobuf:"bytes,8,opt,name=chat,proto3,oneof"`
}

type InvitePreview_User struct {
	User *types.User `protobuf:"bytes,9,opt,name=user,proto3,oneof"`
}

func (*InvitePreview_Community) isInvitePreview_TargetInfo() {}

func (*InvitePreview_Chat) isInvitePreview_TargetInfo() {}

func (*InvitePreview_User) isInvitePreview_TargetInfo() {}

// auth.UseInvite -> ()
type UseInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseInvite) Reset() {
	*x = UseInvite{}
	mi := &file_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseInvite) ProtoMessage() {}

func (x *UseInvite) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseInvite.ProtoReflect.Descriptor instead.
func (*UseInvite) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{20}
}

func (x *UseInvite) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type InviteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invites       []*InvitePreview       `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteList) Reset() {
	*x = InviteList{}
	mi := &file_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteList) ProtoMessage() {}

func (x *InviteList) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteList.ProtoReflect.Descriptor instead.
func (*InviteList) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{21}
}

func (x *InviteList) GetInvites() []*InvitePreview {
	if x != nil {
		return x.Invites
	}
	return nil
}

type ResetPassword_ResetPasswordConfirm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPassword_ResetPasswordConfirm) Reset() {
	*x = ResetPassword_ResetPasswordConfirm{}
	mi := &file_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPassword_ResetPasswordConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPassword_ResetPasswordConfirm) ProtoMessage() {}

func (x *ResetPassword_ResetPasswordConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPassword_ResetPasswordConfirm.ProtoReflect.Descriptor instead.
func (*ResetPassword_ResetPasswordConfirm) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14, 0}
}

func (x *ResetPassword_ResetPasswordConfirm) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResetPassword_ResetPasswordConfirm) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x12osmium.client.auth\x1a\vtypes.proto\"b\n" +
	"\fLegacySignIn\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x17\n" +
	"\x04totp\x18\x03 \x01(\tH\x00R\x04totp\x88\x01\x01B\a\n" +
	"\x05_totp\":\n" +
	"\x06SignIn\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xb5\x01\n" +
	"\x0eCompleteSignIn\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x14\n" +
	"\x04totp\x18\x02 \x01(\tH\x00R\x04totp\x12%\n" +
	"\rrecovery_code\x18\x03 \x01(\tH\x00R\frecoveryCode\x12:\n" +
	"\x18webauthn_credential_json\x18\x04 \x01(\tH\x00R\x16webauthnCredentialJsonB\a\n" +
	"\x05proof\"\xac\x01\n" +
	"\fSignInResult\x12I\n" +
	"\rauthorization\x18\x01 \x01(\v2!.osmium.client.auth.AuthorizationH\x00R\rauthorization\x12G\n" +
	"\rmfa_challenge\x18\x02 \x01(\v2 .osmium.client.auth.MfaChallengeH\x00R\fmfaChallengeB\b\n" +
	"\x06result\"\xde\x01\n" +
	"\fMfaChallenge\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x06R\texpiresAt\x12\x12\n" +
	"\x04totp\x18\x03 \x01(\bR\x04totp\x12%\n" +
	"\x0erecovery_codes\x18\x04 \x01(\bR\rrecoveryCodes\x127\n" +
	"\x15webauthn_options_json\x18\x05 \x01(\tH\x00R\x13webauthnOptionsJson\x88\x01\x01B\x18\n" +
	"\x16_webauthn_options_json\"\xcb\x01\n" +
	"\x06SignUp\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x01R\bpassword\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12=\n" +
	"\x18email_verification_token\x18\x04 \x01(\tH\x02R\x16emailVerificationToken\x88\x01\x01B\b\n" +
	"\x06_emailB\v\n" +
	"\t_passwordB\x1b\n" +
	"\x19_email_verification_token\"\"\n" +
	" CreateEmailVerificationChallenge\"Q\n" +
	"\x1aEmailVerificationChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x06R\texpiresAt\"!\n" +
	"\tAuthorize\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\"s\n" +
	"\rAuthorization\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12-\n" +
	"\x04user\x18\x02 \x01(\v2\x19.osmium.client.types.UserR\x04user\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\x06R\tsessionId\"\r\n" +
	"\vGetSessions\"]\n" +
	"\bSessions\x127\n" +
	"\bsessions\x18\x01 \x03(\v2\x1b.osmium.client.auth.SessionR\bsessions\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x06R\acurrent\"\xae\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x06R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\rR\bclientId\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12%\n" +
	"\x0edevice_version\x18\x04 \x01(\tR\rdeviceVersion\x12\x19\n" +
	"\bapp_name\x18\x05 \x01(\tR\aappName\x12\x1f\n" +
	"\vapp_version\x18\x06 \x01(\tR\n" +
	"appVersion\x12\x1f\n" +
	"\vlast_active\x18\a \x01(\x06R\n" +
	"lastActive\x12\x1d\n" +
	"\acountry\x18\b \x01(\tH\x00R\acountry\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\t \x01(\tH\x01R\x06region\x88\x01\x01B\n" +
	"\n" +
	"\b_countryB\t\n" +
	"\a_region\"1\n" +
	"\x0eRevokeSessions\x12\x1f\n" +
	"\vsession_ids\x18\x01 \x03(\x06R\n" +
	"sessionIds\"\xd7\x01\n" +
	"\rResetPassword\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12U\n" +
	"\aconfirm\x18\x02 \x01(\v26.osmium.client.auth.ResetPassword.ResetPasswordConfirmH\x00R\aconfirm\x88\x01\x01\x1aM\n" +
	"\x14ResetPasswordConfirm\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPasswordB\n" +
	"\n" +
	"\b_confirm\"7\n" +
	"\vVerifyEmail\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\">\n" +
	"\x17ResendEmailVerification\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x88\x01\x01B\b\n" +
	"\x06_email\"\"\n" +
	"\fLookupInvite\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"#\n" +
	"\rCreatedInvite\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xcb\x03\n" +
	"\rInvitePreview\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x06R\tcreatorId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x06R\btargetId\x12?\n" +
	"\vtarget_type\x18\x04 \x01(\x0e2\x1e.osmium.client.auth.InviteTypeR\n" +
	"targetType\x12\"\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x06H\x01R\texpiresAt\x88\x01\x01\x128\n" +
	"\acreator\x18\x06 \x01(\v2\x19.osmium.client.types.UserH\x02R\acreator\x88\x01\x01\x12>\n" +
	"\tcommunity\x18\a \x01(\v2\x1e.osmium.client.types.CommunityH\x00R\tcommunity\x120\n" +
	"\x04chat\x18\b \x01(\v2\x1a.osmium.client.types.GroupH\x00R\x04chat\x12/\n" +
	"\x04user\x18\t \x01(\v2\x19.osmium.client.types.UserH\x00R\x04userB\r\n" +
	"\vtarget_infoB\r\n" +
	"\v_expires_atB\n" +
	"\n" +
	"\b_creator\"\x1f\n" +
	"\tUseInvite\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"I\n" +
	"\n" +
	"InviteList\x12;\n" +
	"\ainvites\x18\x01 \x03(\v2!.osmium.client.auth.InvitePreviewR\ainvites*=\n" +
	"\n" +
	"InviteType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tCOMMUNITY\x10\x01\x12\t\n" +
	"\x05GROUP\x10\x02\x12\b\n" +
	"\x04USER\x10\x03b\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_auth_proto_goTypes = []any{
	(InviteType)(0),                            // 0: osmium.client.auth.InviteType
	(*LegacySignIn)(nil),                       // 1: osmium.client.auth.LegacySignIn
	(*SignIn)(nil),                             // 2: osmium.client.auth.SignIn
	(*CompleteSignIn)(nil),                     // 3: osmium.client.auth.CompleteSignIn
	(*SignInResult)(nil),                       // 4: osmium.client.auth.SignInResult
	(*MfaChallenge)(nil),                       // 5: osmium.client.auth.MfaChallenge
	(*SignUp)(nil),                             // 6: osmium.client.auth.SignUp
	(*CreateEmailVerificationChallenge)(nil),   // 7: osmium.client.auth.CreateEmailVerificationChallenge
	(*EmailVerificationChallenge)(nil),         // 8: osmium.client.auth.EmailVerificationChallenge
	(*Authorize)(nil),                          // 9: osmium.client.auth.Authorize
	(*Authorization)(nil),                      // 10: osmium.client.auth.Authorization
	(*GetSessions)(nil),                        // 11: osmium.client.auth.GetSessions
	(*Sessions)(nil),                           // 12: osmium.client.auth.Sessions
	(*Session)(nil),                            // 13: osmium.client.auth.Session
	(*RevokeSessions)(nil),                     // 14: osmium.client.auth.RevokeSessions
	(*ResetPassword)(nil),                      // 15: osmium.client.auth.ResetPassword
	(*VerifyEmail)(nil),                        // 16: osmium.client.auth.VerifyEmail
	(*ResendEmailVerification)(nil),            // 17: osmium.client.auth.ResendEmailVerification
	(*LookupInvite)(nil),                       // 18: osmium.client.auth.LookupInvite
	(*CreatedInvite)(nil),                      // 19: osmium.client.auth.CreatedInvite
	(*InvitePreview)(nil),                      // 20: osmium.client.auth.InvitePreview
	(*UseInvite)(nil),                          // 21: osmium.client.auth.UseInvite
	(*InviteList)(nil),                         // 22: osmium.client.auth.InviteList
	(*ResetPassword_ResetPasswordConfirm)(nil), // 23: osmium.client.auth.ResetPassword.ResetPasswordConfirm
	(*types.User)(nil),                         // 24: osmium.client.types.User
	(*types.Community)(nil),                    // 25: osmium.client.types.Community
	(*types.Group)(nil),                        // 26: osmium.client.types.Group
}
var file_auth_proto_depIdxs = []int32{
	10, // 0: osmium.client.auth.SignInResult.authorization:type_name -> osmium.client.auth.Authorization
	5,  // 1: osmium.client.auth.SignInResult.mfa_challenge:type_name -> osmium.client.auth.MfaChallenge
	24, // 2: osmium.client.auth.Authorization.user:type_name -> osmium.client.types.User
	13, // 3: osmium.client.auth.Sessions.sessions:type_name -> osmium.client.auth.Session
	23, // 4: osmium.client.auth.ResetPassword.confirm:type_name -> osmium.client.auth.ResetPassword.ResetPasswordConfirm
	0,  // 5: osmium.client.auth.InvitePreview.target_type:type_name -> osmium.client.auth.InviteType
	24, // 6: osmium.client.auth.InvitePreview.creator:type_name -> osmium.client.types.User
	25, // 7: osmium.client.auth.InvitePreview.community:type_name -> osmium.client.types.Community
	26, // 8: osmium.client.auth.InvitePreview.chat:type_name -> osmium.client.types.Group
	24, // 9: osmium.client.auth.InvitePreview.user:type_name -> osmium.client.types.User
	20, // 10: osmium.client.auth.InviteList.invites:type_name -> osmium.client.auth.InvitePreview
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_auth_proto_msgTypes[0].OneofWrappers = []any{}
	file_auth_proto_msgTypes[2].OneofWrappers = []any{
		(*CompleteSignIn_Totp)(nil),
		(*CompleteSignIn_RecoveryCode)(nil),
		(*CompleteSignIn_WebauthnCredentialJson)(nil),
	}
	file_auth_proto_msgTypes[3].OneofWrappers = []any{
		(*SignInResult_Authorization)(nil),
		(*SignInResult_MfaChallenge)(nil),
	}
	file_auth_proto_msgTypes[4].OneofWrappers = []any{}
	file_auth_proto_msgTypes[5].OneofWrappers = []any{}
	file_auth_proto_msgTypes[12].OneofWrappers = []any{}
	file_auth_proto_msgTypes[14].OneofWrappers = []any{}
	file_auth_proto_msgTypes[16].OneofWrappers = []any{}
	file_auth_proto_msgTypes[19].OneofWrappers = []any{
		(*InvitePreview_Community)(nil),
		(*InvitePreview_Chat)(nil),
		(*InvitePreview_User)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		EnumInfos:         file_auth_proto_enumTypes,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
