// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// source: users.proto

package users

import (
	refs "github.com/ofabiodev/osmose/proto/refs"
	types "github.com/ofabiodev/osmose/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// users.getProfile -> Profile
type GetProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ref            *refs.UserRef          `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	IncludeMutuals bool                   `protobuf:"varint,2,opt,name=include_mutuals,json=includeMutuals,proto3" json:"include_mutuals,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProfile) Reset() {
	*x = GetProfile{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfile) ProtoMessage() {}

func (x *GetProfile) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfile.ProtoReflect.Descriptor instead.
func (*GetProfile) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfile) GetRef() *refs.UserRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *GetProfile) GetIncludeMutuals() bool {
	if x != nil {
		return x.IncludeMutuals
	}
	return false
}

type Profile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ref               *refs.UserRef          `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Bio               string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	PremiumSince      *uint64                `protobuf:"fixed64,3,opt,name=premium_since,json=premiumSince,proto3,oneof" json:"premium_since,omitempty"`
	Banner            *types.ChatPhoto       `protobuf:"bytes,4,opt,name=banner,proto3,oneof" json:"banner,omitempty"`
	MutualCommunities []uint64               `protobuf:"fixed64,5,rep,packed,name=mutual_communities,json=mutualCommunities,proto3" json:"mutual_communities,omitempty"`
	MutualFriends     []uint64               `protobuf:"fixed64,6,rep,packed,name=mutual_friends,json=mutualFriends,proto3" json:"mutual_friends,omitempty"`
	ThemeColor        *uint64                `protobuf:"varint,7,opt,name=theme_color,json=themeColor,proto3,oneof" json:"theme_color,omitempty"`
	ShowBannerInVoice *bool                  `protobuf:"varint,8,opt,name=show_banner_in_voice,json=showBannerInVoice,proto3,oneof" json:"show_banner_in_voice,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetRef() *refs.UserRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Profile) GetPremiumSince() uint64 {
	if x != nil && x.PremiumSince != nil {
		return *x.PremiumSince
	}
	return 0
}

func (x *Profile) GetBanner() *types.ChatPhoto {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *Profile) GetMutualCommunities() []uint64 {
	if x != nil {
		return x.MutualCommunities
	}
	return nil
}

func (x *Profile) GetMutualFriends() []uint64 {
	if x != nil {
		return x.MutualFriends
	}
	return nil
}

func (x *Profile) GetThemeColor() uint64 {
	if x != nil && x.ThemeColor != nil {
		return *x.ThemeColor
	}
	return 0
}

func (x *Profile) GetShowBannerInVoice() bool {
	if x != nil && x.ShowBannerInVoice != nil {
		return *x.ShowBannerInVoice
	}
	return false
}

// users.lookupUsername -> UserDetails
type LookupUsername struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupUsername) Reset() {
	*x = LookupUsername{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupUsername) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupUsername) ProtoMessage() {}

func (x *LookupUsername) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupUsername.ProtoReflect.Descriptor instead.
func (*LookupUsername) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *LookupUsername) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *types.User            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *UserDetails) GetUser() *types.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x13osmium.client.users\x1a\n" +
	"refs.proto\x1a\vtypes.proto\"d\n" +
	"\n" +
	"GetProfile\x12-\n" +
	"\x03ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.UserRefR\x03ref\x12'\n" +
	"\x0finclude_mutuals\x18\x02 \x01(\bR\x0eincludeMutuals\"\xa9\x03\n" +
	"\aProfile\x12-\n" +
	"\x03ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.UserRefR\x03ref\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12(\n" +
	"\rpremium_since\x18\x03 \x01(\x06H\x00R\fpremiumSince\x88\x01\x01\x12;\n" +
	"\x06banner\x18\x04 \x01(\v2\x1e.osmium.client.types.ChatPhotoH\x01R\x06banner\x88\x01\x01\x12-\n" +
	"\x12mutual_communities\x18\x05 \x03(\x06R\x11mutualCommunities\x12%\n" +
	"\x0emutual_friends\x18\x06 \x03(\x06R\rmutualFriends\x12$\n" +
	"\vtheme_color\x18\a \x01(\x04H\x02R\n" +
	"themeColor\x88\x01\x01\x124\n" +
	"\x14show_banner_in_voice\x18\b \x01(\bH\x03R\x11showBannerInVoice\x88\x01\x01B\x10\n" +
	"\x0e_premium_sinceB\t\n" +
	"\a_bannerB\x0e\n" +
	"\f_theme_colorB\x17\n" +
	"\x15_show_banner_in_voice\",\n" +
	"\x0eLookupUsername\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"<\n" +
	"\vUserDetails\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.osmium.client.types.UserR\x04userb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_users_proto_goTypes = []any{
	(*GetProfile)(nil),      // 0: osmium.client.users.GetProfile
	(*Profile)(nil),         // 1: osmium.client.users.Profile
	(*LookupUsername)(nil),  // 2: osmium.client.users.LookupUsername
	(*UserDetails)(nil),     // 3: osmium.client.users.UserDetails
	(*refs.UserRef)(nil),    // 4: osmium.client.refs.UserRef
	(*types.ChatPhoto)(nil), // 5: osmium.client.types.ChatPhoto
	(*types.User)(nil),      // 6: osmium.client.types.User
}
var file_users_proto_depIdxs = []int32{
	4, // 0: osmium.client.users.GetProfile.ref:type_name -> osmium.client.refs.UserRef
	4, // 1: osmium.client.users.Profile.ref:type_name -> osmium.client.refs.UserRef
	5, // 2: osmium.client.users.Profile.banner:type_name -> osmium.client.types.ChatPhoto
	6, // 3: osmium.client.users.UserDetails.user:type_name -> osmium.client.types.User
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	file_users_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
