// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// source: updates.proto

package updates

import (
	chats "github.com/ofabiodev/osmose/proto/chats"
	reactions "github.com/ofabiodev/osmose/proto/reactions"
	refs "github.com/ofabiodev/osmose/proto/refs"
	types "github.com/ofabiodev/osmose/proto/types"
	voice "github.com/ofabiodev/osmose/proto/voice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Update struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*Update_MessageCreated
	//	*Update_Channel
	//	*Update_MessageDeleted
	//	*Update_UserStatus
	//	*Update_User
	//	*Update_Community
	//	*Update_ChannelDeleted
	//	*Update_Message
	//	*Update_ChatTyping
	//	*Update_CommunityMember
	//	*Update_CommunityDeleted
	//	*Update_ConversationPermissions
	//	*Update_Chat
	//	*Update_SessionDeleted
	//	*Update_CommunityUnavailable
	//	*Update_MemberList
	//	*Update_CommunityMemberDeleted
	//	*Update_UpdateUserRelationship
	//	*Update_UpdateUserRelationshipDeleted
	//	*Update_Group
	//	*Update_RoomState
	//	*Update_RoomParticipant
	//	*Update_MessageReactions
	//	*Update_ConversationLastRead
	//	*Update_CommunityMemberCreated
	//	*Update_Interaction
	//	*Update_UserStatusBatch
	Update        isUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_updates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{0}
}

func (x *Update) GetUpdate() isUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *Update) GetMessageCreated() *UpdateMessageCreated {
	if x != nil {
		if x, ok := x.Update.(*Update_MessageCreated); ok {
			return x.MessageCreated
		}
	}
	return nil
}

func (x *Update) GetChannel() *UpdateChannel {
	if x != nil {
		if x, ok := x.Update.(*Update_Channel); ok {
			return x.Channel
		}
	}
	return nil
}

func (x *Update) GetMessageDeleted() *UpdateMessageDeleted {
	if x != nil {
		if x, ok := x.Update.(*Update_MessageDeleted); ok {
			return x.MessageDeleted
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in updates.proto.
func (x *Update) GetUserStatus() *UpdateUserStatus {
	if x != nil {
		if x, ok := x.Update.(*Update_UserStatus); ok {
			return x.UserStatus
		}
	}
	return nil
}

func (x *Update) GetUser() *UpdateUser {
	if x != nil {
		if x, ok := x.Update.(*Update_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *Update) GetCommunity() *UpdateCommunity {
	if x != nil {
		if x, ok := x.Update.(*Update_Community); ok {
			return x.Community
		}
	}
	return nil
}

func (x *Update) GetChannelDeleted() *UpdateChannelDeleted {
	if x != nil {
		if x, ok := x.Update.(*Update_ChannelDeleted); ok {
			return x.ChannelDeleted
		}
	}
	return nil
}

func (x *Update) GetMessage() *UpdateMessage {
	if x != nil {
		if x, ok := x.Update.(*Update_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Update) GetChatTyping() *UpdateChatTyping {
	if x != nil {
		if x, ok := x.Update.(*Update_ChatTyping); ok {
			return x.ChatTyping
		}
	}
	return nil
}

func (x *Update) GetCommunityMember() *UpdateCommunityMember {
	if x != nil {
		if x, ok := x.Update.(*Update_CommunityMember); ok {
			return x.CommunityMember
		}
	}
	return nil
}

func (x *Update) GetCommunityDeleted() *UpdateCommunityDeleted {
	if x != nil {
		if x, ok := x.Update.(*Update_CommunityDeleted); ok {
			return x.CommunityDeleted
		}
	}
	return nil
}

func (x *Update) GetConversationPermissions() *UpdateConversationPermissions {
	if x != nil {
		if x, ok := x.Update.(*Update_ConversationPermissions); ok {
			return x.ConversationPermissions
		}
	}
	return nil
}

func (x *Update) GetChat() *UpdateChat {
	if x != nil {
		if x, ok := x.Update.(*Update_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Update) GetSessionDeleted() *UpdateSessionDeleted {
	if x != nil {
		if x, ok := x.Update.(*Update_SessionDeleted); ok {
			return x.SessionDeleted
		}
	}
	return nil
}

func (x *Update) GetCommunityUnavailable() *UpdateCommunityUnavailable {
	if x != nil {
		if x, ok := x.Update.(*Update_CommunityUnavailable); ok {
			return x.CommunityUnavailable
		}
	}
	return nil
}

func (x *Update) GetMemberList() *UpdateMemberList {
	if x != nil {
		if x, ok := x.Update.(*Update_MemberList); ok {
			return x.MemberList
		}
	}
	return nil
}

func (x *Update) GetCommunityMemberDeleted() *UpdateCommunityMemberDeleted {
	if x != nil {
		if x, ok := x.Update.(*Update_CommunityMemberDeleted); ok {
			return x.CommunityMemberDeleted
		}
	}
	return nil
}

func (x *Update) GetUpdateUserRelationship() *UpdateUserRelationship {
	if x != nil {
		if x, ok := x.Update.(*Update_UpdateUserRelationship); ok {
			return x.UpdateUserRelationship
		}
	}
	return nil
}

func (x *Update) GetUpdateUserRelationshipDeleted() *UpdateUserRelationshipDeleted {
	if x != nil {
		if x, ok := x.Update.(*Update_UpdateUserRelationshipDeleted); ok {
			return x.UpdateUserRelationshipDeleted
		}
	}
	return nil
}

func (x *Update) GetGroup() *UpdateGroup {
	if x != nil {
		if x, ok := x.Update.(*Update_Group); ok {
			return x.Group
		}
	}
	return nil
}

func (x *Update) GetRoomState() *voice.UpdateRoomState {
	if x != nil {
		if x, ok := x.Update.(*Update_RoomState); ok {
			return x.RoomState
		}
	}
	return nil
}

func (x *Update) GetRoomParticipant() *voice.UpdateRoomParticipant {
	if x != nil {
		if x, ok := x.Update.(*Update_RoomParticipant); ok {
			return x.RoomParticipant
		}
	}
	return nil
}

func (x *Update) GetMessageReactions() *UpdateMessageReactions {
	if x != nil {
		if x, ok := x.Update.(*Update_MessageReactions); ok {
			return x.MessageReactions
		}
	}
	return nil
}

func (x *Update) GetConversationLastRead() *UpdateConversationLastRead {
	if x != nil {
		if x, ok := x.Update.(*Update_ConversationLastRead); ok {
			return x.ConversationLastRead
		}
	}
	return nil
}

func (x *Update) GetCommunityMemberCreated() *UpdateCommunityMemberCreated {
	if x != nil {
		if x, ok := x.Update.(*Update_CommunityMemberCreated); ok {
			return x.CommunityMemberCreated
		}
	}
	return nil
}

func (x *Update) GetInteraction() *UpdateInteraction {
	if x != nil {
		if x, ok := x.Update.(*Update_Interaction); ok {
			return x.Interaction
		}
	}
	return nil
}

func (x *Update) GetUserStatusBatch() *UpdateUserStatusBatch {
	if x != nil {
		if x, ok := x.Update.(*Update_UserStatusBatch); ok {
			return x.UserStatusBatch
		}
	}
	return nil
}

type isUpdate_Update interface {
	isUpdate_Update()
}

type Update_MessageCreated struct {
	MessageCreated *UpdateMessageCreated `protobuf:"bytes,1,opt,name=message_created,json=messageCreated,proto3,oneof"`
}

type Update_Channel struct {
	Channel *UpdateChannel `protobuf:"bytes,2,opt,name=channel,proto3,oneof"`
}

type Update_MessageDeleted struct {
	MessageDeleted *UpdateMessageDeleted `protobuf:"bytes,3,opt,name=message_deleted,json=messageDeleted,proto3,oneof"`
}

type Update_UserStatus struct {
	// Deprecated: Marked as deprecated in updates.proto.
	UserStatus *UpdateUserStatus `protobuf:"bytes,4,opt,name=user_status,json=userStatus,proto3,oneof"`
}

type Update_User struct {
	User *UpdateUser `protobuf:"bytes,5,opt,name=user,proto3,oneof"`
}

type Update_Community struct {
	Community *UpdateCommunity `protobuf:"bytes,6,opt,name=community,proto3,oneof"`
}

type Update_ChannelDeleted struct {
	ChannelDeleted *UpdateChannelDeleted `protobuf:"bytes,7,opt,name=channel_deleted,json=channelDeleted,proto3,oneof"`
}

type Update_Message struct {
	Message *UpdateMessage `protobuf:"bytes,8,opt,name=message,proto3,oneof"`
}

type Update_ChatTyping struct {
	ChatTyping *UpdateChatTyping `protobuf:"bytes,9,opt,name=chat_typing,json=chatTyping,proto3,oneof"`
}

type Update_CommunityMember struct {
	CommunityMember *UpdateCommunityMember `protobuf:"bytes,10,opt,name=community_member,json=communityMember,proto3,oneof"`
}

type Update_CommunityDeleted struct {
	CommunityDeleted *UpdateCommunityDeleted `protobuf:"bytes,11,opt,name=community_deleted,json=communityDeleted,proto3,oneof"`
}

type Update_ConversationPermissions struct {
	ConversationPermissions *UpdateConversationPermissions `protobuf:"bytes,12,opt,name=conversation_permissions,json=conversationPermissions,proto3,oneof"`
}

type Update_Chat struct {
	Chat *UpdateChat `protobuf:"bytes,13,opt,name=chat,proto3,oneof"`
}

type Update_SessionDeleted struct {
	SessionDeleted *UpdateSessionDeleted `protobuf:"bytes,14,opt,name=session_deleted,json=sessionDeleted,proto3,oneof"`
}

type Update_CommunityUnavailable struct {
	CommunityUnavailable *UpdateCommunityUnavailable `protobuf:"bytes,15,opt,name=community_unavailable,json=communityUnavailable,proto3,oneof"`
}

type Update_MemberList struct {
	MemberList *UpdateMemberList `protobuf:"bytes,16,opt,name=member_list,json=memberList,proto3,oneof"`
}

type Update_CommunityMemberDeleted struct {
	CommunityMemberDeleted *UpdateCommunityMemberDeleted `protobuf:"bytes,17,opt,name=community_member_deleted,json=communityMemberDeleted,proto3,oneof"`
}

type Update_UpdateUserRelationship struct {
	UpdateUserRelationship *UpdateUserRelationship `protobuf:"bytes,18,opt,name=update_user_relationship,json=updateUserRelationship,proto3,oneof"`
}

type Update_UpdateUserRelationshipDeleted struct {
	UpdateUserRelationshipDeleted *UpdateUserRelationshipDeleted `protobuf:"bytes,19,opt,name=update_user_relationship_deleted,json=updateUserRelationshipDeleted,proto3,oneof"`
}

type Update_Group struct {
	Group *UpdateGroup `protobuf:"bytes,20,opt,name=group,proto3,oneof"`
}

type Update_RoomState struct {
	RoomState *voice.UpdateRoomState `protobuf:"bytes,21,opt,name=room_state,json=roomState,proto3,oneof"`
}

type Update_RoomParticipant struct {
	RoomParticipant *voice.UpdateRoomParticipant `protobuf:"bytes,22,opt,name=room_participant,json=roomParticipant,proto3,oneof"`
}

type Update_MessageReactions struct {
	MessageReactions *UpdateMessageReactions `protobuf:"bytes,23,opt,name=message_reactions,json=messageReactions,proto3,oneof"`
}

type Update_ConversationLastRead struct {
	ConversationLastRead *UpdateConversationLastRead `protobuf:"bytes,24,opt,name=conversation_last_read,json=conversationLastRead,proto3,oneof"`
}

type Update_CommunityMemberCreated struct {
	CommunityMemberCreated *UpdateCommunityMemberCreated `protobuf:"bytes,25,opt,name=community_member_created,json=communityMemberCreated,proto3,oneof"`
}

type Update_Interaction struct {
	Interaction *UpdateInteraction `protobuf:"bytes,26,opt,name=interaction,proto3,oneof"`
}

type Update_UserStatusBatch struct {
	UserStatusBatch *UpdateUserStatusBatch `protobuf:"bytes,27,opt,name=user_status_batch,json=userStatusBatch,proto3,oneof"`
}

func (*Update_MessageCreated) isUpdate_Update() {}

func (*Update_Channel) isUpdate_Update() {}

func (*Update_MessageDeleted) isUpdate_Update() {}

func (*Update_UserStatus) isUpdate_Update() {}

func (*Update_User) isUpdate_Update() {}

func (*Update_Community) isUpdate_Update() {}

func (*Update_ChannelDeleted) isUpdate_Update() {}

func (*Update_Message) isUpdate_Update() {}

func (*Update_ChatTyping) isUpdate_Update() {}

func (*Update_CommunityMember) isUpdate_Update() {}

func (*Update_CommunityDeleted) isUpdate_Update() {}

func (*Update_ConversationPermissions) isUpdate_Update() {}

func (*Update_Chat) isUpdate_Update() {}

func (*Update_SessionDeleted) isUpdate_Update() {}

func (*Update_CommunityUnavailable) isUpdate_Update() {}

func (*Update_MemberList) isUpdate_Update() {}

func (*Update_CommunityMemberDeleted) isUpdate_Update() {}

func (*Update_UpdateUserRelationship) isUpdate_Update() {}

func (*Update_UpdateUserRelationshipDeleted) isUpdate_Update() {}

func (*Update_Group) isUpdate_Update() {}

func (*Update_RoomState) isUpdate_Update() {}

func (*Update_RoomParticipant) isUpdate_Update() {}

func (*Update_MessageReactions) isUpdate_Update() {}

func (*Update_ConversationLastRead) isUpdate_Update() {}

func (*Update_CommunityMemberCreated) isUpdate_Update() {}

func (*Update_Interaction) isUpdate_Update() {}

func (*Update_UserStatusBatch) isUpdate_Update() {}

type UpdateMessageCreated struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Message            *types.Message         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ChannelUnreadCount uint32                 `protobuf:"varint,2,opt,name=channel_unread_count,json=channelUnreadCount,proto3" json:"channel_unread_count,omitempty"`
	// The author of the message. Mostly used in communities. Do not assume this
	// is always present.
	Author        *types.User `protobuf:"bytes,3,opt,name=author,proto3,oneof" json:"author,omitempty"`
	ClientId      *uint64     `protobuf:"fixed64,4,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageCreated) Reset() {
	*x = UpdateMessageCreated{}
	mi := &file_updates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageCreated) ProtoMessage() {}

func (x *UpdateMessageCreated) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageCreated.ProtoReflect.Descriptor instead.
func (*UpdateMessageCreated) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMessageCreated) GetMessage() *types.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *UpdateMessageCreated) GetChannelUnreadCount() uint32 {
	if x != nil {
		return x.ChannelUnreadCount
	}
	return 0
}

func (x *UpdateMessageCreated) GetAuthor() *types.User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *UpdateMessageCreated) GetClientId() uint64 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

type UpdateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *types.Message         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessage) Reset() {
	*x = UpdateMessage{}
	mi := &file_updates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessage) ProtoMessage() {}

func (x *UpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessage.ProtoReflect.Descriptor instead.
func (*UpdateMessage) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMessage) GetMessage() *types.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type UpdateChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *types.Channel         `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannel) Reset() {
	*x = UpdateChannel{}
	mi := &file_updates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannel) ProtoMessage() {}

func (x *UpdateChannel) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannel.ProtoReflect.Descriptor instead.
func (*UpdateChannel) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateChannel) GetChannel() *types.Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type UpdateChannelDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *refs.ChannelRef       `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelDeleted) Reset() {
	*x = UpdateChannelDeleted{}
	mi := &file_updates_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelDeleted) ProtoMessage() {}

func (x *UpdateChannelDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelDeleted.ProtoReflect.Descriptor instead.
func (*UpdateChannelDeleted) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateChannelDeleted) GetChannel() *refs.ChannelRef {
	if x != nil {
		return x.Channel
	}
	return nil
}

type UpdateMessageDeleted struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<Message>
	MessageIds    []uint64 `protobuf:"fixed64,2,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageDeleted) Reset() {
	*x = UpdateMessageDeleted{}
	mi := &file_updates_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageDeleted) ProtoMessage() {}

func (x *UpdateMessageDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageDeleted.ProtoReflect.Descriptor instead.
func (*UpdateMessageDeleted) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMessageDeleted) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *UpdateMessageDeleted) GetMessageIds() []uint64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type UpdateUserStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<User>
	UserId        uint64            `protobuf:"fixed64,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        *types.UserStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatus) Reset() {
	*x = UpdateUserStatus{}
	mi := &file_updates_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatus) ProtoMessage() {}

func (x *UpdateUserStatus) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatus.ProtoReflect.Descriptor instead.
func (*UpdateUserStatus) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserStatus) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserStatus) GetStatus() *types.UserStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateUserStatusBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*UpdateUserStatus    `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusBatch) Reset() {
	*x = UpdateUserStatusBatch{}
	mi := &file_updates_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusBatch) ProtoMessage() {}

func (x *UpdateUserStatusBatch) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusBatch.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusBatch) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserStatusBatch) GetUpdates() []*UpdateUserStatus {
	if x != nil {
		return x.Updates
	}
	return nil
}

type UpdateUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<User>
	UserId        uint64      `protobuf:"fixed64,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User          *types.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUser) Reset() {
	*x = UpdateUser{}
	mi := &file_updates_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUser) ProtoMessage() {}

func (x *UpdateUser) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUser.ProtoReflect.Descriptor instead.
func (*UpdateUser) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUser) GetUser() *types.User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateCommunity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Community>
	CommunityId   uint64           `protobuf:"fixed64,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Community     *types.Community `protobuf:"bytes,2,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunity) Reset() {
	*x = UpdateCommunity{}
	mi := &file_updates_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunity) ProtoMessage() {}

func (x *UpdateCommunity) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunity.ProtoReflect.Descriptor instead.
func (*UpdateCommunity) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCommunity) GetCommunityId() uint64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *UpdateCommunity) GetCommunity() *types.Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type UpdateCommunityDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Community>
	CommunityId   uint64 `protobuf:"fixed64,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityDeleted) Reset() {
	*x = UpdateCommunityDeleted{}
	mi := &file_updates_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityDeleted) ProtoMessage() {}

func (x *UpdateCommunityDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityDeleted.ProtoReflect.Descriptor instead.
func (*UpdateCommunityDeleted) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCommunityDeleted) GetCommunityId() uint64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

type UpdateChatTyping struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<User>
	UserId        uint64              `protobuf:"fixed64,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Typing        bool                `protobuf:"varint,3,opt,name=typing,proto3" json:"typing,omitempty"`
	Action        *chats.TypingAction `protobuf:"varint,4,opt,name=action,proto3,enum=osmium.client.chats.TypingAction,oneof" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatTyping) Reset() {
	*x = UpdateChatTyping{}
	mi := &file_updates_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatTyping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatTyping) ProtoMessage() {}

func (x *UpdateChatTyping) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatTyping.ProtoReflect.Descriptor instead.
func (*UpdateChatTyping) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateChatTyping) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *UpdateChatTyping) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateChatTyping) GetTyping() bool {
	if x != nil {
		return x.Typing
	}
	return false
}

func (x *UpdateChatTyping) GetAction() chats.TypingAction {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return chats.TypingAction(0)
}

type UpdateCommunityMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Community>
	CommunityId uint64 `protobuf:"fixed64,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	// @snowflake<User>
	MemberId      uint64                 `protobuf:"fixed64,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Member        *types.CommunityMember `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityMember) Reset() {
	*x = UpdateCommunityMember{}
	mi := &file_updates_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityMember) ProtoMessage() {}

func (x *UpdateCommunityMember) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityMember.ProtoReflect.Descriptor instead.
func (*UpdateCommunityMember) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCommunityMember) GetCommunityId() uint64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *UpdateCommunityMember) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *UpdateCommunityMember) GetMember() *types.CommunityMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type UpdateCommunityMemberDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Community>
	CommunityId uint64 `protobuf:"fixed64,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	// @snowflake<User>
	MemberId      uint64 `protobuf:"fixed64,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityMemberDeleted) Reset() {
	*x = UpdateCommunityMemberDeleted{}
	mi := &file_updates_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityMemberDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityMemberDeleted) ProtoMessage() {}

func (x *UpdateCommunityMemberDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityMemberDeleted.ProtoReflect.Descriptor instead.
func (*UpdateCommunityMemberDeleted) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateCommunityMemberDeleted) GetCommunityId() uint64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *UpdateCommunityMemberDeleted) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type UpdateCommunityMemberCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Community>
	CommunityId uint64 `protobuf:"fixed64,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	// @snowflake<User>
	MemberId      uint64                 `protobuf:"fixed64,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Member        *types.CommunityMember `protobuf:"bytes,3,opt,name=member,proto3,oneof" json:"member,omitempty"`
	User          *types.User            `protobuf:"bytes,4,opt,name=user,proto3,oneof" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityMemberCreated) Reset() {
	*x = UpdateCommunityMemberCreated{}
	mi := &file_updates_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityMemberCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityMemberCreated) ProtoMessage() {}

func (x *UpdateCommunityMemberCreated) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityMemberCreated.ProtoReflect.Descriptor instead.
func (*UpdateCommunityMemberCreated) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateCommunityMemberCreated) GetCommunityId() uint64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *UpdateCommunityMemberCreated) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *UpdateCommunityMemberCreated) GetMember() *types.CommunityMember {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *UpdateCommunityMemberCreated) GetUser() *types.User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateConversationPermissions struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ChatRef       *refs.ChatRef              `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	Permissions   *types.PermissionOverrides `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationPermissions) Reset() {
	*x = UpdateConversationPermissions{}
	mi := &file_updates_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationPermissions) ProtoMessage() {}

func (x *UpdateConversationPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationPermissions.ProtoReflect.Descriptor instead.
func (*UpdateConversationPermissions) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateConversationPermissions) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *UpdateConversationPermissions) GetPermissions() *types.PermissionOverrides {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UpdateChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *chats.Chat            `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChat) Reset() {
	*x = UpdateChat{}
	mi := &file_updates_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChat) ProtoMessage() {}

func (x *UpdateChat) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChat.ProtoReflect.Descriptor instead.
func (*UpdateChat) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateChat) GetChat() *chats.Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type UpdateSessionDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Session>
	SessionId     uint64 `protobuf:"fixed64,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionDeleted) Reset() {
	*x = UpdateSessionDeleted{}
	mi := &file_updates_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionDeleted) ProtoMessage() {}

func (x *UpdateSessionDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionDeleted.ProtoReflect.Descriptor instead.
func (*UpdateSessionDeleted) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateSessionDeleted) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type UpdateCommunityUnavailable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Community>
	CommunityId   uint64 `protobuf:"fixed64,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityUnavailable) Reset() {
	*x = UpdateCommunityUnavailable{}
	mi := &file_updates_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityUnavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityUnavailable) ProtoMessage() {}

func (x *UpdateCommunityUnavailable) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityUnavailable.ProtoReflect.Descriptor instead.
func (*UpdateCommunityUnavailable) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateCommunityUnavailable) GetCommunityId() uint64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

type UpdateMemberList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Community>
	CommunityId *uint64 `protobuf:"fixed64,1,opt,name=community_id,json=communityId,proto3,oneof" json:"community_id,omitempty"`
	// @snowflake<Channel>
	ChannelId     uint64             `protobuf:"fixed64,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Entries       []*MemberListEntry `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberList) Reset() {
	*x = UpdateMemberList{}
	mi := &file_updates_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberList) ProtoMessage() {}

func (x *UpdateMemberList) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberList.ProtoReflect.Descriptor instead.
func (*UpdateMemberList) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateMemberList) GetCommunityId() uint64 {
	if x != nil && x.CommunityId != nil {
		return *x.CommunityId
	}
	return 0
}

func (x *UpdateMemberList) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *UpdateMemberList) GetEntries() []*MemberListEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MemberListEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entry:
	//
	//	*MemberListEntry_User
	//	*MemberListEntry_Divider
	Entry         isMemberListEntry_Entry `protobuf_oneof:"entry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberListEntry) Reset() {
	*x = MemberListEntry{}
	mi := &file_updates_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberListEntry) ProtoMessage() {}

func (x *MemberListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberListEntry.ProtoReflect.Descriptor instead.
func (*MemberListEntry) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{20}
}

func (x *MemberListEntry) GetEntry() isMemberListEntry_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *MemberListEntry) GetUser() *MemberListEntryUser {
	if x != nil {
		if x, ok := x.Entry.(*MemberListEntry_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *MemberListEntry) GetDivider() *MemberListEntryDivider {
	if x != nil {
		if x, ok := x.Entry.(*MemberListEntry_Divider); ok {
			return x.Divider
		}
	}
	return nil
}

type isMemberListEntry_Entry interface {
	isMemberListEntry_Entry()
}

type MemberListEntry_User struct {
	User *MemberListEntryUser `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

type MemberListEntry_Divider struct {
	Divider *MemberListEntryDivider `protobuf:"bytes,2,opt,name=divider,proto3,oneof"`
}

func (*MemberListEntry_User) isMemberListEntry_Entry() {}

func (*MemberListEntry_Divider) isMemberListEntry_Entry() {}

type MemberListEntryUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *types.User            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Nickname      *string                `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberListEntryUser) Reset() {
	*x = MemberListEntryUser{}
	mi := &file_updates_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberListEntryUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberListEntryUser) ProtoMessage() {}

func (x *MemberListEntryUser) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberListEntryUser.ProtoReflect.Descriptor instead.
func (*MemberListEntryUser) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{21}
}

func (x *MemberListEntryUser) GetUser() *types.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *MemberListEntryUser) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

type MemberListEntryDivider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Inner:
	//
	//	*MemberListEntryDivider_Online
	//	*MemberListEntryDivider_RoleId
	Inner         isMemberListEntryDivider_Inner `protobuf_oneof:"inner"`
	MemberCount   uint32                         `protobuf:"varint,3,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberListEntryDivider) Reset() {
	*x = MemberListEntryDivider{}
	mi := &file_updates_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberListEntryDivider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberListEntryDivider) ProtoMessage() {}

func (x *MemberListEntryDivider) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberListEntryDivider.ProtoReflect.Descriptor instead.
func (*MemberListEntryDivider) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{22}
}

func (x *MemberListEntryDivider) GetInner() isMemberListEntryDivider_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *MemberListEntryDivider) GetOnline() bool {
	if x != nil {
		if x, ok := x.Inner.(*MemberListEntryDivider_Online); ok {
			return x.Online
		}
	}
	return false
}

func (x *MemberListEntryDivider) GetRoleId() uint64 {
	if x != nil {
		if x, ok := x.Inner.(*MemberListEntryDivider_RoleId); ok {
			return x.RoleId
		}
	}
	return 0
}

func (x *MemberListEntryDivider) GetMemberCount() uint32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type isMemberListEntryDivider_Inner interface {
	isMemberListEntryDivider_Inner()
}

type MemberListEntryDivider_Online struct {
	Online bool `protobuf:"varint,1,opt,name=online,proto3,oneof"`
}

type MemberListEntryDivider_RoleId struct {
	// @snowflake<Role>
	RoleId uint64 `protobuf:"fixed64,2,opt,name=role_id,json=roleId,proto3,oneof"`
}

func (*MemberListEntryDivider_Online) isMemberListEntryDivider_Inner() {}

func (*MemberListEntryDivider_RoleId) isMemberListEntryDivider_Inner() {}

type UpdateUserRelationship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relationship  *types.Relationship    `protobuf:"bytes,1,opt,name=relationship,proto3" json:"relationship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRelationship) Reset() {
	*x = UpdateUserRelationship{}
	mi := &file_updates_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRelationship) ProtoMessage() {}

func (x *UpdateUserRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRelationship.ProtoReflect.Descriptor instead.
func (*UpdateUserRelationship) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateUserRelationship) GetRelationship() *types.Relationship {
	if x != nil {
		return x.Relationship
	}
	return nil
}

type UpdateUserRelationshipDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<User>
	OtherUserId   uint64 `protobuf:"fixed64,1,opt,name=other_user_id,json=otherUserId,proto3" json:"other_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRelationshipDeleted) Reset() {
	*x = UpdateUserRelationshipDeleted{}
	mi := &file_updates_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRelationshipDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRelationshipDeleted) ProtoMessage() {}

func (x *UpdateUserRelationshipDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRelationshipDeleted.ProtoReflect.Descriptor instead.
func (*UpdateUserRelationshipDeleted) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateUserRelationshipDeleted) GetOtherUserId() uint64 {
	if x != nil {
		return x.OtherUserId
	}
	return 0
}

type UpdateGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *types.Group           `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Users         []*types.User          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroup) Reset() {
	*x = UpdateGroup{}
	mi := &file_updates_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroup) ProtoMessage() {}

func (x *UpdateGroup) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroup.ProtoReflect.Descriptor instead.
func (*UpdateGroup) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateGroup) GetGroup() *types.Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *UpdateGroup) GetUsers() []*types.User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateMessageReactions struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ChatRef       *refs.ChatRef               `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	Reactions     *reactions.MessageReactions `protobuf:"bytes,2,opt,name=reactions,proto3" json:"reactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageReactions) Reset() {
	*x = UpdateMessageReactions{}
	mi := &file_updates_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageReactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageReactions) ProtoMessage() {}

func (x *UpdateMessageReactions) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageReactions.ProtoReflect.Descriptor instead.
func (*UpdateMessageReactions) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateMessageReactions) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *UpdateMessageReactions) GetReactions() *reactions.MessageReactions {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type UpdateConversationLastRead struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<Message>
	LastReadMessageId   uint64  `protobuf:"fixed64,2,opt,name=last_read_message_id,json=lastReadMessageId,proto3" json:"last_read_message_id,omitempty"`
	UnreadCount         *uint32 `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3,oneof" json:"unread_count,omitempty"`
	UnreadMentionsCount *uint32 `protobuf:"varint,4,opt,name=unread_mentions_count,json=unreadMentionsCount,proto3,oneof" json:"unread_mentions_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateConversationLastRead) Reset() {
	*x = UpdateConversationLastRead{}
	mi := &file_updates_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationLastRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationLastRead) ProtoMessage() {}

func (x *UpdateConversationLastRead) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationLastRead.ProtoReflect.Descriptor instead.
func (*UpdateConversationLastRead) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateConversationLastRead) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *UpdateConversationLastRead) GetLastReadMessageId() uint64 {
	if x != nil {
		return x.LastReadMessageId
	}
	return 0
}

func (x *UpdateConversationLastRead) GetUnreadCount() uint32 {
	if x != nil && x.UnreadCount != nil {
		return *x.UnreadCount
	}
	return 0
}

func (x *UpdateConversationLastRead) GetUnreadMentionsCount() uint32 {
	if x != nil && x.UnreadMentionsCount != nil {
		return *x.UnreadMentionsCount
	}
	return 0
}

type UpdateInteraction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Interaction>
	InteractionId uint64 `protobuf:"fixed64,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	// @snowflake<User>
	UserId uint64 `protobuf:"fixed64,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// @snowflake<Message>
	MessageId     uint64  `protobuf:"fixed64,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Data          *string `protobuf:"bytes,4,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInteraction) Reset() {
	*x = UpdateInteraction{}
	mi := &file_updates_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInteraction) ProtoMessage() {}

func (x *UpdateInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_updates_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInteraction.ProtoReflect.Descriptor instead.
func (*UpdateInteraction) Descriptor() ([]byte, []int) {
	return file_updates_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateInteraction) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *UpdateInteraction) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateInteraction) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UpdateInteraction) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

var File_updates_proto protoreflect.FileDescriptor

const file_updates_proto_rawDesc = "" +
	"\n" +
	"\rupdates.proto\x12\x15osmium.client.updates\x1a\vtypes.proto\x1a\n" +
	"refs.proto\x1a\vchats.proto\x1a\vvoice.proto\x1a\x0freactions.proto\"\xcb\x12\n" +
	"\x06Update\x12V\n" +
	"\x0fmessage_created\x18\x01 \x01(\v2+.osmium.client.updates.UpdateMessageCreatedH\x00R\x0emessageCreated\x12@\n" +
	"\achannel\x18\x02 \x01(\v2$.osmium.client.updates.UpdateChannelH\x00R\achannel\x12V\n" +
	"\x0fmessage_deleted\x18\x03 \x01(\v2+.osmium.client.updates.UpdateMessageDeletedH\x00R\x0emessageDeleted\x12N\n" +
	"\vuser_status\x18\x04 \x01(\v2'.osmium.client.updates.UpdateUserStatusB\x02\x18\x01H\x00R\n" +
	"userStatus\x127\n" +
	"\x04user\x18\x05 \x01(\v2!.osmium.client.updates.UpdateUserH\x00R\x04user\x12F\n" +
	"\tcommunity\x18\x06 \x01(\v2&.osmium.client.updates.UpdateCommunityH\x00R\tcommunity\x12V\n" +
	"\x0fchannel_deleted\x18\a \x01(\v2+.osmium.client.updates.UpdateChannelDeletedH\x00R\x0echannelDeleted\x12@\n" +
	"\amessage\x18\b \x01(\v2$.osmium.client.updates.UpdateMessageH\x00R\amessage\x12J\n" +
	"\vchat_typing\x18\t \x01(\v2'.osmium.client.updates.UpdateChatTypingH\x00R\n" +
	"chatTyping\x12Y\n" +
	"\x10community_member\x18\n" +
	" \x01(\v2,.osmium.client.updates.UpdateCommunityMemberH\x00R\x0fcommunityMember\x12\\\n" +
	"\x11community_deleted\x18\v \x01(\v2-.osmium.client.updates.UpdateCommunityDeletedH\x00R\x10communityDeleted\x12q\n" +
	"\x18conversation_permissions\x18\f \x01(\v24.osmium.client.updates.UpdateConversationPermissionsH\x00R\x17conversationPermissions\x127\n" +
	"\x04chat\x18\r \x01(\v2!.osmium.client.updates.UpdateChatH\x00R\x04chat\x12V\n" +
	"\x0fsession_deleted\x18\x0e \x01(\v2+.osmium.client.updates.UpdateSessionDeletedH\x00R\x0esessionDeleted\x12h\n" +
	"\x15community_unavailable\x18\x0f \x01(\v21.osmium.client.updates.UpdateCommunityUnavailableH\x00R\x14communityUnavailable\x12J\n" +
	"\vmember_list\x18\x10 \x01(\v2'.osmium.client.updates.UpdateMemberListH\x00R\n" +
	"memberList\x12o\n" +
	"\x18community_member_deleted\x18\x11 \x01(\v23.osmium.client.updates.UpdateCommunityMemberDeletedH\x00R\x16communityMemberDeleted\x12i\n" +
	"\x18update_user_relationship\x18\x12 \x01(\v2-.osmium.client.updates.UpdateUserRelationshipH\x00R\x16updateUserRelationship\x12\x7f\n" +
	" update_user_relationship_deleted\x18\x13 \x01(\v24.osmium.client.updates.UpdateUserRelationshipDeletedH\x00R\x1dupdateUserRelationshipDeleted\x12:\n" +
	"\x05group\x18\x14 \x01(\v2\".osmium.client.updates.UpdateGroupH\x00R\x05group\x12E\n" +
	"\n" +
	"room_state\x18\x15 \x01(\v2$.osmium.client.voice.UpdateRoomStateH\x00R\troomState\x12W\n" +
	"\x10room_participant\x18\x16 \x01(\v2*.osmium.client.voice.UpdateRoomParticipantH\x00R\x0froomParticipant\x12\\\n" +
	"\x11message_reactions\x18\x17 \x01(\v2-.osmium.client.updates.UpdateMessageReactionsH\x00R\x10messageReactions\x12i\n" +
	"\x16conversation_last_read\x18\x18 \x01(\v21.osmium.client.updates.UpdateConversationLastReadH\x00R\x14conversationLastRead\x12o\n" +
	"\x18community_member_created\x18\x19 \x01(\v23.osmium.client.updates.UpdateCommunityMemberCreatedH\x00R\x16communityMemberCreated\x12L\n" +
	"\vinteraction\x18\x1a \x01(\v2(.osmium.client.updates.UpdateInteractionH\x00R\vinteraction\x12Z\n" +
	"\x11user_status_batch\x18\x1b \x01(\v2,.osmium.client.updates.UpdateUserStatusBatchH\x00R\x0fuserStatusBatchB\b\n" +
	"\x06update\"\xf3\x01\n" +
	"\x14UpdateMessageCreated\x126\n" +
	"\amessage\x18\x01 \x01(\v2\x1c.osmium.client.types.MessageR\amessage\x120\n" +
	"\x14channel_unread_count\x18\x02 \x01(\rR\x12channelUnreadCount\x126\n" +
	"\x06author\x18\x03 \x01(\v2\x19.osmium.client.types.UserH\x00R\x06author\x88\x01\x01\x12 \n" +
	"\tclient_id\x18\x04 \x01(\x06H\x01R\bclientId\x88\x01\x01B\t\n" +
	"\a_authorB\f\n" +
	"\n" +
	"_client_id\"G\n" +
	"\rUpdateMessage\x126\n" +
	"\amessage\x18\x01 \x01(\v2\x1c.osmium.client.types.MessageR\amessage\"G\n" +
	"\rUpdateChannel\x126\n" +
	"\achannel\x18\x01 \x01(\v2\x1c.osmium.client.types.ChannelR\achannel\"P\n" +
	"\x14UpdateChannelDeleted\x128\n" +
	"\achannel\x18\x01 \x01(\v2\x1e.osmium.client.refs.ChannelRefR\achannel\"o\n" +
	"\x14UpdateMessageDeleted\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\x06R\n" +
	"messageIds\"d\n" +
	"\x10UpdateUserStatus\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x06R\x06userId\x127\n" +
	"\x06status\x18\x02 \x01(\v2\x1f.osmium.client.types.UserStatusR\x06status\"Z\n" +
	"\x15UpdateUserStatusBatch\x12A\n" +
	"\aupdates\x18\x01 \x03(\v2'.osmium.client.updates.UpdateUserStatusR\aupdates\"T\n" +
	"\n" +
	"UpdateUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x06R\x06userId\x12-\n" +
	"\x04user\x18\x02 \x01(\v2\x19.osmium.client.types.UserR\x04user\"r\n" +
	"\x0fUpdateCommunity\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x06R\vcommunityId\x12<\n" +
	"\tcommunity\x18\x02 \x01(\v2\x1e.osmium.client.types.CommunityR\tcommunity\";\n" +
	"\x16UpdateCommunityDeleted\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x06R\vcommunityId\"\xc6\x01\n" +
	"\x10UpdateChatTyping\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x06R\x06userId\x12\x16\n" +
	"\x06typing\x18\x03 \x01(\bR\x06typing\x12>\n" +
	"\x06action\x18\x04 \x01(\x0e2!.osmium.client.chats.TypingActionH\x00R\x06action\x88\x01\x01B\t\n" +
	"\a_action\"\x95\x01\n" +
	"\x15UpdateCommunityMember\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x06R\vcommunityId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x06R\bmemberId\x12<\n" +
	"\x06member\x18\x03 \x01(\v2$.osmium.client.types.CommunityMemberR\x06member\"^\n" +
	"\x1cUpdateCommunityMemberDeleted\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x06R\vcommunityId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x06R\bmemberId\"\xe9\x01\n" +
	"\x1cUpdateCommunityMemberCreated\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x06R\vcommunityId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x06R\bmemberId\x12A\n" +
	"\x06member\x18\x03 \x01(\v2$.osmium.client.types.CommunityMemberH\x00R\x06member\x88\x01\x01\x122\n" +
	"\x04user\x18\x04 \x01(\v2\x19.osmium.client.types.UserH\x01R\x04user\x88\x01\x01B\t\n" +
	"\a_memberB\a\n" +
	"\x05_user\"\xa3\x01\n" +
	"\x1dUpdateConversationPermissions\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12J\n" +
	"\vpermissions\x18\x02 \x01(\v2(.osmium.client.types.PermissionOverridesR\vpermissions\";\n" +
	"\n" +
	"UpdateChat\x12-\n" +
	"\x04chat\x18\x01 \x01(\v2\x19.osmium.client.chats.ChatR\x04chat\"5\n" +
	"\x14UpdateSessionDeleted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x06R\tsessionId\"?\n" +
	"\x1aUpdateCommunityUnavailable\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x06R\vcommunityId\"\xb2\x01\n" +
	"\x10UpdateMemberList\x12&\n" +
	"\fcommunity_id\x18\x01 \x01(\x06H\x00R\vcommunityId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\x06R\tchannelId\x12@\n" +
	"\aentries\x18\x04 \x03(\v2&.osmium.client.updates.MemberListEntryR\aentriesB\x0f\n" +
	"\r_community_idJ\x04\b\x03\x10\x04\"\xa7\x01\n" +
	"\x0fMemberListEntry\x12@\n" +
	"\x04user\x18\x01 \x01(\v2*.osmium.client.updates.MemberListEntryUserH\x00R\x04user\x12I\n" +
	"\adivider\x18\x02 \x01(\v2-.osmium.client.updates.MemberListEntryDividerH\x00R\adividerB\a\n" +
	"\x05entry\"r\n" +
	"\x13MemberListEntryUser\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.osmium.client.types.UserR\x04user\x12\x1f\n" +
	"\bnickname\x18\x02 \x01(\tH\x00R\bnickname\x88\x01\x01B\v\n" +
	"\t_nickname\"y\n" +
	"\x16MemberListEntryDivider\x12\x18\n" +
	"\x06online\x18\x01 \x01(\bH\x00R\x06online\x12\x19\n" +
	"\arole_id\x18\x02 \x01(\x06H\x00R\x06roleId\x12!\n" +
	"\fmember_count\x18\x03 \x01(\rR\vmemberCountB\a\n" +
	"\x05inner\"_\n" +
	"\x16UpdateUserRelationship\x12E\n" +
	"\frelationship\x18\x01 \x01(\v2!.osmium.client.types.RelationshipR\frelationship\"C\n" +
	"\x1dUpdateUserRelationshipDeleted\x12\"\n" +
	"\rother_user_id\x18\x01 \x01(\x06R\votherUserId\"p\n" +
	"\vUpdateGroup\x120\n" +
	"\x05group\x18\x01 \x01(\v2\x1a.osmium.client.types.GroupR\x05group\x12/\n" +
	"\x05users\x18\x02 \x03(\v2\x19.osmium.client.types.UserR\x05users\"\x99\x01\n" +
	"\x16UpdateMessageReactions\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12G\n" +
	"\treactions\x18\x02 \x01(\v2).osmium.client.reactions.MessageReactionsR\treactions\"\x91\x02\n" +
	"\x1aUpdateConversationLastRead\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12/\n" +
	"\x14last_read_message_id\x18\x02 \x01(\x06R\x11lastReadMessageId\x12&\n" +
	"\funread_count\x18\x03 \x01(\rH\x00R\vunreadCount\x88\x01\x01\x127\n" +
	"\x15unread_mentions_count\x18\x04 \x01(\rH\x01R\x13unreadMentionsCount\x88\x01\x01B\x0f\n" +
	"\r_unread_countB\x18\n" +
	"\x16_unread_mentions_count\"\x94\x01\n" +
	"\x11UpdateInteraction\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x06R\rinteractionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x06R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x06R\tmessageId\x12\x17\n" +
	"\x04data\x18\x04 \x01(\tH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_datab\x06proto3"

var (
	file_updates_proto_rawDescOnce sync.Once
	file_updates_proto_rawDescData []byte
)

func file_updates_proto_rawDescGZIP() []byte {
	file_updates_proto_rawDescOnce.Do(func() {
		file_updates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_updates_proto_rawDesc), len(file_updates_proto_rawDesc)))
	})
	return file_updates_proto_rawDescData
}

var file_updates_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_updates_proto_goTypes = []any{
	(*Update)(nil),                        // 0: osmium.client.updates.Update
	(*UpdateMessageCreated)(nil),          // 1: osmium.client.updates.UpdateMessageCreated
	(*UpdateMessage)(nil),                 // 2: osmium.client.updates.UpdateMessage
	(*UpdateChannel)(nil),                 // 3: osmium.client.updates.UpdateChannel
	(*UpdateChannelDeleted)(nil),          // 4: osmium.client.updates.UpdateChannelDeleted
	(*UpdateMessageDeleted)(nil),          // 5: osmium.client.updates.UpdateMessageDeleted
	(*UpdateUserStatus)(nil),              // 6: osmium.client.updates.UpdateUserStatus
	(*UpdateUserStatusBatch)(nil),         // 7: osmium.client.updates.UpdateUserStatusBatch
	(*UpdateUser)(nil),                    // 8: osmium.client.updates.UpdateUser
	(*UpdateCommunity)(nil),               // 9: osmium.client.updates.UpdateCommunity
	(*UpdateCommunityDeleted)(nil),        // 10: osmium.client.updates.UpdateCommunityDeleted
	(*UpdateChatTyping)(nil),              // 11: osmium.client.updates.UpdateChatTyping
	(*UpdateCommunityMember)(nil),         // 12: osmium.client.updates.UpdateCommunityMember
	(*UpdateCommunityMemberDeleted)(nil),  // 13: osmium.client.updates.UpdateCommunityMemberDeleted
	(*UpdateCommunityMemberCreated)(nil),  // 14: osmium.client.updates.UpdateCommunityMemberCreated
	(*UpdateConversationPermissions)(nil), // 15: osmium.client.updates.UpdateConversationPermissions
	(*UpdateChat)(nil),                    // 16: osmium.client.updates.UpdateChat
	(*UpdateSessionDeleted)(nil),          // 17: osmium.client.updates.UpdateSessionDeleted
	(*UpdateCommunityUnavailable)(nil),    // 18: osmium.client.updates.UpdateCommunityUnavailable
	(*UpdateMemberList)(nil),              // 19: osmium.client.updates.UpdateMemberList
	(*MemberListEntry)(nil),               // 20: osmium.client.updates.MemberListEntry
	(*MemberListEntryUser)(nil),           // 21: osmium.client.updates.MemberListEntryUser
	(*MemberListEntryDivider)(nil),        // 22: osmium.client.updates.MemberListEntryDivider
	(*UpdateUserRelationship)(nil),        // 23: osmium.client.updates.UpdateUserRelationship
	(*UpdateUserRelationshipDeleted)(nil), // 24: osmium.client.updates.UpdateUserRelationshipDeleted
	(*UpdateGroup)(nil),                   // 25: osmium.client.updates.UpdateGroup
	(*UpdateMessageReactions)(nil),        // 26: osmium.client.updates.UpdateMessageReactions
	(*UpdateConversationLastRead)(nil),    // 27: osmium.client.updates.UpdateConversationLastRead
	(*UpdateInteraction)(nil),             // 28: osmium.client.updates.UpdateInteraction
	(*voice.UpdateRoomState)(nil),         // 29: osmium.client.voice.UpdateRoomState
	(*voice.UpdateRoomParticipant)(nil),   // 30: osmium.client.voice.UpdateRoomParticipant
	(*types.Message)(nil),                 // 31: osmium.client.types.Message
	(*types.User)(nil),                    // 32: osmium.client.types.User
	(*types.Channel)(nil),                 // 33: osmium.client.types.Channel
	(*refs.ChannelRef)(nil),               // 34: osmium.client.refs.ChannelRef
	(*refs.ChatRef)(nil),                  // 35: osmium.client.refs.ChatRef
	(*types.UserStatus)(nil),              // 36: osmium.client.types.UserStatus
	(*types.Community)(nil),               // 37: osmium.client.types.Community
	(chats.TypingAction)(0),               // 38: osmium.client.chats.TypingAction
	(*types.CommunityMember)(nil),         // 39: osmium.client.types.CommunityMember
	(*types.PermissionOverrides)(nil),     // 40: osmium.client.types.PermissionOverrides
	(*chats.Chat)(nil),                    // 41: osmium.client.chats.Chat
	(*types.Relationship)(nil),            // 42: osmium.client.types.Relationship
	(*types.Group)(nil),                   // 43: osmium.client.types.Group
	(*reactions.MessageReactions)(nil),    // 44: osmium.client.reactions.MessageReactions
}
var file_updates_proto_depIdxs = []int32{
	1,  // 0: osmium.client.updates.Update.message_created:type_name -> osmium.client.updates.UpdateMessageCreated
	3,  // 1: osmium.client.updates.Update.channel:type_name -> osmium.client.updates.UpdateChannel
	5,  // 2: osmium.client.updates.Update.message_deleted:type_name -> osmium.client.updates.UpdateMessageDeleted
	6,  // 3: osmium.client.updates.Update.user_status:type_name -> osmium.client.updates.UpdateUserStatus
	8,  // 4: osmium.client.updates.Update.user:type_name -> osmium.client.updates.UpdateUser
	9,  // 5: osmium.client.updates.Update.community:type_name -> osmium.client.updates.UpdateCommunity
	4,  // 6: osmium.client.updates.Update.channel_deleted:type_name -> osmium.client.updates.UpdateChannelDeleted
	2,  // 7: osmium.client.updates.Update.message:type_name -> osmium.client.updates.UpdateMessage
	11, // 8: osmium.client.updates.Update.chat_typing:type_name -> osmium.client.updates.UpdateChatTyping
	12, // 9: osmium.client.updates.Update.community_member:type_name -> osmium.client.updates.UpdateCommunityMember
	10, // 10: osmium.client.updates.Update.community_deleted:type_name -> osmium.client.updates.UpdateCommunityDeleted
	15, // 11: osmium.client.updates.Update.conversation_permissions:type_name -> osmium.client.updates.UpdateConversationPermissions
	16, // 12: osmium.client.updates.Update.chat:type_name -> osmium.client.updates.UpdateChat
	17, // 13: osmium.client.updates.Update.session_deleted:type_name -> osmium.client.updates.UpdateSessionDeleted
	18, // 14: osmium.client.updates.Update.community_unavailable:type_name -> osmium.client.updates.UpdateCommunityUnavailable
	19, // 15: osmium.client.updates.Update.member_list:type_name -> osmium.client.updates.UpdateMemberList
	13, // 16: osmium.client.updates.Update.community_member_deleted:type_name -> osmium.client.updates.UpdateCommunityMemberDeleted
	23, // 17: osmium.client.updates.Update.update_user_relationship:type_name -> osmium.client.updates.UpdateUserRelationship
	24, // 18: osmium.client.updates.Update.update_user_relationship_deleted:type_name -> osmium.client.updates.UpdateUserRelationshipDeleted
	25, // 19: osmium.client.updates.Update.group:type_name -> osmium.client.updates.UpdateGroup
	29, // 20: osmium.client.updates.Update.room_state:type_name -> osmium.client.voice.UpdateRoomState
	30, // 21: osmium.client.updates.Update.room_participant:type_name -> osmium.client.voice.UpdateRoomParticipant
	26, // 22: osmium.client.updates.Update.message_reactions:type_name -> osmium.client.updates.UpdateMessageReactions
	27, // 23: osmium.client.updates.Update.conversation_last_read:type_name -> osmium.client.updates.UpdateConversationLastRead
	14, // 24: osmium.client.updates.Update.community_member_created:type_name -> osmium.client.updates.UpdateCommunityMemberCreated
	28, // 25: osmium.client.updates.Update.interaction:type_name -> osmium.client.updates.UpdateInteraction
	7,  // 26: osmium.client.updates.Update.user_status_batch:type_name -> osmium.client.updates.UpdateUserStatusBatch
	31, // 27: osmium.client.updates.UpdateMessageCreated.message:type_name -> osmium.client.types.Message
	32, // 28: osmium.client.updates.UpdateMessageCreated.author:type_name -> osmium.client.types.User
	31, // 29: osmium.client.updates.UpdateMessage.message:type_name -> osmium.client.types.Message
	33, // 30: osmium.client.updates.UpdateChannel.channel:type_name -> osmium.client.types.Channel
	34, // 31: osmium.client.updates.UpdateChannelDeleted.channel:type_name -> osmium.client.refs.ChannelRef
	35, // 32: osmium.client.updates.UpdateMessageDeleted.chat_ref:type_name -> osmium.client.refs.ChatRef
	36, // 33: osmium.client.updates.UpdateUserStatus.status:type_name -> osmium.client.types.UserStatus
	6,  // 34: osmium.client.updates.UpdateUserStatusBatch.updates:type_name -> osmium.client.updates.UpdateUserStatus
	32, // 35: osmium.client.updates.UpdateUser.user:type_name -> osmium.client.types.User
	37, // 36: osmium.client.updates.UpdateCommunity.community:type_name -> osmium.client.types.Community
	35, // 37: osmium.client.updates.UpdateChatTyping.chat_ref:type_name -> osmium.client.refs.ChatRef
	38, // 38: osmium.client.updates.UpdateChatTyping.action:type_name -> osmium.client.chats.TypingAction
	39, // 39: osmium.client.updates.UpdateCommunityMember.member:type_name -> osmium.client.types.CommunityMember
	39, // 40: osmium.client.updates.UpdateCommunityMemberCreated.member:type_name -> osmium.client.types.CommunityMember
	32, // 41: osmium.client.updates.UpdateCommunityMemberCreated.user:type_name -> osmium.client.types.User
	35, // 42: osmium.client.updates.UpdateConversationPermissions.chat_ref:type_name -> osmium.client.refs.ChatRef
	40, // 43: osmium.client.updates.UpdateConversationPermissions.permissions:type_name -> osmium.client.types.PermissionOverrides
	41, // 44: osmium.client.updates.UpdateChat.chat:type_name -> osmium.client.chats.Chat
	20, // 45: osmium.client.updates.UpdateMemberList.entries:type_name -> osmium.client.updates.MemberListEntry
	21, // 46: osmium.client.updates.MemberListEntry.user:type_name -> osmium.client.updates.MemberListEntryUser
	22, // 47: osmium.client.updates.MemberListEntry.divider:type_name -> osmium.client.updates.MemberListEntryDivider
	32, // 48: osmium.client.updates.MemberListEntryUser.user:type_name -> osmium.client.types.User
	42, // 49: osmium.client.updates.UpdateUserRelationship.relationship:type_name -> osmium.client.types.Relationship
	43, // 50: osmium.client.updates.UpdateGroup.group:type_name -> osmium.client.types.Group
	32, // 51: osmium.client.updates.UpdateGroup.users:type_name -> osmium.client.types.User
	35, // 52: osmium.client.updates.UpdateMessageReactions.chat_ref:type_name -> osmium.client.refs.ChatRef
	44, // 53: osmium.client.updates.UpdateMessageReactions.reactions:type_name -> osmium.client.reactions.MessageReactions
	35, // 54: osmium.client.updates.UpdateConversationLastRead.chat_ref:type_name -> osmium.client.refs.ChatRef
	55, // [55:55] is the sub-list for method output_type
	55, // [55:55] is the sub-list for method input_type
	55, // [55:55] is the sub-list for extension type_name
	55, // [55:55] is the sub-list for extension extendee
	0,  // [0:55] is the sub-list for field type_name
}

func init() { file_updates_proto_init() }
func file_updates_proto_init() {
	if File_updates_proto != nil {
		return
	}
	file_updates_proto_msgTypes[0].OneofWrappers = []any{
		(*Update_MessageCreated)(nil),
		(*Update_Channel)(nil),
		(*Update_MessageDeleted)(nil),
		(*Update_UserStatus)(nil),
		(*Update_User)(nil),
		(*Update_Community)(nil),
		(*Update_ChannelDeleted)(nil),
		(*Update_Message)(nil),
		(*Update_ChatTyping)(nil),
		(*Update_CommunityMember)(nil),
		(*Update_CommunityDeleted)(nil),
		(*Update_ConversationPermissions)(nil),
		(*Update_Chat)(nil),
		(*Update_SessionDeleted)(nil),
		(*Update_CommunityUnavailable)(nil),
		(*Update_MemberList)(nil),
		(*Update_CommunityMemberDeleted)(nil),
		(*Update_UpdateUserRelationship)(nil),
		(*Update_UpdateUserRelationshipDeleted)(nil),
		(*Update_Group)(nil),
		(*Update_RoomState)(nil),
		(*Update_RoomParticipant)(nil),
		(*Update_MessageReactions)(nil),
		(*Update_ConversationLastRead)(nil),
		(*Update_CommunityMemberCreated)(nil),
		(*Update_Interaction)(nil),
		(*Update_UserStatusBatch)(nil),
	}
	file_updates_proto_msgTypes[1].OneofWrappers = []any{}
	file_updates_proto_msgTypes[11].OneofWrappers = []any{}
	file_updates_proto_msgTypes[14].OneofWrappers = []any{}
	file_updates_proto_msgTypes[19].OneofWrappers = []any{}
	file_updates_proto_msgTypes[20].OneofWrappers = []any{
		(*MemberListEntry_User)(nil),
		(*MemberListEntry_Divider)(nil),
	}
	file_updates_proto_msgTypes[21].OneofWrappers = []any{}
	file_updates_proto_msgTypes[22].OneofWrappers = []any{
		(*MemberListEntryDivider_Online)(nil),
		(*MemberListEntryDivider_RoleId)(nil),
	}
	file_updates_proto_msgTypes[27].OneofWrappers = []any{}
	file_updates_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_updates_proto_rawDesc), len(file_updates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_updates_proto_goTypes,
		DependencyIndexes: file_updates_proto_depIdxs,
		MessageInfos:      file_updates_proto_msgTypes,
	}.Build()
	File_updates_proto = out.File
	file_updates_proto_goTypes = nil
	file_updates_proto_depIdxs = nil
}
