// Code generated by tools/wrapgen; DO NOT EDIT.

package rpc

import (
	"fmt"
	auth "github.com/ofabiodev/osmose/proto/auth"
	billing "github.com/ofabiodev/osmose/proto/billing"
	chats "github.com/ofabiodev/osmose/proto/chats"
	communities "github.com/ofabiodev/osmose/proto/communities"
	core "github.com/ofabiodev/osmose/proto/core"
	discovery "github.com/ofabiodev/osmose/proto/discovery"
	friends "github.com/ofabiodev/osmose/proto/friends"
	media "github.com/ofabiodev/osmose/proto/media"
	messages "github.com/ofabiodev/osmose/proto/messages"
	oauth "github.com/ofabiodev/osmose/proto/oauth"
	reactions "github.com/ofabiodev/osmose/proto/reactions"
	settings "github.com/ofabiodev/osmose/proto/settings"
	stickers "github.com/ofabiodev/osmose/proto/stickers"
	users "github.com/ofabiodev/osmose/proto/users"
	voice "github.com/ofabiodev/osmose/proto/voice"
	"google.golang.org/protobuf/proto"
)

func wrap(id uint32, msg proto.Message) (*core.ClientMessage, error) {
	switch value := msg.(type) {
	case *auth.Authorize:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthAuthorize{AuthAuthorize: value}}, nil
	case *auth.CompleteSignIn:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthCompleteSignIn{AuthCompleteSignIn: value}}, nil
	case *auth.CreateEmailVerificationChallenge:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthCreateEmailVerificationChallenge{AuthCreateEmailVerificationChallenge: value}}, nil
	case *auth.GetSessions:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthGetSessions{AuthGetSessions: value}}, nil
	case *auth.LegacySignIn:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthLegacySignIn{AuthLegacySignIn: value}}, nil
	case *auth.LookupInvite:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthLookupInvite{AuthLookupInvite: value}}, nil
	case *auth.ResendEmailVerification:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthResendEmailVerification{AuthResendEmailVerification: value}}, nil
	case *auth.ResetPassword:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthResetPassword{AuthResetPassword: value}}, nil
	case *auth.RevokeSessions:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthRevokeSessions{AuthRevokeSessions: value}}, nil
	case *auth.SignIn:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthSignIn{AuthSignIn: value}}, nil
	case *auth.SignUp:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthSignUp{AuthSignUp: value}}, nil
	case *auth.UseInvite:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthUseInvite{AuthUseInvite: value}}, nil
	case *auth.VerifyEmail:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_AuthVerifyEmail{AuthVerifyEmail: value}}, nil
	case *billing.CancelSubscription:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_BillingCancelSubscription{BillingCancelSubscription: value}}, nil
	case *billing.ClaimGift:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_BillingClaimGift{BillingClaimGift: value}}, nil
	case *billing.CreateGiftLink:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_BillingCreateGiftLink{BillingCreateGiftLink: value}}, nil
	case *billing.GetInventory:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_BillingGetInventory{BillingGetInventory: value}}, nil
	case *billing.GetProducts:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_BillingGetProducts{BillingGetProducts: value}}, nil
	case *billing.GetSubscription:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_BillingGetSubscription{BillingGetSubscription: value}}, nil
	case *billing.PurchaseCredit:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_BillingPurchaseCredit{BillingPurchaseCredit: value}}, nil
	case *billing.RedeemInventoryItem:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_BillingRedeemInventoryItem{BillingRedeemInventoryItem: value}}, nil
	case *billing.RequestPaymentLink:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_BillingRequestPaymentLink{BillingRequestPaymentLink: value}}, nil
	case *billing.RevokeGiftLink:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_BillingRevokeGiftLink{BillingRevokeGiftLink: value}}, nil
	case *chats.AddChatMember:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsAddChatMember{ChatsAddChatMember: value}}, nil
	case *chats.CreateChat:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsCreateChat{ChatsCreateChat: value}}, nil
	case *chats.CreateChatInvite:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsCreateChatInvite{ChatsCreateChatInvite: value}}, nil
	case *chats.DeleteChatInvite:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsDeleteChatInvite{ChatsDeleteChatInvite: value}}, nil
	case *chats.EditChat:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsEditChat{ChatsEditChat: value}}, nil
	case *chats.EditChatMember:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsEditChatMember{ChatsEditChatMember: value}}, nil
	case *chats.GetChat:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsGetChat{ChatsGetChat: value}}, nil
	case *chats.GetChatMembers:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsGetChatMembers{ChatsGetChatMembers: value}}, nil
	case *chats.GetChats:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsGetChats{ChatsGetChats: value}}, nil
	case *chats.ListChatInvites:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsListChatInvites{ChatsListChatInvites: value}}, nil
	case *chats.MarkChatRead:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsMarkChatRead{ChatsMarkChatRead: value}}, nil
	case *chats.RemoveChatMember:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsRemoveChatMember{ChatsRemoveChatMember: value}}, nil
	case *chats.SetTyping:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ChatsSetTyping{ChatsSetTyping: value}}, nil
	case *communities.AddMember:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesAddMember{CommunitiesAddMember: value}}, nil
	case *communities.CreateChannel:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesCreateChannel{CommunitiesCreateChannel: value}}, nil
	case *communities.CreateChannelOverride:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesCreateChannelOverride{CommunitiesCreateChannelOverride: value}}, nil
	case *communities.CreateCommunity:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesCreateCommunity{CommunitiesCreateCommunity: value}}, nil
	case *communities.CreateRole:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesCreateRole{CommunitiesCreateRole: value}}, nil
	case *communities.DeleteChannel:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesDeleteChannel{CommunitiesDeleteChannel: value}}, nil
	case *communities.DeleteChannelOverride:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesDeleteChannelOverride{CommunitiesDeleteChannelOverride: value}}, nil
	case *communities.DeleteCommunity:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesDeleteCommunity{CommunitiesDeleteCommunity: value}}, nil
	case *communities.DeleteRole:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesDeleteRole{CommunitiesDeleteRole: value}}, nil
	case *communities.EditChannel:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesEditChannel{CommunitiesEditChannel: value}}, nil
	case *communities.EditCommunity:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesEditCommunity{CommunitiesEditCommunity: value}}, nil
	case *communities.EditDefaultPermissions:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesEditDefaultPermissions{CommunitiesEditDefaultPermissions: value}}, nil
	case *communities.EditMember:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesEditMember{CommunitiesEditMember: value}}, nil
	case *communities.EditPhoto:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesEditPhoto{CommunitiesEditPhoto: value}}, nil
	case *communities.EditRole:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesEditRole{CommunitiesEditRole: value}}, nil
	case *communities.EditSettings:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesEditSettings{CommunitiesEditSettings: value}}, nil
	case *communities.GetChannelMembers:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesGetChannelMembers{CommunitiesGetChannelMembers: value}}, nil
	case *communities.GetChannelOverrides:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesGetChannelOverrides{CommunitiesGetChannelOverrides: value}}, nil
	case *communities.GetChannels:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesGetChannels{CommunitiesGetChannels: value}}, nil
	case *communities.GetCommunities:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesGetCommunities{CommunitiesGetCommunities: value}}, nil
	case *communities.GetMembers:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesGetMembers{CommunitiesGetMembers: value}}, nil
	case *communities.GetRemovedMembers:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesGetRemovedMembers{CommunitiesGetRemovedMembers: value}}, nil
	case *communities.GetRoles:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesGetRoles{CommunitiesGetRoles: value}}, nil
	case *communities.GetRoomStates:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesGetRoomStates{CommunitiesGetRoomStates: value}}, nil
	case *communities.LeaveCommunity:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesLeaveCommunity{CommunitiesLeaveCommunity: value}}, nil
	case *communities.RemoveMembers:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesRemoveMembers{CommunitiesRemoveMembers: value}}, nil
	case *communities.SyncChannelOverrides:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesSyncChannelOverrides{CommunitiesSyncChannelOverrides: value}}, nil
	case *communities.UnbanMembers:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CommunitiesUnbanMembers{CommunitiesUnbanMembers: value}}, nil
	case *core.Initialize:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_CoreInitialize{CoreInitialize: value}}, nil
	case *discovery.GetDiscoverableCommunities:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_DiscoveryGetDiscoverableCommunities{DiscoveryGetDiscoverableCommunities: value}}, nil
	case *friends.ChangeRelationship:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_FriendsChangeRelationship{FriendsChangeRelationship: value}}, nil
	case *friends.GetRelationships:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_FriendsGetRelationships{FriendsGetRelationships: value}}, nil
	case *friends.SyncFriends:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_FriendsSyncFriends{FriendsSyncFriends: value}}, nil
	case *media.DownloadFilePart:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MediaDownloadFilePart{MediaDownloadFilePart: value}}, nil
	case *media.UploadFilePart:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MediaUploadFilePart{MediaUploadFilePart: value}}, nil
	case *messages.DeleteMessage:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesDeleteMessage{MessagesDeleteMessage: value}}, nil
	case *messages.EditMessage:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesEditMessage{MessagesEditMessage: value}}, nil
	case *messages.ForwardMessage:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesForwardMessage{MessagesForwardMessage: value}}, nil
	case *messages.GetEmbedPreview:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesGetEmbedPreview{MessagesGetEmbedPreview: value}}, nil
	case *messages.GetHistory:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesGetHistory{MessagesGetHistory: value}}, nil
	case *messages.GetPinnedMessages:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesGetPinnedMessages{MessagesGetPinnedMessages: value}}, nil
	case *messages.GetUnreadMentions:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesGetUnreadMentions{MessagesGetUnreadMentions: value}}, nil
	case *messages.ReportMessage:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesReportMessage{MessagesReportMessage: value}}, nil
	case *messages.Search:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesSearch{MessagesSearch: value}}, nil
	case *messages.SendMessage:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesSendMessage{MessagesSendMessage: value}}, nil
	case *messages.SetInteractionResponse:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesSetInteractionResponse{MessagesSetInteractionResponse: value}}, nil
	case *messages.SetMessagePin:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesSetMessagePin{MessagesSetMessagePin: value}}, nil
	case *messages.SubmitInteraction:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_MessagesSubmitInteraction{MessagesSubmitInteraction: value}}, nil
	case *oauth.Authorize:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_OauthAuthorize{OauthAuthorize: value}}, nil
	case *oauth.GetApp:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_OauthGetApp{OauthGetApp: value}}, nil
	case *reactions.AddReaction:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ReactionsAddReaction{ReactionsAddReaction: value}}, nil
	case *reactions.RemoveReaction:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_ReactionsRemoveReaction{ReactionsRemoveReaction: value}}, nil
	case *settings.BeginMfaStepUp:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsBeginMfaStepUp{SettingsBeginMfaStepUp: value}}, nil
	case *settings.ChangeEmail:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsChangeEmail{SettingsChangeEmail: value}}, nil
	case *settings.ChangeNotificationPreferences:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsChangeNotificationPreferences{SettingsChangeNotificationPreferences: value}}, nil
	case *settings.ChangePassword:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsChangePassword{SettingsChangePassword: value}}, nil
	case *settings.ChangeStatus:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsChangeStatus{SettingsChangeStatus: value}}, nil
	case *settings.CompleteMfaStepUp:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsCompleteMfaStepUp{SettingsCompleteMfaStepUp: value}}, nil
	case *settings.DeleteAccount:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsDeleteAccount{SettingsDeleteAccount: value}}, nil
	case *settings.EditProfile:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsEditProfile{SettingsEditProfile: value}}, nil
	case *settings.EditProfileBanner:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsEditProfileBanner{SettingsEditProfileBanner: value}}, nil
	case *settings.EditProfilePhoto:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsEditProfilePhoto{SettingsEditProfilePhoto: value}}, nil
	case *settings.EditUserSettings:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsEditUserSettings{SettingsEditUserSettings: value}}, nil
	case *settings.GetAccount:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsGetAccount{SettingsGetAccount: value}}, nil
	case *settings.GetMfaMethods:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsGetMfaMethods{SettingsGetMfaMethods: value}}, nil
	case *settings.GetRecoveryCodes:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsGetRecoveryCodes{SettingsGetRecoveryCodes: value}}, nil
	case *settings.RegenerateRecoveryCodes:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsRegenerateRecoveryCodes{SettingsRegenerateRecoveryCodes: value}}, nil
	case *settings.RegisterPushSubscription:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsRegisterPushSubscription{SettingsRegisterPushSubscription: value}}, nil
	case *settings.RequestTakeout:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsRequestTakeout{SettingsRequestTakeout: value}}, nil
	case *settings.SetupTotp:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsSetupTotp{SettingsSetupTotp: value}}, nil
	case *settings.SetupWebauthn:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsSetupWebauthn{SettingsSetupWebauthn: value}}, nil
	case *settings.UnregisterPushSubscription:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_SettingsUnregisterPushSubscription{SettingsUnregisterPushSubscription: value}}, nil
	case *stickers.AddStickerToPack:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_StickersAddStickerToPack{StickersAddStickerToPack: value}}, nil
	case *stickers.GetSavedStickers:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_StickersGetSavedStickers{StickersGetSavedStickers: value}}, nil
	case *stickers.GetStickerFiles:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_StickersGetStickerFiles{StickersGetStickerFiles: value}}, nil
	case *stickers.GetStickerPack:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_StickersGetStickerPack{StickersGetStickerPack: value}}, nil
	case *stickers.RemoveStickerFromPack:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_StickersRemoveStickerFromPack{StickersRemoveStickerFromPack: value}}, nil
	case *users.GetProfile:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_UsersGetProfile{UsersGetProfile: value}}, nil
	case *users.LookupUsername:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_UsersLookupUsername{UsersLookupUsername: value}}, nil
	case *voice.DisconnectUser:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_VoiceDisconnectUser{VoiceDisconnectUser: value}}, nil
	case *voice.GetRoomStates:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_VoiceGetRoomStates{VoiceGetRoomStates: value}}, nil
	case *voice.RequestRoom:
		return &core.ClientMessage{Id: id, Message: &core.ClientMessage_VoiceRequestRoom{VoiceRequestRoom: value}}, nil
	default:
		return nil, fmt.Errorf("%w: %T", ErrUnsupportedRequest, msg)
	}
}

// Wrap places a typed Osmium request inside the core ClientMessage oneof.
func Wrap(id uint32, msg proto.Message) (*core.ClientMessage, error) { return wrap(id, msg) }
