// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: chats.proto

package chats

import (
	media "github.com/ofabiodev/osmose/proto/media"
	refs "github.com/ofabiodev/osmose/proto/refs"
	types "github.com/ofabiodev/osmose/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypingAction int32

const (
	TypingAction_TYPING          TypingAction = 0
	TypingAction_UPLOAD_IMAGE    TypingAction = 1
	TypingAction_UPLOAD_VIDEO    TypingAction = 2
	TypingAction_UPLOAD_FILE     TypingAction = 3
	TypingAction_RECORDING_AUDIO TypingAction = 4
	TypingAction_RECORDING_VIDEO TypingAction = 5
)

// Enum value maps for TypingAction.
var (
	TypingAction_name = map[int32]string{
		0: "TYPING",
		1: "UPLOAD_IMAGE",
		2: "UPLOAD_VIDEO",
		3: "UPLOAD_FILE",
		4: "RECORDING_AUDIO",
		5: "RECORDING_VIDEO",
	}
	TypingAction_value = map[string]int32{
		"TYPING":          0,
		"UPLOAD_IMAGE":    1,
		"UPLOAD_VIDEO":    2,
		"UPLOAD_FILE":     3,
		"RECORDING_AUDIO": 4,
		"RECORDING_VIDEO": 5,
	}
)

func (x TypingAction) Enum() *TypingAction {
	p := new(TypingAction)
	*p = x
	return p
}

func (x TypingAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypingAction) Descriptor() protoreflect.EnumDescriptor {
	return file_chats_proto_enumTypes[0].Descriptor()
}

func (TypingAction) Type() protoreflect.EnumType {
	return &file_chats_proto_enumTypes[0]
}

func (x TypingAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypingAction.Descriptor instead.
func (TypingAction) EnumDescriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{0}
}

// chats.getChats -> chats.Chats
type GetChats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Limit *uint32                `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// @snowflake<Chat>
	MaxId *uint64 `protobuf:"fixed64,2,opt,name=max_id,json=maxId,proto3,oneof" json:"max_id,omitempty"`
	// @snowflake<Chat>
	MinId         *uint64 `protobuf:"fixed64,3,opt,name=min_id,json=minId,proto3,oneof" json:"min_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChats) Reset() {
	*x = GetChats{}
	mi := &file_chats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChats) ProtoMessage() {}

func (x *GetChats) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChats.ProtoReflect.Descriptor instead.
func (*GetChats) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{0}
}

func (x *GetChats) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetChats) GetMaxId() uint64 {
	if x != nil && x.MaxId != nil {
		return *x.MaxId
	}
	return 0
}

func (x *GetChats) GetMinId() uint64 {
	if x != nil && x.MinId != nil {
		return *x.MinId
	}
	return 0
}

type Chats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*types.Conversation  `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	Users         []*types.User          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Groups        []*types.Group         `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Channels      []*types.Channel       `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`
	Messages      []*types.Message       `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chats) Reset() {
	*x = Chats{}
	mi := &file_chats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chats) ProtoMessage() {}

func (x *Chats) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chats.ProtoReflect.Descriptor instead.
func (*Chats) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{1}
}

func (x *Chats) GetChats() []*types.Conversation {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *Chats) GetUsers() []*types.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Chats) GetGroups() []*types.Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Chats) GetChannels() []*types.Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *Chats) GetMessages() []*types.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// chats.getChat -> chats.Chat
type GetChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChat) Reset() {
	*x = GetChat{}
	mi := &file_chats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChat) ProtoMessage() {}

func (x *GetChat) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChat.ProtoReflect.Descriptor instead.
func (*GetChat) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{2}
}

func (x *GetChat) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *types.Conversation    `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	Message       *types.Message         `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Users         []*types.User          `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Group         *types.Group           `protobuf:"bytes,4,opt,name=group,proto3,oneof" json:"group,omitempty"`
	Channel       *types.Channel         `protobuf:"bytes,5,opt,name=channel,proto3,oneof" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_chats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{3}
}

func (x *Chat) GetChat() *types.Conversation {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *Chat) GetMessage() *types.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Chat) GetUsers() []*types.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Chat) GetGroup() *types.Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *Chat) GetChannel() *types.Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

// chats.getChatMembers -> chats.ChatMembers
type GetChatMembers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatMembers) Reset() {
	*x = GetChatMembers{}
	mi := &file_chats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMembers) ProtoMessage() {}

func (x *GetChatMembers) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMembers.ProtoReflect.Descriptor instead.
func (*GetChatMembers) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{4}
}

func (x *GetChatMembers) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

type ChatMembers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*types.ChatMember    `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Users         []*types.User          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMembers) Reset() {
	*x = ChatMembers{}
	mi := &file_chats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMembers) ProtoMessage() {}

func (x *ChatMembers) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMembers.ProtoReflect.Descriptor instead.
func (*ChatMembers) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{5}
}

func (x *ChatMembers) GetMembers() []*types.ChatMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ChatMembers) GetUsers() []*types.User {
	if x != nil {
		return x.Users
	}
	return nil
}

// chats.createChatInvite -> auth.CreatedInvite
type CreateChatInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	ExpiresAt     *uint64                `protobuf:"fixed64,2,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	MaxUses       *uint32                `protobuf:"varint,3,opt,name=max_uses,json=maxUses,proto3,oneof" json:"max_uses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatInvite) Reset() {
	*x = CreateChatInvite{}
	mi := &file_chats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatInvite) ProtoMessage() {}

func (x *CreateChatInvite) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatInvite.ProtoReflect.Descriptor instead.
func (*CreateChatInvite) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{6}
}

func (x *CreateChatInvite) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *CreateChatInvite) GetExpiresAt() uint64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *CreateChatInvite) GetMaxUses() uint32 {
	if x != nil && x.MaxUses != nil {
		return *x.MaxUses
	}
	return 0
}

// chats.listChatInvites -> auth.InviteList
type ListChatInvites struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatInvites) Reset() {
	*x = ListChatInvites{}
	mi := &file_chats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatInvites) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatInvites) ProtoMessage() {}

func (x *ListChatInvites) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatInvites.ProtoReflect.Descriptor instead.
func (*ListChatInvites) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{7}
}

func (x *ListChatInvites) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

// chats.deleteChatInvite -> ()
type DeleteChatInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatInvite) Reset() {
	*x = DeleteChatInvite{}
	mi := &file_chats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatInvite) ProtoMessage() {}

func (x *DeleteChatInvite) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatInvite.ProtoReflect.Descriptor instead.
func (*DeleteChatInvite) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteChatInvite) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// chats.markChatRead -> ()
type MarkChatRead struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<Message>
	MessageId     uint64  `protobuf:"fixed64,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReadAmount    *uint32 `protobuf:"varint,3,opt,name=read_amount,json=readAmount,proto3,oneof" json:"read_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkChatRead) Reset() {
	*x = MarkChatRead{}
	mi := &file_chats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkChatRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkChatRead) ProtoMessage() {}

func (x *MarkChatRead) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkChatRead.ProtoReflect.Descriptor instead.
func (*MarkChatRead) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{9}
}

func (x *MarkChatRead) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *MarkChatRead) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MarkChatRead) GetReadAmount() uint32 {
	if x != nil && x.ReadAmount != nil {
		return *x.ReadAmount
	}
	return 0
}

// chats.setTyping -> ()
type SetTyping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	Typing        bool                   `protobuf:"varint,2,opt,name=typing,proto3" json:"typing,omitempty"`
	Action        *TypingAction          `protobuf:"varint,3,opt,name=action,proto3,enum=osmium.client.chats.TypingAction,oneof" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTyping) Reset() {
	*x = SetTyping{}
	mi := &file_chats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTyping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTyping) ProtoMessage() {}

func (x *SetTyping) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTyping.ProtoReflect.Descriptor instead.
func (*SetTyping) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{10}
}

func (x *SetTyping) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *SetTyping) GetTyping() bool {
	if x != nil {
		return x.Typing
	}
	return false
}

func (x *SetTyping) GetAction() TypingAction {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return TypingAction_TYPING
}

// chats.createChat -> types.Group
type CreateChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*refs.UserRef        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChat) Reset() {
	*x = CreateChat{}
	mi := &file_chats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChat) ProtoMessage() {}

func (x *CreateChat) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChat.ProtoReflect.Descriptor instead.
func (*CreateChat) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{11}
}

func (x *CreateChat) GetUsers() []*refs.UserRef {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *CreateChat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// chats.editChat -> chats.Chat
type EditChat struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	Name    *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// None to not modify, 0 to modify to None, >0 to modify to Some(msg_id)
	HighlightedMsgId *EditChat_HighlightedMessage `protobuf:"bytes,3,opt,name=highlighted_msg_id,json=highlightedMsgId,proto3,oneof" json:"highlighted_msg_id,omitempty"`
	Photo            *EditChat_Photo              `protobuf:"bytes,4,opt,name=photo,proto3,oneof" json:"photo,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EditChat) Reset() {
	*x = EditChat{}
	mi := &file_chats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditChat) ProtoMessage() {}

func (x *EditChat) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditChat.ProtoReflect.Descriptor instead.
func (*EditChat) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{12}
}

func (x *EditChat) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *EditChat) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EditChat) GetHighlightedMsgId() *EditChat_HighlightedMessage {
	if x != nil {
		return x.HighlightedMsgId
	}
	return nil
}

func (x *EditChat) GetPhoto() *EditChat_Photo {
	if x != nil {
		return x.Photo
	}
	return nil
}

// chats.removeChatMember -> ()
type RemoveChatMember struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<User>
	UserId        uint64 `protobuf:"fixed64,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveChatMember) Reset() {
	*x = RemoveChatMember{}
	mi := &file_chats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveChatMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChatMember) ProtoMessage() {}

func (x *RemoveChatMember) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChatMember.ProtoReflect.Descriptor instead.
func (*RemoveChatMember) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveChatMember) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *RemoveChatMember) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// chats.addChatMember -> ()
type AddChatMember struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<User>
	UserId        uint64 `protobuf:"fixed64,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChatMember) Reset() {
	*x = AddChatMember{}
	mi := &file_chats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChatMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChatMember) ProtoMessage() {}

func (x *AddChatMember) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChatMember.ProtoReflect.Descriptor instead.
func (*AddChatMember) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{14}
}

func (x *AddChatMember) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *AddChatMember) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// chats.editChatMember -> ()
type EditChatMember struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<User>
	UserId        uint64 `protobuf:"fixed64,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permissions   uint64 `protobuf:"fixed64,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditChatMember) Reset() {
	*x = EditChatMember{}
	mi := &file_chats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditChatMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditChatMember) ProtoMessage() {}

func (x *EditChatMember) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditChatMember.ProtoReflect.Descriptor instead.
func (*EditChatMember) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{15}
}

func (x *EditChatMember) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *EditChatMember) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EditChatMember) GetPermissions() uint64 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

type EditChat_HighlightedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Message>
	HighlightedMsgId *uint64 `protobuf:"fixed64,1,opt,name=highlighted_msg_id,json=highlightedMsgId,proto3,oneof" json:"highlighted_msg_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EditChat_HighlightedMessage) Reset() {
	*x = EditChat_HighlightedMessage{}
	mi := &file_chats_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditChat_HighlightedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditChat_HighlightedMessage) ProtoMessage() {}

func (x *EditChat_HighlightedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditChat_HighlightedMessage.ProtoReflect.Descriptor instead.
func (*EditChat_HighlightedMessage) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{12, 0}
}

func (x *EditChat_HighlightedMessage) GetHighlightedMsgId() uint64 {
	if x != nil && x.HighlightedMsgId != nil {
		return *x.HighlightedMsgId
	}
	return 0
}

type EditChat_Photo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *media.UploadedFileRef `protobuf:"bytes,1,opt,name=file,proto3,oneof" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditChat_Photo) Reset() {
	*x = EditChat_Photo{}
	mi := &file_chats_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditChat_Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditChat_Photo) ProtoMessage() {}

func (x *EditChat_Photo) ProtoReflect() protoreflect.Message {
	mi := &file_chats_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditChat_Photo.ProtoReflect.Descriptor instead.
func (*EditChat_Photo) Descriptor() ([]byte, []int) {
	return file_chats_proto_rawDescGZIP(), []int{12, 1}
}

func (x *EditChat_Photo) GetFile() *media.UploadedFileRef {
	if x != nil {
		return x.File
	}
	return nil
}

var File_chats_proto protoreflect.FileDescriptor

const file_chats_proto_rawDesc = "" +
	"\n" +
	"\vchats.proto\x12\x13osmium.client.chats\x1a\vtypes.proto\x1a\n" +
	"refs.proto\x1a\vmedia.proto\"}\n" +
	"\bGetChats\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\rH\x00R\x05limit\x88\x01\x01\x12\x1a\n" +
	"\x06max_id\x18\x02 \x01(\x06H\x01R\x05maxId\x88\x01\x01\x12\x1a\n" +
	"\x06min_id\x18\x03 \x01(\x06H\x02R\x05minId\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_max_idB\t\n" +
	"\a_min_id\"\x99\x02\n" +
	"\x05Chats\x127\n" +
	"\x05chats\x18\x01 \x03(\v2!.osmium.client.types.ConversationR\x05chats\x12/\n" +
	"\x05users\x18\x02 \x03(\v2\x19.osmium.client.types.UserR\x05users\x122\n" +
	"\x06groups\x18\x03 \x03(\v2\x1a.osmium.client.types.GroupR\x06groups\x128\n" +
	"\bchannels\x18\x04 \x03(\v2\x1c.osmium.client.types.ChannelR\bchannels\x128\n" +
	"\bmessages\x18\x05 \x03(\v2\x1c.osmium.client.types.MessageR\bmessages\"A\n" +
	"\aGetChat\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\"\xc1\x02\n" +
	"\x04Chat\x125\n" +
	"\x04chat\x18\x01 \x01(\v2!.osmium.client.types.ConversationR\x04chat\x12;\n" +
	"\amessage\x18\x02 \x01(\v2\x1c.osmium.client.types.MessageH\x00R\amessage\x88\x01\x01\x12/\n" +
	"\x05users\x18\x03 \x03(\v2\x19.osmium.client.types.UserR\x05users\x125\n" +
	"\x05group\x18\x04 \x01(\v2\x1a.osmium.client.types.GroupH\x01R\x05group\x88\x01\x01\x12;\n" +
	"\achannel\x18\x05 \x01(\v2\x1c.osmium.client.types.ChannelH\x02R\achannel\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\b\n" +
	"\x06_groupB\n" +
	"\n" +
	"\b_channel\"H\n" +
	"\x0eGetChatMembers\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\"y\n" +
	"\vChatMembers\x129\n" +
	"\amembers\x18\x01 \x03(\v2\x1f.osmium.client.types.ChatMemberR\amembers\x12/\n" +
	"\x05users\x18\x02 \x03(\v2\x19.osmium.client.types.UserR\x05users\"\xaa\x01\n" +
	"\x10CreateChatInvite\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\"\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x06H\x00R\texpiresAt\x88\x01\x01\x12\x1e\n" +
	"\bmax_uses\x18\x03 \x01(\rH\x01R\amaxUses\x88\x01\x01B\r\n" +
	"\v_expires_atB\v\n" +
	"\t_max_uses\"I\n" +
	"\x0fListChatInvites\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\"&\n" +
	"\x10DeleteChatInvite\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x9b\x01\n" +
	"\fMarkChatRead\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x06R\tmessageId\x12$\n" +
	"\vread_amount\x18\x03 \x01(\rH\x00R\n" +
	"readAmount\x88\x01\x01B\x0e\n" +
	"\f_read_amount\"\xa6\x01\n" +
	"\tSetTyping\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x16\n" +
	"\x06typing\x18\x02 \x01(\bR\x06typing\x12>\n" +
	"\x06action\x18\x03 \x01(\x0e2!.osmium.client.chats.TypingActionH\x00R\x06action\x88\x01\x01B\t\n" +
	"\a_action\"S\n" +
	"\n" +
	"CreateChat\x121\n" +
	"\x05users\x18\x01 \x03(\v2\x1b.osmium.client.refs.UserRefR\x05users\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xdb\x03\n" +
	"\bEditChat\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12c\n" +
	"\x12highlighted_msg_id\x18\x03 \x01(\v20.osmium.client.chats.EditChat.HighlightedMessageH\x01R\x10highlightedMsgId\x88\x01\x01\x12>\n" +
	"\x05photo\x18\x04 \x01(\v2#.osmium.client.chats.EditChat.PhotoH\x02R\x05photo\x88\x01\x01\x1a^\n" +
	"\x12HighlightedMessage\x121\n" +
	"\x12highlighted_msg_id\x18\x01 \x01(\x06H\x00R\x10highlightedMsgId\x88\x01\x01B\x15\n" +
	"\x13_highlighted_msg_id\x1aO\n" +
	"\x05Photo\x12=\n" +
	"\x04file\x18\x01 \x01(\v2$.osmium.client.media.UploadedFileRefH\x00R\x04file\x88\x01\x01B\a\n" +
	"\x05_fileB\a\n" +
	"\x05_nameB\x15\n" +
	"\x13_highlighted_msg_idB\b\n" +
	"\x06_photo\"c\n" +
	"\x10RemoveChatMember\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x06R\x06userId\"`\n" +
	"\rAddChatMember\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x06R\x06userId\"\x83\x01\n" +
	"\x0eEditChatMember\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x06R\x06userId\x12 \n" +
	"\vpermissions\x18\x03 \x01(\x06R\vpermissions*y\n" +
	"\fTypingAction\x12\n" +
	"\n" +
	"\x06TYPING\x10\x00\x12\x10\n" +
	"\fUPLOAD_IMAGE\x10\x01\x12\x10\n" +
	"\fUPLOAD_VIDEO\x10\x02\x12\x0f\n" +
	"\vUPLOAD_FILE\x10\x03\x12\x13\n" +
	"\x0fRECORDING_AUDIO\x10\x04\x12\x13\n" +
	"\x0fRECORDING_VIDEO\x10\x05b\x06proto3"

var (
	file_chats_proto_rawDescOnce sync.Once
	file_chats_proto_rawDescData []byte
)

func file_chats_proto_rawDescGZIP() []byte {
	file_chats_proto_rawDescOnce.Do(func() {
		file_chats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chats_proto_rawDesc), len(file_chats_proto_rawDesc)))
	})
	return file_chats_proto_rawDescData
}

var file_chats_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chats_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_chats_proto_goTypes = []any{
	(TypingAction)(0),                   // 0: osmium.client.chats.TypingAction
	(*GetChats)(nil),                    // 1: osmium.client.chats.GetChats
	(*Chats)(nil),                       // 2: osmium.client.chats.Chats
	(*GetChat)(nil),                     // 3: osmium.client.chats.GetChat
	(*Chat)(nil),                        // 4: osmium.client.chats.Chat
	(*GetChatMembers)(nil),              // 5: osmium.client.chats.GetChatMembers
	(*ChatMembers)(nil),                 // 6: osmium.client.chats.ChatMembers
	(*CreateChatInvite)(nil),            // 7: osmium.client.chats.CreateChatInvite
	(*ListChatInvites)(nil),             // 8: osmium.client.chats.ListChatInvites
	(*DeleteChatInvite)(nil),            // 9: osmium.client.chats.DeleteChatInvite
	(*MarkChatRead)(nil),                // 10: osmium.client.chats.MarkChatRead
	(*SetTyping)(nil),                   // 11: osmium.client.chats.SetTyping
	(*CreateChat)(nil),                  // 12: osmium.client.chats.CreateChat
	(*EditChat)(nil),                    // 13: osmium.client.chats.EditChat
	(*RemoveChatMember)(nil),            // 14: osmium.client.chats.RemoveChatMember
	(*AddChatMember)(nil),               // 15: osmium.client.chats.AddChatMember
	(*EditChatMember)(nil),              // 16: osmium.client.chats.EditChatMember
	(*EditChat_HighlightedMessage)(nil), // 17: osmium.client.chats.EditChat.HighlightedMessage
	(*EditChat_Photo)(nil),              // 18: osmium.client.chats.EditChat.Photo
	(*types.Conversation)(nil),          // 19: osmium.client.types.Conversation
	(*types.User)(nil),                  // 20: osmium.client.types.User
	(*types.Group)(nil),                 // 21: osmium.client.types.Group
	(*types.Channel)(nil),               // 22: osmium.client.types.Channel
	(*types.Message)(nil),               // 23: osmium.client.types.Message
	(*refs.ChatRef)(nil),                // 24: osmium.client.refs.ChatRef
	(*types.ChatMember)(nil),            // 25: osmium.client.types.ChatMember
	(*refs.UserRef)(nil),                // 26: osmium.client.refs.UserRef
	(*media.UploadedFileRef)(nil),       // 27: osmium.client.media.UploadedFileRef
}
var file_chats_proto_depIdxs = []int32{
	19, // 0: osmium.client.chats.Chats.chats:type_name -> osmium.client.types.Conversation
	20, // 1: osmium.client.chats.Chats.users:type_name -> osmium.client.types.User
	21, // 2: osmium.client.chats.Chats.groups:type_name -> osmium.client.types.Group
	22, // 3: osmium.client.chats.Chats.channels:type_name -> osmium.client.types.Channel
	23, // 4: osmium.client.chats.Chats.messages:type_name -> osmium.client.types.Message
	24, // 5: osmium.client.chats.GetChat.chat_ref:type_name -> osmium.client.refs.ChatRef
	19, // 6: osmium.client.chats.Chat.chat:type_name -> osmium.client.types.Conversation
	23, // 7: osmium.client.chats.Chat.message:type_name -> osmium.client.types.Message
	20, // 8: osmium.client.chats.Chat.users:type_name -> osmium.client.types.User
	21, // 9: osmium.client.chats.Chat.group:type_name -> osmium.client.types.Group
	22, // 10: osmium.client.chats.Chat.channel:type_name -> osmium.client.types.Channel
	24, // 11: osmium.client.chats.GetChatMembers.chat_ref:type_name -> osmium.client.refs.ChatRef
	25, // 12: osmium.client.chats.ChatMembers.members:type_name -> osmium.client.types.ChatMember
	20, // 13: osmium.client.chats.ChatMembers.users:type_name -> osmium.client.types.User
	24, // 14: osmium.client.chats.CreateChatInvite.chat_ref:type_name -> osmium.client.refs.ChatRef
	24, // 15: osmium.client.chats.ListChatInvites.chat_ref:type_name -> osmium.client.refs.ChatRef
	24, // 16: osmium.client.chats.MarkChatRead.chat_ref:type_name -> osmium.client.refs.ChatRef
	24, // 17: osmium.client.chats.SetTyping.chat_ref:type_name -> osmium.client.refs.ChatRef
	0,  // 18: osmium.client.chats.SetTyping.action:type_name -> osmium.client.chats.TypingAction
	26, // 19: osmium.client.chats.CreateChat.users:type_name -> osmium.client.refs.UserRef
	24, // 20: osmium.client.chats.EditChat.chat_ref:type_name -> osmium.client.refs.ChatRef
	17, // 21: osmium.client.chats.EditChat.highlighted_msg_id:type_name -> osmium.client.chats.EditChat.HighlightedMessage
	18, // 22: osmium.client.chats.EditChat.photo:type_name -> osmium.client.chats.EditChat.Photo
	24, // 23: osmium.client.chats.RemoveChatMember.chat_ref:type_name -> osmium.client.refs.ChatRef
	24, // 24: osmium.client.chats.AddChatMember.chat_ref:type_name -> osmium.client.refs.ChatRef
	24, // 25: osmium.client.chats.EditChatMember.chat_ref:type_name -> osmium.client.refs.ChatRef
	27, // 26: osmium.client.chats.EditChat.Photo.file:type_name -> osmium.client.media.UploadedFileRef
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_chats_proto_init() }
func file_chats_proto_init() {
	if File_chats_proto != nil {
		return
	}
	file_chats_proto_msgTypes[0].OneofWrappers = []any{}
	file_chats_proto_msgTypes[3].OneofWrappers = []any{}
	file_chats_proto_msgTypes[6].OneofWrappers = []any{}
	file_chats_proto_msgTypes[9].OneofWrappers = []any{}
	file_chats_proto_msgTypes[10].OneofWrappers = []any{}
	file_chats_proto_msgTypes[12].OneofWrappers = []any{}
	file_chats_proto_msgTypes[16].OneofWrappers = []any{}
	file_chats_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chats_proto_rawDesc), len(file_chats_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chats_proto_goTypes,
		DependencyIndexes: file_chats_proto_depIdxs,
		EnumInfos:         file_chats_proto_enumTypes,
		MessageInfos:      file_chats_proto_msgTypes,
	}.Build()
	File_chats_proto = out.File
	file_chats_proto_goTypes = nil
	file_chats_proto_depIdxs = nil
}
