// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// source: messages.proto

package messages

import (
	media "github.com/ofabiodev/osmose/proto/media"
	reactions "github.com/ofabiodev/osmose/proto/reactions"
	refs "github.com/ofabiodev/osmose/proto/refs"
	types "github.com/ofabiodev/osmose/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// messages.sendMessage -> messages.SentMessage
type SendMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// @snowflake<Message>
	//
	// Deprecated: Marked as deprecated in messages.proto.
	ReplyToOld     *uint64                `protobuf:"fixed64,3,opt,name=reply_to_old,json=replyToOld,proto3,oneof" json:"reply_to_old,omitempty"`
	Media          []*media.MediaRef      `protobuf:"bytes,4,rep,name=media,proto3" json:"media,omitempty"`
	Entities       []*types.MessageEntity `protobuf:"bytes,5,rep,name=entities,proto3" json:"entities,omitempty"`
	SuppressEmbeds bool                   `protobuf:"varint,6,opt,name=suppress_embeds,json=suppressEmbeds,proto3" json:"suppress_embeds,omitempty"`
	ReplyTo        *SendMessage_ReplyTo   `protobuf:"bytes,7,opt,name=reply_to,json=replyTo,proto3,oneof" json:"reply_to,omitempty"`
	BotInfo        *SendMessage_BotInfo   `protobuf:"bytes,8,opt,name=bot_info,json=botInfo,proto3,oneof" json:"bot_info,omitempty"`
	ClientId       *uint64                `protobuf:"fixed64,9,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessage) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *SendMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Deprecated: Marked as deprecated in messages.proto.
func (x *SendMessage) GetReplyToOld() uint64 {
	if x != nil && x.ReplyToOld != nil {
		return *x.ReplyToOld
	}
	return 0
}

func (x *SendMessage) GetMedia() []*media.MediaRef {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *SendMessage) GetEntities() []*types.MessageEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SendMessage) GetSuppressEmbeds() bool {
	if x != nil {
		return x.SuppressEmbeds
	}
	return false
}

func (x *SendMessage) GetReplyTo() *SendMessage_ReplyTo {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *SendMessage) GetBotInfo() *SendMessage_BotInfo {
	if x != nil {
		return x.BotInfo
	}
	return nil
}

func (x *SendMessage) GetClientId() uint64 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

type MessageButton struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Label string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*MessageButton_Url
	//	*MessageButton_Interaction
	//	*MessageButton_Clipboard
	Action        isMessageButton_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageButton) Reset() {
	*x = MessageButton{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageButton) ProtoMessage() {}

func (x *MessageButton) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageButton.ProtoReflect.Descriptor instead.
func (*MessageButton) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MessageButton) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MessageButton) GetAction() isMessageButton_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *MessageButton) GetUrl() *MessageButton_MessageButtonUrl {
	if x != nil {
		if x, ok := x.Action.(*MessageButton_Url); ok {
			return x.Url
		}
	}
	return nil
}

func (x *MessageButton) GetInteraction() *MessageButton_MessageButtonInteraction {
	if x != nil {
		if x, ok := x.Action.(*MessageButton_Interaction); ok {
			return x.Interaction
		}
	}
	return nil
}

func (x *MessageButton) GetClipboard() *MessageButton_MessageButtonClipboard {
	if x != nil {
		if x, ok := x.Action.(*MessageButton_Clipboard); ok {
			return x.Clipboard
		}
	}
	return nil
}

type isMessageButton_Action interface {
	isMessageButton_Action()
}

type MessageButton_Url struct {
	Url *MessageButton_MessageButtonUrl `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

type MessageButton_Interaction struct {
	Interaction *MessageButton_MessageButtonInteraction `protobuf:"bytes,3,opt,name=interaction,proto3,oneof"`
}

type MessageButton_Clipboard struct {
	Clipboard *MessageButton_MessageButtonClipboard `protobuf:"bytes,4,opt,name=clipboard,proto3,oneof"`
}

func (*MessageButton_Url) isMessageButton_Action() {}

func (*MessageButton_Interaction) isMessageButton_Action() {}

func (*MessageButton_Clipboard) isMessageButton_Action() {}

type SentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Message>
	MessageId     uint64 `protobuf:"fixed64,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentMessage) Reset() {
	*x = SentMessage{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentMessage) ProtoMessage() {}

func (x *SentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentMessage.ProtoReflect.Descriptor instead.
func (*SentMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SentMessage) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// messages.submitInteraction -> messages.InteractionResponse
type SubmitInteraction struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<Message>
	MessageId     uint64  `protobuf:"fixed64,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Data          *string `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitInteraction) Reset() {
	*x = SubmitInteraction{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInteraction) ProtoMessage() {}

func (x *SubmitInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInteraction.ProtoReflect.Descriptor instead.
func (*SubmitInteraction) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitInteraction) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *SubmitInteraction) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SubmitInteraction) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

type InteractionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionResponse) Reset() {
	*x = InteractionResponse{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionResponse) ProtoMessage() {}

func (x *InteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionResponse.ProtoReflect.Descriptor instead.
func (*InteractionResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *InteractionResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// messages.editMessage -> ()
type EditMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<Message>
	MessageId   uint64  `protobuf:"fixed64,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message     *string `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	RemoveMedia bool    `protobuf:"varint,4,opt,name=remove_media,json=removeMedia,proto3" json:"remove_media,omitempty"`
	// Replaces media
	Media []*media.MediaRef `protobuf:"bytes,5,rep,name=media,proto3" json:"media,omitempty"`
	// Replaces entities if not empty or if message is set.
	Entities       []*types.MessageEntity       `protobuf:"bytes,6,rep,name=entities,proto3" json:"entities,omitempty"`
	SuppressEmbeds bool                         `protobuf:"varint,7,opt,name=suppress_embeds,json=suppressEmbeds,proto3" json:"suppress_embeds,omitempty"`
	Buttons        *SendMessage_BotInfo_Buttons `protobuf:"bytes,8,opt,name=buttons,proto3,oneof" json:"buttons,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EditMessage) Reset() {
	*x = EditMessage{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessage) ProtoMessage() {}

func (x *EditMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessage.ProtoReflect.Descriptor instead.
func (*EditMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *EditMessage) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *EditMessage) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *EditMessage) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *EditMessage) GetRemoveMedia() bool {
	if x != nil {
		return x.RemoveMedia
	}
	return false
}

func (x *EditMessage) GetMedia() []*media.MediaRef {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *EditMessage) GetEntities() []*types.MessageEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *EditMessage) GetSuppressEmbeds() bool {
	if x != nil {
		return x.SuppressEmbeds
	}
	return false
}

func (x *EditMessage) GetButtons() *SendMessage_BotInfo_Buttons {
	if x != nil {
		return x.Buttons
	}
	return nil
}

// messages.forwardMessage -> ()
type ForwardMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	From    *refs.ChatRef          `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// @snowflake<Message>
	MessageIds    []uint64 `protobuf:"fixed64,3,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardMessage) Reset() {
	*x = ForwardMessage{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMessage) ProtoMessage() {}

func (x *ForwardMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMessage.ProtoReflect.Descriptor instead.
func (*ForwardMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ForwardMessage) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *ForwardMessage) GetFrom() *refs.ChatRef {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ForwardMessage) GetMessageIds() []uint64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

// messages.deleteMessage -> ()
type DeleteMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<Message>
	MessageIds    []uint64 `protobuf:"fixed64,2,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessage) Reset() {
	*x = DeleteMessage{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessage) ProtoMessage() {}

func (x *DeleteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessage.ProtoReflect.Descriptor instead.
func (*DeleteMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMessage) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *DeleteMessage) GetMessageIds() []uint64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

// messages.getHistory -> messages.Messages
type GetHistory struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// Limit the number of messages to return. Defaults to 50, split when using
	// around.
	Limit *uint32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Types that are valid to be assigned to Offset:
	//
	//	*GetHistory_Since
	//	*GetHistory_Before
	//	*GetHistory_Around
	Offset        isGetHistory_Offset `protobuf_oneof:"offset"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistory) Reset() {
	*x = GetHistory{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistory) ProtoMessage() {}

func (x *GetHistory) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistory.ProtoReflect.Descriptor instead.
func (*GetHistory) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetHistory) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *GetHistory) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetHistory) GetOffset() isGetHistory_Offset {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *GetHistory) GetSince() uint64 {
	if x != nil {
		if x, ok := x.Offset.(*GetHistory_Since); ok {
			return x.Since
		}
	}
	return 0
}

func (x *GetHistory) GetBefore() uint64 {
	if x != nil {
		if x, ok := x.Offset.(*GetHistory_Before); ok {
			return x.Before
		}
	}
	return 0
}

func (x *GetHistory) GetAround() uint64 {
	if x != nil {
		if x, ok := x.Offset.(*GetHistory_Around); ok {
			return x.Around
		}
	}
	return 0
}

type isGetHistory_Offset interface {
	isGetHistory_Offset()
}

type GetHistory_Since struct {
	// @snowflake<Message>
	Since uint64 `protobuf:"fixed64,3,opt,name=since,proto3,oneof"`
}

type GetHistory_Before struct {
	// @snowflake<Message>
	Before uint64 `protobuf:"fixed64,4,opt,name=before,proto3,oneof"`
}

type GetHistory_Around struct {
	// @snowflake<Message>
	Around uint64 `protobuf:"fixed64,5,opt,name=around,proto3,oneof"`
}

func (*GetHistory_Since) isGetHistory_Offset() {}

func (*GetHistory_Before) isGetHistory_Offset() {}

func (*GetHistory_Around) isGetHistory_Offset() {}

type Messages struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Messages      []*types.Message              `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Users         []*types.User                 `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Members       []*types.CommunityMember      `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	Reactions     []*reactions.MessageReactions `protobuf:"bytes,4,rep,name=reactions,proto3" json:"reactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Messages) Reset() {
	*x = Messages{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messages) ProtoMessage() {}

func (x *Messages) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messages.ProtoReflect.Descriptor instead.
func (*Messages) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *Messages) GetMessages() []*types.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Messages) GetUsers() []*types.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Messages) GetMembers() []*types.CommunityMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Messages) GetReactions() []*reactions.MessageReactions {
	if x != nil {
		return x.Reactions
	}
	return nil
}

// messages.search -> messages.Messages
type Search struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	Query   string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Scoped  bool                   `protobuf:"varint,3,opt,name=scoped,proto3" json:"scoped,omitempty"` // A scoped query searches only the specific channel, rather than the entire parent. For global search, see messages.searchAll
	// Types that are valid to be assigned to Offset:
	//
	//	*Search_Since
	//	*Search_Before
	Offset        isSearch_Offset `protobuf_oneof:"offset"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search) Reset() {
	*x = Search{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *Search) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *Search) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Search) GetScoped() bool {
	if x != nil {
		return x.Scoped
	}
	return false
}

func (x *Search) GetOffset() isSearch_Offset {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *Search) GetSince() uint64 {
	if x != nil {
		if x, ok := x.Offset.(*Search_Since); ok {
			return x.Since
		}
	}
	return 0
}

func (x *Search) GetBefore() uint64 {
	if x != nil {
		if x, ok := x.Offset.(*Search_Before); ok {
			return x.Before
		}
	}
	return 0
}

type isSearch_Offset interface {
	isSearch_Offset()
}

type Search_Since struct {
	// @snowflake<Message>
	Since uint64 `protobuf:"fixed64,4,opt,name=since,proto3,oneof"`
}

type Search_Before struct {
	// @snowflake<Message>
	Before uint64 `protobuf:"fixed64,5,opt,name=before,proto3,oneof"`
}

func (*Search_Since) isSearch_Offset() {}

func (*Search_Before) isSearch_Offset() {}

// messages.getEmbedPreview -> media.MediaEmbed
type GetEmbedPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Entities      []*types.MessageEntity `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbedPreview) Reset() {
	*x = GetEmbedPreview{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbedPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbedPreview) ProtoMessage() {}

func (x *GetEmbedPreview) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbedPreview.ProtoReflect.Descriptor instead.
func (*GetEmbedPreview) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *GetEmbedPreview) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEmbedPreview) GetEntities() []*types.MessageEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

// messages.reportMessage -> ()
type ReportMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Message>
	MessageId     uint64        `protobuf:"fixed64,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatRef       *refs.ChatRef `protobuf:"bytes,2,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	Reason        string        `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMessage) Reset() {
	*x = ReportMessage{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMessage) ProtoMessage() {}

func (x *ReportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMessage.ProtoReflect.Descriptor instead.
func (*ReportMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ReportMessage) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReportMessage) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *ReportMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// messages.getUnreadMentions -> messages.UnreadMentions
type GetUnreadMentions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadMentions) Reset() {
	*x = GetUnreadMentions{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadMentions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadMentions) ProtoMessage() {}

func (x *GetUnreadMentions) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadMentions.ProtoReflect.Descriptor instead.
func (*GetUnreadMentions) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GetUnreadMentions) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

type UnreadMentions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Message>
	MessageIds    []uint64 `protobuf:"fixed64,1,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadMentions) Reset() {
	*x = UnreadMentions{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadMentions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadMentions) ProtoMessage() {}

func (x *UnreadMentions) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadMentions.ProtoReflect.Descriptor instead.
func (*UnreadMentions) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *UnreadMentions) GetMessageIds() []uint64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

// messages.setMessagePin -> ()
type SetMessagePin struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<Message>
	MessageId     uint64 `protobuf:"fixed64,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Pin           bool   `protobuf:"varint,3,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMessagePin) Reset() {
	*x = SetMessagePin{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMessagePin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMessagePin) ProtoMessage() {}

func (x *SetMessagePin) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMessagePin.ProtoReflect.Descriptor instead.
func (*SetMessagePin) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *SetMessagePin) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *SetMessagePin) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SetMessagePin) GetPin() bool {
	if x != nil {
		return x.Pin
	}
	return false
}

// messages.getPinnedMessages -> messages.Messages
type GetPinnedMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRef       *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPinnedMessages) Reset() {
	*x = GetPinnedMessages{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPinnedMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPinnedMessages) ProtoMessage() {}

func (x *GetPinnedMessages) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPinnedMessages.ProtoReflect.Descriptor instead.
func (*GetPinnedMessages) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *GetPinnedMessages) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

// messages.setInteractionResponse -> ()
type SetInteractionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Interaction>
	InteractionId uint64  `protobuf:"fixed64,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInteractionResponse) Reset() {
	*x = SetInteractionResponse{}
	mi := &file_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInteractionResponse) ProtoMessage() {}

func (x *SetInteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInteractionResponse.ProtoReflect.Descriptor instead.
func (*SetInteractionResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *SetInteractionResponse) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *SetInteractionResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type SendMessage_ReplyTo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Message>
	MessageId     uint64                     `protobuf:"fixed64,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Quote         *SendMessage_ReplyTo_Quote `protobuf:"bytes,2,opt,name=quote,proto3,oneof" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage_ReplyTo) Reset() {
	*x = SendMessage_ReplyTo{}
	mi := &file_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage_ReplyTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage_ReplyTo) ProtoMessage() {}

func (x *SendMessage_ReplyTo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage_ReplyTo.ProtoReflect.Descriptor instead.
func (*SendMessage_ReplyTo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SendMessage_ReplyTo) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SendMessage_ReplyTo) GetQuote() *SendMessage_ReplyTo_Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

type SendMessage_BotInfo struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Cloak         *SendMessage_BotInfo_MessageCloak `protobuf:"bytes,1,opt,name=cloak,proto3,oneof" json:"cloak,omitempty"`
	Buttons       *SendMessage_BotInfo_Buttons      `protobuf:"bytes,2,opt,name=buttons,proto3,oneof" json:"buttons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage_BotInfo) Reset() {
	*x = SendMessage_BotInfo{}
	mi := &file_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage_BotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage_BotInfo) ProtoMessage() {}

func (x *SendMessage_BotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage_BotInfo.ProtoReflect.Descriptor instead.
func (*SendMessage_BotInfo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SendMessage_BotInfo) GetCloak() *SendMessage_BotInfo_MessageCloak {
	if x != nil {
		return x.Cloak
	}
	return nil
}

func (x *SendMessage_BotInfo) GetButtons() *SendMessage_BotInfo_Buttons {
	if x != nil {
		return x.Buttons
	}
	return nil
}

type SendMessage_ReplyTo_Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Entities      []*types.MessageEntity `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	Offset        *uint64                `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage_ReplyTo_Quote) Reset() {
	*x = SendMessage_ReplyTo_Quote{}
	mi := &file_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage_ReplyTo_Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage_ReplyTo_Quote) ProtoMessage() {}

func (x *SendMessage_ReplyTo_Quote) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage_ReplyTo_Quote.ProtoReflect.Descriptor instead.
func (*SendMessage_ReplyTo_Quote) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *SendMessage_ReplyTo_Quote) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessage_ReplyTo_Quote) GetEntities() []*types.MessageEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SendMessage_ReplyTo_Quote) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type SendMessage_BotInfo_MessageCloak struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// @snowflake<File>
	PhotoId       *uint64 `protobuf:"fixed64,2,opt,name=photo_id,json=photoId,proto3,oneof" json:"photo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage_BotInfo_MessageCloak) Reset() {
	*x = SendMessage_BotInfo_MessageCloak{}
	mi := &file_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage_BotInfo_MessageCloak) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage_BotInfo_MessageCloak) ProtoMessage() {}

func (x *SendMessage_BotInfo_MessageCloak) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage_BotInfo_MessageCloak.ProtoReflect.Descriptor instead.
func (*SendMessage_BotInfo_MessageCloak) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *SendMessage_BotInfo_MessageCloak) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendMessage_BotInfo_MessageCloak) GetPhotoId() uint64 {
	if x != nil && x.PhotoId != nil {
		return *x.PhotoId
	}
	return 0
}

type SendMessage_BotInfo_Buttons struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Rows          []*SendMessage_BotInfo_Buttons_ButtonRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"` // max of 5 rows, max of 5 per row
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage_BotInfo_Buttons) Reset() {
	*x = SendMessage_BotInfo_Buttons{}
	mi := &file_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage_BotInfo_Buttons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage_BotInfo_Buttons) ProtoMessage() {}

func (x *SendMessage_BotInfo_Buttons) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage_BotInfo_Buttons.ProtoReflect.Descriptor instead.
func (*SendMessage_BotInfo_Buttons) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *SendMessage_BotInfo_Buttons) GetRows() []*SendMessage_BotInfo_Buttons_ButtonRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type SendMessage_BotInfo_Buttons_ButtonRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buttons       []*MessageButton       `protobuf:"bytes,1,rep,name=buttons,proto3" json:"buttons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage_BotInfo_Buttons_ButtonRow) Reset() {
	*x = SendMessage_BotInfo_Buttons_ButtonRow{}
	mi := &file_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage_BotInfo_Buttons_ButtonRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage_BotInfo_Buttons_ButtonRow) ProtoMessage() {}

func (x *SendMessage_BotInfo_Buttons_ButtonRow) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage_BotInfo_Buttons_ButtonRow.ProtoReflect.Descriptor instead.
func (*SendMessage_BotInfo_Buttons_ButtonRow) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0, 1, 1, 0}
}

func (x *SendMessage_BotInfo_Buttons_ButtonRow) GetButtons() []*MessageButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

type MessageButton_MessageButtonUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageButton_MessageButtonUrl) Reset() {
	*x = MessageButton_MessageButtonUrl{}
	mi := &file_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageButton_MessageButtonUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageButton_MessageButtonUrl) ProtoMessage() {}

func (x *MessageButton_MessageButtonUrl) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageButton_MessageButtonUrl.ProtoReflect.Descriptor instead.
func (*MessageButton_MessageButtonUrl) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MessageButton_MessageButtonUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MessageButton_MessageButtonInteraction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageButton_MessageButtonInteraction) Reset() {
	*x = MessageButton_MessageButtonInteraction{}
	mi := &file_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageButton_MessageButtonInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageButton_MessageButtonInteraction) ProtoMessage() {}

func (x *MessageButton_MessageButtonInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageButton_MessageButtonInteraction.ProtoReflect.Descriptor instead.
func (*MessageButton_MessageButtonInteraction) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1, 1}
}

func (x *MessageButton_MessageButtonInteraction) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type MessageButton_MessageButtonClipboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageButton_MessageButtonClipboard) Reset() {
	*x = MessageButton_MessageButtonClipboard{}
	mi := &file_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageButton_MessageButtonClipboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageButton_MessageButtonClipboard) ProtoMessage() {}

func (x *MessageButton_MessageButtonClipboard) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageButton_MessageButtonClipboard.ProtoReflect.Descriptor instead.
func (*MessageButton_MessageButtonClipboard) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1, 2}
}

func (x *MessageButton_MessageButtonClipboard) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x16osmium.client.messages\x1a\vtypes.proto\x1a\n" +
	"refs.proto\x1a\vmedia.proto\x1a\x0freactions.proto\"\xf5\t\n" +
	"\vSendMessage\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\freply_to_old\x18\x03 \x01(\x06B\x02\x18\x01H\x00R\n" +
	"replyToOld\x88\x01\x01\x123\n" +
	"\x05media\x18\x04 \x03(\v2\x1d.osmium.client.media.MediaRefR\x05media\x12>\n" +
	"\bentities\x18\x05 \x03(\v2\".osmium.client.types.MessageEntityR\bentities\x12'\n" +
	"\x0fsuppress_embeds\x18\x06 \x01(\bR\x0esuppressEmbeds\x12K\n" +
	"\breply_to\x18\a \x01(\v2+.osmium.client.messages.SendMessage.ReplyToH\x01R\areplyTo\x88\x01\x01\x12K\n" +
	"\bbot_info\x18\b \x01(\v2+.osmium.client.messages.SendMessage.BotInfoH\x02R\abotInfo\x88\x01\x01\x12 \n" +
	"\tclient_id\x18\t \x01(\x06H\x03R\bclientId\x88\x01\x01\x1a\x8c\x02\n" +
	"\aReplyTo\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x06R\tmessageId\x12L\n" +
	"\x05quote\x18\x02 \x01(\v21.osmium.client.messages.SendMessage.ReplyTo.QuoteH\x00R\x05quote\x88\x01\x01\x1a\x89\x01\n" +
	"\x05Quote\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12>\n" +
	"\bentities\x18\x02 \x03(\v2\".osmium.client.types.MessageEntityR\bentities\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x04H\x00R\x06offset\x88\x01\x01B\t\n" +
	"\a_offsetB\b\n" +
	"\x06_quote\x1a\xc6\x03\n" +
	"\aBotInfo\x12S\n" +
	"\x05cloak\x18\x01 \x01(\v28.osmium.client.messages.SendMessage.BotInfo.MessageCloakH\x00R\x05cloak\x88\x01\x01\x12R\n" +
	"\abuttons\x18\x02 \x01(\v23.osmium.client.messages.SendMessage.BotInfo.ButtonsH\x01R\abuttons\x88\x01\x01\x1aO\n" +
	"\fMessageCloak\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\bphoto_id\x18\x02 \x01(\x06H\x00R\aphotoId\x88\x01\x01B\v\n" +
	"\t_photo_id\x1a\xaa\x01\n" +
	"\aButtons\x12Q\n" +
	"\x04rows\x18\x01 \x03(\v2=.osmium.client.messages.SendMessage.BotInfo.Buttons.ButtonRowR\x04rows\x1aL\n" +
	"\tButtonRow\x12?\n" +
	"\abuttons\x18\x01 \x03(\v2%.osmium.client.messages.MessageButtonR\abuttonsB\b\n" +
	"\x06_cloakB\n" +
	"\n" +
	"\b_buttonsB\x0f\n" +
	"\r_reply_to_oldB\v\n" +
	"\t_reply_toB\v\n" +
	"\t_bot_infoB\f\n" +
	"\n" +
	"_client_id\"\xc1\x03\n" +
	"\rMessageButton\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12J\n" +
	"\x03url\x18\x02 \x01(\v26.osmium.client.messages.MessageButton.MessageButtonUrlH\x00R\x03url\x12b\n" +
	"\vinteraction\x18\x03 \x01(\v2>.osmium.client.messages.MessageButton.MessageButtonInteractionH\x00R\vinteraction\x12\\\n" +
	"\tclipboard\x18\x04 \x01(\v2<.osmium.client.messages.MessageButton.MessageButtonClipboardH\x00R\tclipboard\x1a$\n" +
	"\x10MessageButtonUrl\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x1a.\n" +
	"\x18MessageButtonInteraction\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x1a,\n" +
	"\x16MessageButtonClipboard\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04textB\b\n" +
	"\x06action\",\n" +
	"\vSentMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x06R\tmessageId\"\x8c\x01\n" +
	"\x11SubmitInteraction\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x06R\tmessageId\x12\x17\n" +
	"\x04data\x18\x03 \x01(\tH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\"@\n" +
	"\x13InteractionResponse\x12\x1d\n" +
	"\amessage\x18\x01 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\xb0\x03\n" +
	"\vEditMessage\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x06R\tmessageId\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01\x12!\n" +
	"\fremove_media\x18\x04 \x01(\bR\vremoveMedia\x123\n" +
	"\x05media\x18\x05 \x03(\v2\x1d.osmium.client.media.MediaRefR\x05media\x12>\n" +
	"\bentities\x18\x06 \x03(\v2\".osmium.client.types.MessageEntityR\bentities\x12'\n" +
	"\x0fsuppress_embeds\x18\a \x01(\bR\x0esuppressEmbeds\x12R\n" +
	"\abuttons\x18\b \x01(\v23.osmium.client.messages.SendMessage.BotInfo.ButtonsH\x01R\abuttons\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\n" +
	"\n" +
	"\b_buttons\"\x9a\x01\n" +
	"\x0eForwardMessage\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12/\n" +
	"\x04from\x18\x02 \x01(\v2\x1b.osmium.client.refs.ChatRefR\x04from\x12\x1f\n" +
	"\vmessage_ids\x18\x03 \x03(\x06R\n" +
	"messageIds\"h\n" +
	"\rDeleteMessage\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\x06R\n" +
	"messageIds\"\xbf\x01\n" +
	"\n" +
	"GetHistory\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\rH\x01R\x05limit\x88\x01\x01\x12\x16\n" +
	"\x05since\x18\x03 \x01(\x06H\x00R\x05since\x12\x18\n" +
	"\x06before\x18\x04 \x01(\x06H\x00R\x06before\x12\x18\n" +
	"\x06around\x18\x05 \x01(\x06H\x00R\x06aroundB\b\n" +
	"\x06offsetB\b\n" +
	"\x06_limit\"\xfe\x01\n" +
	"\bMessages\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.osmium.client.types.MessageR\bmessages\x12/\n" +
	"\x05users\x18\x02 \x03(\v2\x19.osmium.client.types.UserR\x05users\x12>\n" +
	"\amembers\x18\x03 \x03(\v2$.osmium.client.types.CommunityMemberR\amembers\x12G\n" +
	"\treactions\x18\x04 \x03(\v2).osmium.client.reactions.MessageReactionsR\treactions\"\xaa\x01\n" +
	"\x06Search\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x16\n" +
	"\x06scoped\x18\x03 \x01(\bR\x06scoped\x12\x16\n" +
	"\x05since\x18\x04 \x01(\x06H\x00R\x05since\x12\x18\n" +
	"\x06before\x18\x05 \x01(\x06H\x00R\x06beforeB\b\n" +
	"\x06offset\"k\n" +
	"\x0fGetEmbedPreview\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12>\n" +
	"\bentities\x18\x02 \x03(\v2\".osmium.client.types.MessageEntityR\bentities\"~\n" +
	"\rReportMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x06R\tmessageId\x126\n" +
	"\bchat_ref\x18\x02 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"K\n" +
	"\x11GetUnreadMentions\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\"1\n" +
	"\x0eUnreadMentions\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\x06R\n" +
	"messageIds\"x\n" +
	"\rSetMessagePin\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x06R\tmessageId\x12\x10\n" +
	"\x03pin\x18\x03 \x01(\bR\x03pin\"K\n" +
	"\x11GetPinnedMessages\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\"j\n" +
	"\x16SetInteractionResponse\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x06R\rinteractionId\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_messageb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_messages_proto_goTypes = []any{
	(*SendMessage)(nil),                            // 0: osmium.client.messages.SendMessage
	(*MessageButton)(nil),                          // 1: osmium.client.messages.MessageButton
	(*SentMessage)(nil),                            // 2: osmium.client.messages.SentMessage
	(*SubmitInteraction)(nil),                      // 3: osmium.client.messages.SubmitInteraction
	(*InteractionResponse)(nil),                    // 4: osmium.client.messages.InteractionResponse
	(*EditMessage)(nil),                            // 5: osmium.client.messages.EditMessage
	(*ForwardMessage)(nil),                         // 6: osmium.client.messages.ForwardMessage
	(*DeleteMessage)(nil),                          // 7: osmium.client.messages.DeleteMessage
	(*GetHistory)(nil),                             // 8: osmium.client.messages.GetHistory
	(*Messages)(nil),                               // 9: osmium.client.messages.Messages
	(*Search)(nil),                                 // 10: osmium.client.messages.Search
	(*GetEmbedPreview)(nil),                        // 11: osmium.client.messages.GetEmbedPreview
	(*ReportMessage)(nil),                          // 12: osmium.client.messages.ReportMessage
	(*GetUnreadMentions)(nil),                      // 13: osmium.client.messages.GetUnreadMentions
	(*UnreadMentions)(nil),                         // 14: osmium.client.messages.UnreadMentions
	(*SetMessagePin)(nil),                          // 15: osmium.client.messages.SetMessagePin
	(*GetPinnedMessages)(nil),                      // 16: osmium.client.messages.GetPinnedMessages
	(*SetInteractionResponse)(nil),                 // 17: osmium.client.messages.SetInteractionResponse
	(*SendMessage_ReplyTo)(nil),                    // 18: osmium.client.messages.SendMessage.ReplyTo
	(*SendMessage_BotInfo)(nil),                    // 19: osmium.client.messages.SendMessage.BotInfo
	(*SendMessage_ReplyTo_Quote)(nil),              // 20: osmium.client.messages.SendMessage.ReplyTo.Quote
	(*SendMessage_BotInfo_MessageCloak)(nil),       // 21: osmium.client.messages.SendMessage.BotInfo.MessageCloak
	(*SendMessage_BotInfo_Buttons)(nil),            // 22: osmium.client.messages.SendMessage.BotInfo.Buttons
	(*SendMessage_BotInfo_Buttons_ButtonRow)(nil),  // 23: osmium.client.messages.SendMessage.BotInfo.Buttons.ButtonRow
	(*MessageButton_MessageButtonUrl)(nil),         // 24: osmium.client.messages.MessageButton.MessageButtonUrl
	(*MessageButton_MessageButtonInteraction)(nil), // 25: osmium.client.messages.MessageButton.MessageButtonInteraction
	(*MessageButton_MessageButtonClipboard)(nil),   // 26: osmium.client.messages.MessageButton.MessageButtonClipboard
	(*refs.ChatRef)(nil),                           // 27: osmium.client.refs.ChatRef
	(*media.MediaRef)(nil),                         // 28: osmium.client.media.MediaRef
	(*types.MessageEntity)(nil),                    // 29: osmium.client.types.MessageEntity
	(*types.Message)(nil),                          // 30: osmium.client.types.Message
	(*types.User)(nil),                             // 31: osmium.client.types.User
	(*types.CommunityMember)(nil),                  // 32: osmium.client.types.CommunityMember
	(*reactions.MessageReactions)(nil),             // 33: osmium.client.reactions.MessageReactions
}
var file_messages_proto_depIdxs = []int32{
	27, // 0: osmium.client.messages.SendMessage.chat_ref:type_name -> osmium.client.refs.ChatRef
	28, // 1: osmium.client.messages.SendMessage.media:type_name -> osmium.client.media.MediaRef
	29, // 2: osmium.client.messages.SendMessage.entities:type_name -> osmium.client.types.MessageEntity
	18, // 3: osmium.client.messages.SendMessage.reply_to:type_name -> osmium.client.messages.SendMessage.ReplyTo
	19, // 4: osmium.client.messages.SendMessage.bot_info:type_name -> osmium.client.messages.SendMessage.BotInfo
	24, // 5: osmium.client.messages.MessageButton.url:type_name -> osmium.client.messages.MessageButton.MessageButtonUrl
	25, // 6: osmium.client.messages.MessageButton.interaction:type_name -> osmium.client.messages.MessageButton.MessageButtonInteraction
	26, // 7: osmium.client.messages.MessageButton.clipboard:type_name -> osmium.client.messages.MessageButton.MessageButtonClipboard
	27, // 8: osmium.client.messages.SubmitInteraction.chat_ref:type_name -> osmium.client.refs.ChatRef
	27, // 9: osmium.client.messages.EditMessage.chat_ref:type_name -> osmium.client.refs.ChatRef
	28, // 10: osmium.client.messages.EditMessage.media:type_name -> osmium.client.media.MediaRef
	29, // 11: osmium.client.messages.EditMessage.entities:type_name -> osmium.client.types.MessageEntity
	22, // 12: osmium.client.messages.EditMessage.buttons:type_name -> osmium.client.messages.SendMessage.BotInfo.Buttons
	27, // 13: osmium.client.messages.ForwardMessage.chat_ref:type_name -> osmium.client.refs.ChatRef
	27, // 14: osmium.client.messages.ForwardMessage.from:type_name -> osmium.client.refs.ChatRef
	27, // 15: osmium.client.messages.DeleteMessage.chat_ref:type_name -> osmium.client.refs.ChatRef
	27, // 16: osmium.client.messages.GetHistory.chat_ref:type_name -> osmium.client.refs.ChatRef
	30, // 17: osmium.client.messages.Messages.messages:type_name -> osmium.client.types.Message
	31, // 18: osmium.client.messages.Messages.users:type_name -> osmium.client.types.User
	32, // 19: osmium.client.messages.Messages.members:type_name -> osmium.client.types.CommunityMember
	33, // 20: osmium.client.messages.Messages.reactions:type_name -> osmium.client.reactions.MessageReactions
	27, // 21: osmium.client.messages.Search.chat_ref:type_name -> osmium.client.refs.ChatRef
	29, // 22: osmium.client.messages.GetEmbedPreview.entities:type_name -> osmium.client.types.MessageEntity
	27, // 23: osmium.client.messages.ReportMessage.chat_ref:type_name -> osmium.client.refs.ChatRef
	27, // 24: osmium.client.messages.GetUnreadMentions.chat_ref:type_name -> osmium.client.refs.ChatRef
	27, // 25: osmium.client.messages.SetMessagePin.chat_ref:type_name -> osmium.client.refs.ChatRef
	27, // 26: osmium.client.messages.GetPinnedMessages.chat_ref:type_name -> osmium.client.refs.ChatRef
	20, // 27: osmium.client.messages.SendMessage.ReplyTo.quote:type_name -> osmium.client.messages.SendMessage.ReplyTo.Quote
	21, // 28: osmium.client.messages.SendMessage.BotInfo.cloak:type_name -> osmium.client.messages.SendMessage.BotInfo.MessageCloak
	22, // 29: osmium.client.messages.SendMessage.BotInfo.buttons:type_name -> osmium.client.messages.SendMessage.BotInfo.Buttons
	29, // 30: osmium.client.messages.SendMessage.ReplyTo.Quote.entities:type_name -> osmium.client.types.MessageEntity
	23, // 31: osmium.client.messages.SendMessage.BotInfo.Buttons.rows:type_name -> osmium.client.messages.SendMessage.BotInfo.Buttons.ButtonRow
	1,  // 32: osmium.client.messages.SendMessage.BotInfo.Buttons.ButtonRow.buttons:type_name -> osmium.client.messages.MessageButton
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[0].OneofWrappers = []any{}
	file_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*MessageButton_Url)(nil),
		(*MessageButton_Interaction)(nil),
		(*MessageButton_Clipboard)(nil),
	}
	file_messages_proto_msgTypes[3].OneofWrappers = []any{}
	file_messages_proto_msgTypes[4].OneofWrappers = []any{}
	file_messages_proto_msgTypes[5].OneofWrappers = []any{}
	file_messages_proto_msgTypes[8].OneofWrappers = []any{
		(*GetHistory_Since)(nil),
		(*GetHistory_Before)(nil),
		(*GetHistory_Around)(nil),
	}
	file_messages_proto_msgTypes[10].OneofWrappers = []any{
		(*Search_Since)(nil),
		(*Search_Before)(nil),
	}
	file_messages_proto_msgTypes[17].OneofWrappers = []any{}
	file_messages_proto_msgTypes[18].OneofWrappers = []any{}
	file_messages_proto_msgTypes[19].OneofWrappers = []any{}
	file_messages_proto_msgTypes[20].OneofWrappers = []any{}
	file_messages_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
