// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: oauth.proto

package oauth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// oauth.authorize -> oauth.Authorization
type Authorize struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResponseType        string                 `protobuf:"bytes,1,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	ClientId            uint32                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RedirectUri         string                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Scope               *string                `protobuf:"bytes,4,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	State               *string                `protobuf:"bytes,5,opt,name=state,proto3,oneof" json:"state,omitempty"`
	CodeChallenge       *string                `protobuf:"bytes,6,opt,name=code_challenge,json=codeChallenge,proto3,oneof" json:"code_challenge,omitempty"`
	CodeChallengeMethod *string                `protobuf:"bytes,7,opt,name=code_challenge_method,json=codeChallengeMethod,proto3,oneof" json:"code_challenge_method,omitempty"`
	Nonce               *string                `protobuf:"bytes,8,opt,name=nonce,proto3,oneof" json:"nonce,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Authorize) Reset() {
	*x = Authorize{}
	mi := &file_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorize) ProtoMessage() {}

func (x *Authorize) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorize.ProtoReflect.Descriptor instead.
func (*Authorize) Descriptor() ([]byte, []int) {
	return file_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *Authorize) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *Authorize) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Authorize) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *Authorize) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *Authorize) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Authorize) GetCodeChallenge() string {
	if x != nil && x.CodeChallenge != nil {
		return *x.CodeChallenge
	}
	return ""
}

func (x *Authorize) GetCodeChallengeMethod() string {
	if x != nil && x.CodeChallengeMethod != nil {
		return *x.CodeChallengeMethod
	}
	return ""
}

func (x *Authorize) GetNonce() string {
	if x != nil && x.Nonce != nil {
		return *x.Nonce
	}
	return ""
}

// oauth.getApp -> oauth.App
type GetApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApp) Reset() {
	*x = GetApp{}
	mi := &file_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApp) ProtoMessage() {}

func (x *GetApp) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApp.ProtoReflect.Descriptor instead.
func (*GetApp) Descriptor() ([]byte, []int) {
	return file_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *GetApp) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type Authorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUri   string                 `protobuf:"bytes,1,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	State         *string                `protobuf:"bytes,3,opt,name=state,proto3,oneof" json:"state,omitempty"`
	ExpiresAt     uint64                 `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorization) Reset() {
	*x = Authorization{}
	mi := &file_oauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorization) ProtoMessage() {}

func (x *Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorization.ProtoReflect.Descriptor instead.
func (*Authorization) Descriptor() ([]byte, []int) {
	return file_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *Authorization) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *Authorization) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Authorization) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Authorization) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flags         uint64                 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	RedirectUris  []string               `protobuf:"bytes,4,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_oauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_oauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *App) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetFlags() uint64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *App) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

var File_oauth_proto protoreflect.FileDescriptor

const file_oauth_proto_rawDesc = "" +
	"\n" +
	"\voauth.proto\x12\x13osmium.client.oauth\"\xf1\x02\n" +
	"\tAuthorize\x12#\n" +
	"\rresponse_type\x18\x01 \x01(\tR\fresponseType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\rR\bclientId\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\x12\x19\n" +
	"\x05scope\x18\x04 \x01(\tH\x00R\x05scope\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x05 \x01(\tH\x01R\x05state\x88\x01\x01\x12*\n" +
	"\x0ecode_challenge\x18\x06 \x01(\tH\x02R\rcodeChallenge\x88\x01\x01\x127\n" +
	"\x15code_challenge_method\x18\a \x01(\tH\x03R\x13codeChallengeMethod\x88\x01\x01\x12\x19\n" +
	"\x05nonce\x18\b \x01(\tH\x04R\x05nonce\x88\x01\x01B\b\n" +
	"\x06_scopeB\b\n" +
	"\x06_stateB\x11\n" +
	"\x0f_code_challengeB\x18\n" +
	"\x16_code_challenge_methodB\b\n" +
	"\x06_nonce\"%\n" +
	"\x06GetApp\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\"\x8a\x01\n" +
	"\rAuthorization\x12!\n" +
	"\fredirect_uri\x18\x01 \x01(\tR\vredirectUri\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x19\n" +
	"\x05state\x18\x03 \x01(\tH\x00R\x05state\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x04R\texpiresAtB\b\n" +
	"\x06_state\"q\n" +
	"\x03App\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\x04R\x05flags\x12#\n" +
	"\rredirect_uris\x18\x04 \x03(\tR\fredirectUrisb\x06proto3"

var (
	file_oauth_proto_rawDescOnce sync.Once
	file_oauth_proto_rawDescData []byte
)

func file_oauth_proto_rawDescGZIP() []byte {
	file_oauth_proto_rawDescOnce.Do(func() {
		file_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oauth_proto_rawDesc), len(file_oauth_proto_rawDesc)))
	})
	return file_oauth_proto_rawDescData
}

var file_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_oauth_proto_goTypes = []any{
	(*Authorize)(nil),     // 0: osmium.client.oauth.Authorize
	(*GetApp)(nil),        // 1: osmium.client.oauth.GetApp
	(*Authorization)(nil), // 2: osmium.client.oauth.Authorization
	(*App)(nil),           // 3: osmium.client.oauth.App
}
var file_oauth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oauth_proto_init() }
func file_oauth_proto_init() {
	if File_oauth_proto != nil {
		return
	}
	file_oauth_proto_msgTypes[0].OneofWrappers = []any{}
	file_oauth_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oauth_proto_rawDesc), len(file_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oauth_proto_goTypes,
		DependencyIndexes: file_oauth_proto_depIdxs,
		MessageInfos:      file_oauth_proto_msgTypes,
	}.Build()
	File_oauth_proto = out.File
	file_oauth_proto_goTypes = nil
	file_oauth_proto_depIdxs = nil
}
