// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: stickers.proto

package stickers

import (
	media "github.com/ofabiodev/osmose/proto/media"
	refs "github.com/ofabiodev/osmose/proto/refs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StickerPack_Type int32

const (
	StickerPack_UNKNOWN StickerPack_Type = 0
	StickerPack_STICKER StickerPack_Type = 1
	StickerPack_EMOJI   StickerPack_Type = 2
)

// Enum value maps for StickerPack_Type.
var (
	StickerPack_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "STICKER",
		2: "EMOJI",
	}
	StickerPack_Type_value = map[string]int32{
		"UNKNOWN": 0,
		"STICKER": 1,
		"EMOJI":   2,
	}
)

func (x StickerPack_Type) Enum() *StickerPack_Type {
	p := new(StickerPack_Type)
	*p = x
	return p
}

func (x StickerPack_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StickerPack_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_stickers_proto_enumTypes[0].Descriptor()
}

func (StickerPack_Type) Type() protoreflect.EnumType {
	return &file_stickers_proto_enumTypes[0]
}

func (x StickerPack_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StickerPack_Type.Descriptor instead.
func (StickerPack_Type) EnumDescriptor() ([]byte, []int) {
	return file_stickers_proto_rawDescGZIP(), []int{2, 0}
}

// media.getSavedStickers -> media.SavedStickers
type GetSavedStickers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *uint64                `protobuf:"fixed64,1,opt,name=since,proto3,oneof" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavedStickers) Reset() {
	*x = GetSavedStickers{}
	mi := &file_stickers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavedStickers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedStickers) ProtoMessage() {}

func (x *GetSavedStickers) ProtoReflect() protoreflect.Message {
	mi := &file_stickers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedStickers.ProtoReflect.Descriptor instead.
func (*GetSavedStickers) Descriptor() ([]byte, []int) {
	return file_stickers_proto_rawDescGZIP(), []int{0}
}

func (x *GetSavedStickers) GetSince() uint64 {
	if x != nil && x.Since != nil {
		return *x.Since
	}
	return 0
}

type SavedStickers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavedPacks    []*StickerPack         `protobuf:"bytes,1,rep,name=saved_packs,json=savedPacks,proto3" json:"saved_packs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavedStickers) Reset() {
	*x = SavedStickers{}
	mi := &file_stickers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedStickers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedStickers) ProtoMessage() {}

func (x *SavedStickers) ProtoReflect() protoreflect.Message {
	mi := &file_stickers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedStickers.ProtoReflect.Descriptor instead.
func (*SavedStickers) Descriptor() ([]byte, []int) {
	return file_stickers_proto_rawDescGZIP(), []int{1}
}

func (x *SavedStickers) GetSavedPacks() []*StickerPack {
	if x != nil {
		return x.SavedPacks
	}
	return nil
}

type StickerPack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<StickerPack>
	Id            uint64           `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          StickerPack_Type `protobuf:"varint,2,opt,name=type,proto3,enum=osmium.client.stickers.StickerPack_Type" json:"type,omitempty"`
	Name          string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Stickers      []*media.File    `protobuf:"bytes,4,rep,name=stickers,proto3" json:"stickers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerPack) Reset() {
	*x = StickerPack{}
	mi := &file_stickers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerPack) ProtoMessage() {}

func (x *StickerPack) ProtoReflect() protoreflect.Message {
	mi := &file_stickers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerPack.ProtoReflect.Descriptor instead.
func (*StickerPack) Descriptor() ([]byte, []int) {
	return file_stickers_proto_rawDescGZIP(), []int{2}
}

func (x *StickerPack) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StickerPack) GetType() StickerPack_Type {
	if x != nil {
		return x.Type
	}
	return StickerPack_UNKNOWN
}

func (x *StickerPack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StickerPack) GetStickers() []*media.File {
	if x != nil {
		return x.Stickers
	}
	return nil
}

// stickers.getStickerFiles -> media.Files
type GetStickerFiles struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Sticker>
	StickerIds    []uint64 `protobuf:"fixed64,1,rep,packed,name=sticker_ids,json=stickerIds,proto3" json:"sticker_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStickerFiles) Reset() {
	*x = GetStickerFiles{}
	mi := &file_stickers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStickerFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStickerFiles) ProtoMessage() {}

func (x *GetStickerFiles) ProtoReflect() protoreflect.Message {
	mi := &file_stickers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStickerFiles.ProtoReflect.Descriptor instead.
func (*GetStickerFiles) Descriptor() ([]byte, []int) {
	return file_stickers_proto_rawDescGZIP(), []int{3}
}

func (x *GetStickerFiles) GetStickerIds() []uint64 {
	if x != nil {
		return x.StickerIds
	}
	return nil
}

// stickers.getStickerPack -> stickers.StickerPack
type GetStickerPack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pack          *refs.StickerPackRef   `protobuf:"bytes,1,opt,name=pack,proto3" json:"pack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStickerPack) Reset() {
	*x = GetStickerPack{}
	mi := &file_stickers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStickerPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStickerPack) ProtoMessage() {}

func (x *GetStickerPack) ProtoReflect() protoreflect.Message {
	mi := &file_stickers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStickerPack.ProtoReflect.Descriptor instead.
func (*GetStickerPack) Descriptor() ([]byte, []int) {
	return file_stickers_proto_rawDescGZIP(), []int{4}
}

func (x *GetStickerPack) GetPack() *refs.StickerPackRef {
	if x != nil {
		return x.Pack
	}
	return nil
}

// stickers.addStickerToPack -> ()
type AddStickerToPack struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Pack          *refs.StickerPackRef        `protobuf:"bytes,1,opt,name=pack,proto3" json:"pack,omitempty"`
	Sticker       *media.MediaRefUploadedFile `protobuf:"bytes,2,opt,name=sticker,proto3" json:"sticker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStickerToPack) Reset() {
	*x = AddStickerToPack{}
	mi := &file_stickers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStickerToPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStickerToPack) ProtoMessage() {}

func (x *AddStickerToPack) ProtoReflect() protoreflect.Message {
	mi := &file_stickers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStickerToPack.ProtoReflect.Descriptor instead.
func (*AddStickerToPack) Descriptor() ([]byte, []int) {
	return file_stickers_proto_rawDescGZIP(), []int{5}
}

func (x *AddStickerToPack) GetPack() *refs.StickerPackRef {
	if x != nil {
		return x.Pack
	}
	return nil
}

func (x *AddStickerToPack) GetSticker() *media.MediaRefUploadedFile {
	if x != nil {
		return x.Sticker
	}
	return nil
}

// stickers.removeStickerFromPack -> ()
type RemoveStickerFromPack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pack  *refs.StickerPackRef   `protobuf:"bytes,1,opt,name=pack,proto3" json:"pack,omitempty"`
	// @snowflake<Sticker>
	StickerId     uint64 `protobuf:"fixed64,2,opt,name=sticker_id,json=stickerId,proto3" json:"sticker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStickerFromPack) Reset() {
	*x = RemoveStickerFromPack{}
	mi := &file_stickers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStickerFromPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStickerFromPack) ProtoMessage() {}

func (x *RemoveStickerFromPack) ProtoReflect() protoreflect.Message {
	mi := &file_stickers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStickerFromPack.ProtoReflect.Descriptor instead.
func (*RemoveStickerFromPack) Descriptor() ([]byte, []int) {
	return file_stickers_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveStickerFromPack) GetPack() *refs.StickerPackRef {
	if x != nil {
		return x.Pack
	}
	return nil
}

func (x *RemoveStickerFromPack) GetStickerId() uint64 {
	if x != nil {
		return x.StickerId
	}
	return 0
}

var File_stickers_proto protoreflect.FileDescriptor

const file_stickers_proto_rawDesc = "" +
	"\n" +
	"\x0estickers.proto\x12\x16osmium.client.stickers\x1a\vmedia.proto\x1a\n" +
	"refs.proto\"7\n" +
	"\x10GetSavedStickers\x12\x19\n" +
	"\x05since\x18\x01 \x01(\x06H\x00R\x05since\x88\x01\x01B\b\n" +
	"\x06_since\"U\n" +
	"\rSavedStickers\x12D\n" +
	"\vsaved_packs\x18\x01 \x03(\v2#.osmium.client.stickers.StickerPackR\n" +
	"savedPacks\"\xd3\x01\n" +
	"\vStickerPack\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x06R\x02id\x12<\n" +
	"\x04type\x18\x02 \x01(\x0e2(.osmium.client.stickers.StickerPack.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x125\n" +
	"\bstickers\x18\x04 \x03(\v2\x19.osmium.client.media.FileR\bstickers\"+\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSTICKER\x10\x01\x12\t\n" +
	"\x05EMOJI\x10\x02\"2\n" +
	"\x0fGetStickerFiles\x12\x1f\n" +
	"\vsticker_ids\x18\x01 \x03(\x06R\n" +
	"stickerIds\"H\n" +
	"\x0eGetStickerPack\x126\n" +
	"\x04pack\x18\x01 \x01(\v2\".osmium.client.refs.StickerPackRefR\x04pack\"\x8f\x01\n" +
	"\x10AddStickerToPack\x126\n" +
	"\x04pack\x18\x01 \x01(\v2\".osmium.client.refs.StickerPackRefR\x04pack\x12C\n" +
	"\asticker\x18\x02 \x01(\v2).osmium.client.media.MediaRefUploadedFileR\asticker\"n\n" +
	"\x15RemoveStickerFromPack\x126\n" +
	"\x04pack\x18\x01 \x01(\v2\".osmium.client.refs.StickerPackRefR\x04pack\x12\x1d\n" +
	"\n" +
	"sticker_id\x18\x02 \x01(\x06R\tstickerIdb\x06proto3"

var (
	file_stickers_proto_rawDescOnce sync.Once
	file_stickers_proto_rawDescData []byte
)

func file_stickers_proto_rawDescGZIP() []byte {
	file_stickers_proto_rawDescOnce.Do(func() {
		file_stickers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stickers_proto_rawDesc), len(file_stickers_proto_rawDesc)))
	})
	return file_stickers_proto_rawDescData
}

var file_stickers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stickers_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stickers_proto_goTypes = []any{
	(StickerPack_Type)(0),              // 0: osmium.client.stickers.StickerPack.Type
	(*GetSavedStickers)(nil),           // 1: osmium.client.stickers.GetSavedStickers
	(*SavedStickers)(nil),              // 2: osmium.client.stickers.SavedStickers
	(*StickerPack)(nil),                // 3: osmium.client.stickers.StickerPack
	(*GetStickerFiles)(nil),            // 4: osmium.client.stickers.GetStickerFiles
	(*GetStickerPack)(nil),             // 5: osmium.client.stickers.GetStickerPack
	(*AddStickerToPack)(nil),           // 6: osmium.client.stickers.AddStickerToPack
	(*RemoveStickerFromPack)(nil),      // 7: osmium.client.stickers.RemoveStickerFromPack
	(*media.File)(nil),                 // 8: osmium.client.media.File
	(*refs.StickerPackRef)(nil),        // 9: osmium.client.refs.StickerPackRef
	(*media.MediaRefUploadedFile)(nil), // 10: osmium.client.media.MediaRefUploadedFile
}
var file_stickers_proto_depIdxs = []int32{
	3,  // 0: osmium.client.stickers.SavedStickers.saved_packs:type_name -> osmium.client.stickers.StickerPack
	0,  // 1: osmium.client.stickers.StickerPack.type:type_name -> osmium.client.stickers.StickerPack.Type
	8,  // 2: osmium.client.stickers.StickerPack.stickers:type_name -> osmium.client.media.File
	9,  // 3: osmium.client.stickers.GetStickerPack.pack:type_name -> osmium.client.refs.StickerPackRef
	9,  // 4: osmium.client.stickers.AddStickerToPack.pack:type_name -> osmium.client.refs.StickerPackRef
	10, // 5: osmium.client.stickers.AddStickerToPack.sticker:type_name -> osmium.client.media.MediaRefUploadedFile
	9,  // 6: osmium.client.stickers.RemoveStickerFromPack.pack:type_name -> osmium.client.refs.StickerPackRef
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_stickers_proto_init() }
func file_stickers_proto_init() {
	if File_stickers_proto != nil {
		return
	}
	file_stickers_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stickers_proto_rawDesc), len(file_stickers_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stickers_proto_goTypes,
		DependencyIndexes: file_stickers_proto_depIdxs,
		EnumInfos:         file_stickers_proto_enumTypes,
		MessageInfos:      file_stickers_proto_msgTypes,
	}.Build()
	File_stickers_proto = out.File
	file_stickers_proto_goTypes = nil
	file_stickers_proto_depIdxs = nil
}
