// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// source: refs.proto

package refs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO: This is only meant to be used for input. Current use is ambiguous.
type ChatRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ref:
	//
	//	*ChatRef_User
	//	*ChatRef_Channel
	//	*ChatRef_Group
	//	*ChatRef_Self
	Ref           isChatRef_Ref `protobuf_oneof:"ref"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRef) Reset() {
	*x = ChatRef{}
	mi := &file_refs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRef) ProtoMessage() {}

func (x *ChatRef) ProtoReflect() protoreflect.Message {
	mi := &file_refs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRef.ProtoReflect.Descriptor instead.
func (*ChatRef) Descriptor() ([]byte, []int) {
	return file_refs_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRef) GetRef() isChatRef_Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ChatRef) GetUser() *UserRef {
	if x != nil {
		if x, ok := x.Ref.(*ChatRef_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *ChatRef) GetChannel() *ChannelRef {
	if x != nil {
		if x, ok := x.Ref.(*ChatRef_Channel); ok {
			return x.Channel
		}
	}
	return nil
}

func (x *ChatRef) GetGroup() *GroupRef {
	if x != nil {
		if x, ok := x.Ref.(*ChatRef_Group); ok {
			return x.Group
		}
	}
	return nil
}

func (x *ChatRef) GetSelf() *RefSelf {
	if x != nil {
		if x, ok := x.Ref.(*ChatRef_Self); ok {
			return x.Self
		}
	}
	return nil
}

type isChatRef_Ref interface {
	isChatRef_Ref()
}

type ChatRef_User struct {
	User *UserRef `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

type ChatRef_Channel struct {
	Channel *ChannelRef `protobuf:"bytes,2,opt,name=channel,proto3,oneof"`
}

type ChatRef_Group struct {
	Group *GroupRef `protobuf:"bytes,3,opt,name=group,proto3,oneof"`
}

type ChatRef_Self struct {
	Self *RefSelf `protobuf:"bytes,4,opt,name=self,proto3,oneof"`
}

func (*ChatRef_User) isChatRef_Ref() {}

func (*ChatRef_Channel) isChatRef_Ref() {}

func (*ChatRef_Group) isChatRef_Ref() {}

func (*ChatRef_Self) isChatRef_Ref() {}

type UserRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<User>
	UserId        uint64 `protobuf:"fixed64,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRef) Reset() {
	*x = UserRef{}
	mi := &file_refs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRef) ProtoMessage() {}

func (x *UserRef) ProtoReflect() protoreflect.Message {
	mi := &file_refs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRef.ProtoReflect.Descriptor instead.
func (*UserRef) Descriptor() ([]byte, []int) {
	return file_refs_proto_rawDescGZIP(), []int{1}
}

func (x *UserRef) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RefSelf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefSelf) Reset() {
	*x = RefSelf{}
	mi := &file_refs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefSelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefSelf) ProtoMessage() {}

func (x *RefSelf) ProtoReflect() protoreflect.Message {
	mi := &file_refs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefSelf.ProtoReflect.Descriptor instead.
func (*RefSelf) Descriptor() ([]byte, []int) {
	return file_refs_proto_rawDescGZIP(), []int{2}
}

type ChannelRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Community>
	CommunityId uint64 `protobuf:"fixed64,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	// @snowflake<Channel>
	ChannelId     uint64 `protobuf:"fixed64,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRef) Reset() {
	*x = ChannelRef{}
	mi := &file_refs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRef) ProtoMessage() {}

func (x *ChannelRef) ProtoReflect() protoreflect.Message {
	mi := &file_refs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRef.ProtoReflect.Descriptor instead.
func (*ChannelRef) Descriptor() ([]byte, []int) {
	return file_refs_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelRef) GetCommunityId() uint64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *ChannelRef) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type GroupRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Chat>
	GroupId       uint64 `protobuf:"fixed64,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRef) Reset() {
	*x = GroupRef{}
	mi := &file_refs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRef) ProtoMessage() {}

func (x *GroupRef) ProtoReflect() protoreflect.Message {
	mi := &file_refs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRef.ProtoReflect.Descriptor instead.
func (*GroupRef) Descriptor() ([]byte, []int) {
	return file_refs_proto_rawDescGZIP(), []int{4}
}

func (x *GroupRef) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type StickerPackRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<StickerPack>
	Id            uint64 `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"` // TODO auth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerPackRef) Reset() {
	*x = StickerPackRef{}
	mi := &file_refs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerPackRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerPackRef) ProtoMessage() {}

func (x *StickerPackRef) ProtoReflect() protoreflect.Message {
	mi := &file_refs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerPackRef.ProtoReflect.Descriptor instead.
func (*StickerPackRef) Descriptor() ([]byte, []int) {
	return file_refs_proto_rawDescGZIP(), []int{5}
}

func (x *StickerPackRef) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_refs_proto protoreflect.FileDescriptor

const file_refs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"refs.proto\x12\x12osmium.client.refs\"\xe8\x01\n" +
	"\aChatRef\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.osmium.client.refs.UserRefH\x00R\x04user\x12:\n" +
	"\achannel\x18\x02 \x01(\v2\x1e.osmium.client.refs.ChannelRefH\x00R\achannel\x124\n" +
	"\x05group\x18\x03 \x01(\v2\x1c.osmium.client.refs.GroupRefH\x00R\x05group\x121\n" +
	"\x04self\x18\x04 \x01(\v2\x1b.osmium.client.refs.RefSelfH\x00R\x04selfB\x05\n" +
	"\x03ref\"\"\n" +
	"\aUserRef\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x06R\x06userId\"\t\n" +
	"\aRefSelf\"N\n" +
	"\n" +
	"ChannelRef\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\x06R\vcommunityId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\x06R\tchannelId\"%\n" +
	"\bGroupRef\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x06R\agroupId\" \n" +
	"\x0eStickerPackRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x06R\x02idb\x06proto3"

var (
	file_refs_proto_rawDescOnce sync.Once
	file_refs_proto_rawDescData []byte
)

func file_refs_proto_rawDescGZIP() []byte {
	file_refs_proto_rawDescOnce.Do(func() {
		file_refs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_refs_proto_rawDesc), len(file_refs_proto_rawDesc)))
	})
	return file_refs_proto_rawDescData
}

var file_refs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_refs_proto_goTypes = []any{
	(*ChatRef)(nil),        // 0: osmium.client.refs.ChatRef
	(*UserRef)(nil),        // 1: osmium.client.refs.UserRef
	(*RefSelf)(nil),        // 2: osmium.client.refs.RefSelf
	(*ChannelRef)(nil),     // 3: osmium.client.refs.ChannelRef
	(*GroupRef)(nil),       // 4: osmium.client.refs.GroupRef
	(*StickerPackRef)(nil), // 5: osmium.client.refs.StickerPackRef
}
var file_refs_proto_depIdxs = []int32{
	1, // 0: osmium.client.refs.ChatRef.user:type_name -> osmium.client.refs.UserRef
	3, // 1: osmium.client.refs.ChatRef.channel:type_name -> osmium.client.refs.ChannelRef
	4, // 2: osmium.client.refs.ChatRef.group:type_name -> osmium.client.refs.GroupRef
	2, // 3: osmium.client.refs.ChatRef.self:type_name -> osmium.client.refs.RefSelf
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_refs_proto_init() }
func file_refs_proto_init() {
	if File_refs_proto != nil {
		return
	}
	file_refs_proto_msgTypes[0].OneofWrappers = []any{
		(*ChatRef_User)(nil),
		(*ChatRef_Channel)(nil),
		(*ChatRef_Group)(nil),
		(*ChatRef_Self)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_refs_proto_rawDesc), len(file_refs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_refs_proto_goTypes,
		DependencyIndexes: file_refs_proto_depIdxs,
		MessageInfos:      file_refs_proto_msgTypes,
	}.Build()
	File_refs_proto = out.File
	file_refs_proto_goTypes = nil
	file_refs_proto_depIdxs = nil
}
