// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// source: reactions.proto

package reactions

import (
	refs "github.com/ofabiodev/osmose/proto/refs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddReaction struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<Message>
	MessageId     uint64         `protobuf:"fixed64,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Emoji         *ReactionEmoji `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReaction) Reset() {
	*x = AddReaction{}
	mi := &file_reactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReaction) ProtoMessage() {}

func (x *AddReaction) ProtoReflect() protoreflect.Message {
	mi := &file_reactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReaction.ProtoReflect.Descriptor instead.
func (*AddReaction) Descriptor() ([]byte, []int) {
	return file_reactions_proto_rawDescGZIP(), []int{0}
}

func (x *AddReaction) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *AddReaction) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *AddReaction) GetEmoji() *ReactionEmoji {
	if x != nil {
		return x.Emoji
	}
	return nil
}

type RemoveReaction struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChatRef *refs.ChatRef          `protobuf:"bytes,1,opt,name=chat_ref,json=chatRef,proto3" json:"chat_ref,omitempty"`
	// @snowflake<Message>
	MessageId     uint64         `protobuf:"fixed64,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Emoji         *ReactionEmoji `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReaction) Reset() {
	*x = RemoveReaction{}
	mi := &file_reactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReaction) ProtoMessage() {}

func (x *RemoveReaction) ProtoReflect() protoreflect.Message {
	mi := &file_reactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReaction.ProtoReflect.Descriptor instead.
func (*RemoveReaction) Descriptor() ([]byte, []int) {
	return file_reactions_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveReaction) GetChatRef() *refs.ChatRef {
	if x != nil {
		return x.ChatRef
	}
	return nil
}

func (x *RemoveReaction) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *RemoveReaction) GetEmoji() *ReactionEmoji {
	if x != nil {
		return x.Emoji
	}
	return nil
}

type ReactionEmoji struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Emoji:
	//
	//	*ReactionEmoji_UnicodeEmoji
	//	*ReactionEmoji_CustomEmoji
	Emoji         isReactionEmoji_Emoji `protobuf_oneof:"emoji"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionEmoji) Reset() {
	*x = ReactionEmoji{}
	mi := &file_reactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionEmoji) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionEmoji) ProtoMessage() {}

func (x *ReactionEmoji) ProtoReflect() protoreflect.Message {
	mi := &file_reactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionEmoji.ProtoReflect.Descriptor instead.
func (*ReactionEmoji) Descriptor() ([]byte, []int) {
	return file_reactions_proto_rawDescGZIP(), []int{2}
}

func (x *ReactionEmoji) GetEmoji() isReactionEmoji_Emoji {
	if x != nil {
		return x.Emoji
	}
	return nil
}

func (x *ReactionEmoji) GetUnicodeEmoji() string {
	if x != nil {
		if x, ok := x.Emoji.(*ReactionEmoji_UnicodeEmoji); ok {
			return x.UnicodeEmoji
		}
	}
	return ""
}

func (x *ReactionEmoji) GetCustomEmoji() uint64 {
	if x != nil {
		if x, ok := x.Emoji.(*ReactionEmoji_CustomEmoji); ok {
			return x.CustomEmoji
		}
	}
	return 0
}

type isReactionEmoji_Emoji interface {
	isReactionEmoji_Emoji()
}

type ReactionEmoji_UnicodeEmoji struct {
	UnicodeEmoji string `protobuf:"bytes,1,opt,name=unicode_emoji,json=unicodeEmoji,proto3,oneof"`
}

type ReactionEmoji_CustomEmoji struct {
	// @snowflake<Emoji>
	CustomEmoji uint64 `protobuf:"fixed64,2,opt,name=custom_emoji,json=customEmoji,proto3,oneof"`
}

func (*ReactionEmoji_UnicodeEmoji) isReactionEmoji_Emoji() {}

func (*ReactionEmoji_CustomEmoji) isReactionEmoji_Emoji() {}

type MessageReactions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Message>
	MessageId      uint64                  `protobuf:"fixed64,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReactionFields []*MessageReactionField `protobuf:"bytes,2,rep,name=reaction_fields,json=reactionFields,proto3" json:"reaction_fields,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageReactions) Reset() {
	*x = MessageReactions{}
	mi := &file_reactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReactions) ProtoMessage() {}

func (x *MessageReactions) ProtoReflect() protoreflect.Message {
	mi := &file_reactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReactions.ProtoReflect.Descriptor instead.
func (*MessageReactions) Descriptor() ([]byte, []int) {
	return file_reactions_proto_rawDescGZIP(), []int{3}
}

func (x *MessageReactions) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageReactions) GetReactionFields() []*MessageReactionField {
	if x != nil {
		return x.ReactionFields
	}
	return nil
}

type MessageReactionField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Emoji *ReactionEmoji         `protobuf:"bytes,1,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Count uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Me    bool                   `protobuf:"varint,3,opt,name=me,proto3" json:"me,omitempty"`
	// @snowflake<User>
	PreviewUserIds []uint64 `protobuf:"fixed64,4,rep,packed,name=preview_user_ids,json=previewUserIds,proto3" json:"preview_user_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageReactionField) Reset() {
	*x = MessageReactionField{}
	mi := &file_reactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReactionField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReactionField) ProtoMessage() {}

func (x *MessageReactionField) ProtoReflect() protoreflect.Message {
	mi := &file_reactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReactionField.ProtoReflect.Descriptor instead.
func (*MessageReactionField) Descriptor() ([]byte, []int) {
	return file_reactions_proto_rawDescGZIP(), []int{4}
}

func (x *MessageReactionField) GetEmoji() *ReactionEmoji {
	if x != nil {
		return x.Emoji
	}
	return nil
}

func (x *MessageReactionField) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MessageReactionField) GetMe() bool {
	if x != nil {
		return x.Me
	}
	return false
}

func (x *MessageReactionField) GetPreviewUserIds() []uint64 {
	if x != nil {
		return x.PreviewUserIds
	}
	return nil
}

var File_reactions_proto protoreflect.FileDescriptor

const file_reactions_proto_rawDesc = "" +
	"\n" +
	"\x0freactions.proto\x12\x17osmium.client.reactions\x1a\n" +
	"refs.proto\"\xa2\x01\n" +
	"\vAddReaction\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x06R\tmessageId\x12<\n" +
	"\x05emoji\x18\x03 \x01(\v2&.osmium.client.reactions.ReactionEmojiR\x05emoji\"\xa5\x01\n" +
	"\x0eRemoveReaction\x126\n" +
	"\bchat_ref\x18\x01 \x01(\v2\x1b.osmium.client.refs.ChatRefR\achatRef\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x06R\tmessageId\x12<\n" +
	"\x05emoji\x18\x03 \x01(\v2&.osmium.client.reactions.ReactionEmojiR\x05emoji\"d\n" +
	"\rReactionEmoji\x12%\n" +
	"\runicode_emoji\x18\x01 \x01(\tH\x00R\funicodeEmoji\x12#\n" +
	"\fcustom_emoji\x18\x02 \x01(\x06H\x00R\vcustomEmojiB\a\n" +
	"\x05emoji\"\x89\x01\n" +
	"\x10MessageReactions\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x06R\tmessageId\x12V\n" +
	"\x0freaction_fields\x18\x02 \x03(\v2-.osmium.client.reactions.MessageReactionFieldR\x0ereactionFields\"\xa4\x01\n" +
	"\x14MessageReactionField\x12<\n" +
	"\x05emoji\x18\x01 \x01(\v2&.osmium.client.reactions.ReactionEmojiR\x05emoji\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x0e\n" +
	"\x02me\x18\x03 \x01(\bR\x02me\x12(\n" +
	"\x10preview_user_ids\x18\x04 \x03(\x06R\x0epreviewUserIdsb\x06proto3"

var (
	file_reactions_proto_rawDescOnce sync.Once
	file_reactions_proto_rawDescData []byte
)

func file_reactions_proto_rawDescGZIP() []byte {
	file_reactions_proto_rawDescOnce.Do(func() {
		file_reactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reactions_proto_rawDesc), len(file_reactions_proto_rawDesc)))
	})
	return file_reactions_proto_rawDescData
}

var file_reactions_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_reactions_proto_goTypes = []any{
	(*AddReaction)(nil),          // 0: osmium.client.reactions.AddReaction
	(*RemoveReaction)(nil),       // 1: osmium.client.reactions.RemoveReaction
	(*ReactionEmoji)(nil),        // 2: osmium.client.reactions.ReactionEmoji
	(*MessageReactions)(nil),     // 3: osmium.client.reactions.MessageReactions
	(*MessageReactionField)(nil), // 4: osmium.client.reactions.MessageReactionField
	(*refs.ChatRef)(nil),         // 5: osmium.client.refs.ChatRef
}
var file_reactions_proto_depIdxs = []int32{
	5, // 0: osmium.client.reactions.AddReaction.chat_ref:type_name -> osmium.client.refs.ChatRef
	2, // 1: osmium.client.reactions.AddReaction.emoji:type_name -> osmium.client.reactions.ReactionEmoji
	5, // 2: osmium.client.reactions.RemoveReaction.chat_ref:type_name -> osmium.client.refs.ChatRef
	2, // 3: osmium.client.reactions.RemoveReaction.emoji:type_name -> osmium.client.reactions.ReactionEmoji
	4, // 4: osmium.client.reactions.MessageReactions.reaction_fields:type_name -> osmium.client.reactions.MessageReactionField
	2, // 5: osmium.client.reactions.MessageReactionField.emoji:type_name -> osmium.client.reactions.ReactionEmoji
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_reactions_proto_init() }
func file_reactions_proto_init() {
	if File_reactions_proto != nil {
		return
	}
	file_reactions_proto_msgTypes[2].OneofWrappers = []any{
		(*ReactionEmoji_UnicodeEmoji)(nil),
		(*ReactionEmoji_CustomEmoji)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reactions_proto_rawDesc), len(file_reactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reactions_proto_goTypes,
		DependencyIndexes: file_reactions_proto_depIdxs,
		MessageInfos:      file_reactions_proto_msgTypes,
	}.Build()
	File_reactions_proto = out.File
	file_reactions_proto_goTypes = nil
	file_reactions_proto_depIdxs = nil
}
