syntax = "proto3";

package osmium.client.oauth;

// oauth.authorize -> oauth.Authorization
message Authorize {
  string response_type = 1;
  uint32 client_id = 2;
  string redirect_uri = 3;
  optional string scope = 4;
  optional string state = 5;
  optional string code_challenge = 6;
  optional string code_challenge_method = 7;
  optional string nonce = 8;
}

// oauth.getApp -> oauth.App
message GetApp {
  uint32 client_id = 1;
}

message Authorization {
  string redirect_uri = 1;
  string code = 2;
  optional string state = 3;
  uint64 expires_at = 4;
}

message App {
  uint32 client_id = 1;
  string name = 2;
  uint64 flags = 3;
  repeated string redirect_uris = 4;
}
