// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: settings.proto

package settings

import (
	media "github.com/ofabiodev/osmose/proto/media"
	refs "github.com/ofabiodev/osmose/proto/refs"
	types "github.com/ofabiodev/osmose/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterPushSubscription_PushType int32

const (
	RegisterPushSubscription_UNKNOWN     RegisterPushSubscription_PushType = 0
	RegisterPushSubscription_WEB         RegisterPushSubscription_PushType = 1
	RegisterPushSubscription_IOS         RegisterPushSubscription_PushType = 2
	RegisterPushSubscription_ANDROID_FCM RegisterPushSubscription_PushType = 3
)

// Enum value maps for RegisterPushSubscription_PushType.
var (
	RegisterPushSubscription_PushType_name = map[int32]string{
		0: "UNKNOWN",
		1: "WEB",
		2: "IOS",
		3: "ANDROID_FCM",
	}
	RegisterPushSubscription_PushType_value = map[string]int32{
		"UNKNOWN":     0,
		"WEB":         1,
		"IOS":         2,
		"ANDROID_FCM": 3,
	}
)

func (x RegisterPushSubscription_PushType) Enum() *RegisterPushSubscription_PushType {
	p := new(RegisterPushSubscription_PushType)
	*p = x
	return p
}

func (x RegisterPushSubscription_PushType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterPushSubscription_PushType) Descriptor() protoreflect.EnumDescriptor {
	return file_settings_proto_enumTypes[0].Descriptor()
}

func (RegisterPushSubscription_PushType) Type() protoreflect.EnumType {
	return &file_settings_proto_enumTypes[0]
}

func (x RegisterPushSubscription_PushType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterPushSubscription_PushType.Descriptor instead.
func (RegisterPushSubscription_PushType) EnumDescriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{2, 0}
}

type RegisterPushSubscription_PushEncryptionScheme int32

const (
	RegisterPushSubscription_PUSH_ENCRYPTION_UNKNOWN       RegisterPushSubscription_PushEncryptionScheme = 0
	RegisterPushSubscription_P256_HKDF_SHA256_AES256GCM_V1 RegisterPushSubscription_PushEncryptionScheme = 1
)

// Enum value maps for RegisterPushSubscription_PushEncryptionScheme.
var (
	RegisterPushSubscription_PushEncryptionScheme_name = map[int32]string{
		0: "PUSH_ENCRYPTION_UNKNOWN",
		1: "P256_HKDF_SHA256_AES256GCM_V1",
	}
	RegisterPushSubscription_PushEncryptionScheme_value = map[string]int32{
		"PUSH_ENCRYPTION_UNKNOWN":       0,
		"P256_HKDF_SHA256_AES256GCM_V1": 1,
	}
)

func (x RegisterPushSubscription_PushEncryptionScheme) Enum() *RegisterPushSubscription_PushEncryptionScheme {
	p := new(RegisterPushSubscription_PushEncryptionScheme)
	*p = x
	return p
}

func (x RegisterPushSubscription_PushEncryptionScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterPushSubscription_PushEncryptionScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_settings_proto_enumTypes[1].Descriptor()
}

func (RegisterPushSubscription_PushEncryptionScheme) Type() protoreflect.EnumType {
	return &file_settings_proto_enumTypes[1]
}

func (x RegisterPushSubscription_PushEncryptionScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterPushSubscription_PushEncryptionScheme.Descriptor instead.
func (RegisterPushSubscription_PushEncryptionScheme) EnumDescriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{2, 1}
}

// settings.editProfilePhoto -> ()
type EditProfilePhoto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *media.UploadedFileRef `protobuf:"bytes,1,opt,name=file,proto3,oneof" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProfilePhoto) Reset() {
	*x = EditProfilePhoto{}
	mi := &file_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProfilePhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProfilePhoto) ProtoMessage() {}

func (x *EditProfilePhoto) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProfilePhoto.ProtoReflect.Descriptor instead.
func (*EditProfilePhoto) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{0}
}

func (x *EditProfilePhoto) GetFile() *media.UploadedFileRef {
	if x != nil {
		return x.File
	}
	return nil
}

// settings.editProfileBanner -> ()
type EditProfileBanner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *media.UploadedFileRef `protobuf:"bytes,1,opt,name=file,proto3,oneof" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProfileBanner) Reset() {
	*x = EditProfileBanner{}
	mi := &file_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProfileBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProfileBanner) ProtoMessage() {}

func (x *EditProfileBanner) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProfileBanner.ProtoReflect.Descriptor instead.
func (*EditProfileBanner) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{1}
}

func (x *EditProfileBanner) GetFile() *media.UploadedFileRef {
	if x != nil {
		return x.File
	}
	return nil
}

// settings.registerPushSubscription -> ()
type RegisterPushSubscription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Subscription:
	//
	//	*RegisterPushSubscription_Web
	//	*RegisterPushSubscription_Push_
	Subscription  isRegisterPushSubscription_Subscription `protobuf_oneof:"subscription"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPushSubscription) Reset() {
	*x = RegisterPushSubscription{}
	mi := &file_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPushSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPushSubscription) ProtoMessage() {}

func (x *RegisterPushSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPushSubscription.ProtoReflect.Descriptor instead.
func (*RegisterPushSubscription) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterPushSubscription) GetSubscription() isRegisterPushSubscription_Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *RegisterPushSubscription) GetWeb() *RegisterPushSubscription_WebPush {
	if x != nil {
		if x, ok := x.Subscription.(*RegisterPushSubscription_Web); ok {
			return x.Web
		}
	}
	return nil
}

func (x *RegisterPushSubscription) GetPush() *RegisterPushSubscription_Push {
	if x != nil {
		if x, ok := x.Subscription.(*RegisterPushSubscription_Push_); ok {
			return x.Push
		}
	}
	return nil
}

type isRegisterPushSubscription_Subscription interface {
	isRegisterPushSubscription_Subscription()
}

type RegisterPushSubscription_Web struct {
	Web *RegisterPushSubscription_WebPush `protobuf:"bytes,1,opt,name=web,proto3,oneof"`
}

type RegisterPushSubscription_Push_ struct {
	Push *RegisterPushSubscription_Push `protobuf:"bytes,2,opt,name=push,proto3,oneof"`
}

func (*RegisterPushSubscription_Web) isRegisterPushSubscription_Subscription() {}

func (*RegisterPushSubscription_Push_) isRegisterPushSubscription_Subscription() {}

// settings.unregisterPushSubscription -> ()
type UnregisterPushSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterPushSubscription) Reset() {
	*x = UnregisterPushSubscription{}
	mi := &file_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterPushSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterPushSubscription) ProtoMessage() {}

func (x *UnregisterPushSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterPushSubscription.ProtoReflect.Descriptor instead.
func (*UnregisterPushSubscription) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{3}
}

// settings.changeNotificationPreferences -> ()
type ChangeNotificationPreferences struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Prefs types.NotifPrefs       `protobuf:"varint,1,opt,name=prefs,proto3,enum=osmium.client.types.NotifPrefs" json:"prefs,omitempty"`
	// Types that are valid to be assigned to Scope:
	//
	//	*ChangeNotificationPreferences_ChatRef
	//	*ChangeNotificationPreferences_CommunityId
	Scope         isChangeNotificationPreferences_Scope `protobuf_oneof:"scope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeNotificationPreferences) Reset() {
	*x = ChangeNotificationPreferences{}
	mi := &file_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeNotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeNotificationPreferences) ProtoMessage() {}

func (x *ChangeNotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeNotificationPreferences.ProtoReflect.Descriptor instead.
func (*ChangeNotificationPreferences) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeNotificationPreferences) GetPrefs() types.NotifPrefs {
	if x != nil {
		return x.Prefs
	}
	return types.NotifPrefs(0)
}

func (x *ChangeNotificationPreferences) GetScope() isChangeNotificationPreferences_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ChangeNotificationPreferences) GetChatRef() *refs.ChatRef {
	if x != nil {
		if x, ok := x.Scope.(*ChangeNotificationPreferences_ChatRef); ok {
			return x.ChatRef
		}
	}
	return nil
}

func (x *ChangeNotificationPreferences) GetCommunityId() uint64 {
	if x != nil {
		if x, ok := x.Scope.(*ChangeNotificationPreferences_CommunityId); ok {
			return x.CommunityId
		}
	}
	return 0
}

type isChangeNotificationPreferences_Scope interface {
	isChangeNotificationPreferences_Scope()
}

type ChangeNotificationPreferences_ChatRef struct {
	ChatRef *refs.ChatRef `protobuf:"bytes,2,opt,name=chat_ref,json=chatRef,proto3,oneof"` // For channel or DM chat
}

type ChangeNotificationPreferences_CommunityId struct {
	// @snowflake<Community>
	CommunityId uint64 `protobuf:"fixed64,3,opt,name=community_id,json=communityId,proto3,oneof"` // For community-level default
}

func (*ChangeNotificationPreferences_ChatRef) isChangeNotificationPreferences_Scope() {}

func (*ChangeNotificationPreferences_CommunityId) isChangeNotificationPreferences_Scope() {}

// settings.editUserSettings -> settings.UserSettings
type EditUserSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *UserSettings          `protobuf:"bytes,1,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserSettings) Reset() {
	*x = EditUserSettings{}
	mi := &file_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserSettings) ProtoMessage() {}

func (x *EditUserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserSettings.ProtoReflect.Descriptor instead.
func (*EditUserSettings) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{5}
}

func (x *EditUserSettings) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UserSettings struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	CommunityOrder   *UserSettings_CommunityOrder   `protobuf:"bytes,1,opt,name=community_order,json=communityOrder,proto3,oneof" json:"community_order,omitempty"`
	EmailPreferences *UserSettings_EmailPreferences `protobuf:"bytes,2,opt,name=email_preferences,json=emailPreferences,proto3,oneof" json:"email_preferences,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{6}
}

func (x *UserSettings) GetCommunityOrder() *UserSettings_CommunityOrder {
	if x != nil {
		return x.CommunityOrder
	}
	return nil
}

func (x *UserSettings) GetEmailPreferences() *UserSettings_EmailPreferences {
	if x != nil {
		return x.EmailPreferences
	}
	return nil
}

// settings.editProfile -> ()
type EditProfile struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Username *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Bio      *string                `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	// @snowflake<Emoji>
	Icon  *uint64 `protobuf:"fixed64,4,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Color *uint32 `protobuf:"varint,5,opt,name=color,proto3,oneof" json:"color,omitempty"`
	// Packed RGB colors: first color in bits 0-23, second color in bits 24-47.
	ThemeColor        *uint64 `protobuf:"varint,6,opt,name=theme_color,json=themeColor,proto3,oneof" json:"theme_color,omitempty"`
	ShowBannerInVoice *bool   `protobuf:"varint,7,opt,name=show_banner_in_voice,json=showBannerInVoice,proto3,oneof" json:"show_banner_in_voice,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EditProfile) Reset() {
	*x = EditProfile{}
	mi := &file_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProfile) ProtoMessage() {}

func (x *EditProfile) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProfile.ProtoReflect.Descriptor instead.
func (*EditProfile) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{7}
}

func (x *EditProfile) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EditProfile) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *EditProfile) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *EditProfile) GetIcon() uint64 {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return 0
}

func (x *EditProfile) GetColor() uint32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return 0
}

func (x *EditProfile) GetThemeColor() uint64 {
	if x != nil && x.ThemeColor != nil {
		return *x.ThemeColor
	}
	return 0
}

func (x *EditProfile) GetShowBannerInVoice() bool {
	if x != nil && x.ShowBannerInVoice != nil {
		return *x.ShowBannerInVoice
	}
	return false
}

// settings.getAccount -> settings.Account
type GetAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccount) Reset() {
	*x = GetAccount{}
	mi := &file_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccount) ProtoMessage() {}

func (x *GetAccount) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccount.ProtoReflect.Descriptor instead.
func (*GetAccount) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{8}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Confirmed     bool                   `protobuf:"varint,2,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	HasPassword   bool                   `protobuf:"varint,3,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`
	TotpEnabled   bool                   `protobuf:"varint,4,opt,name=totp_enabled,json=totpEnabled,proto3" json:"totp_enabled,omitempty"`
	PendingDelete bool                   `protobuf:"varint,5,opt,name=pending_delete,json=pendingDelete,proto3" json:"pending_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_settings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{9}
}

func (x *Account) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Account) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *Account) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

func (x *Account) GetTotpEnabled() bool {
	if x != nil {
		return x.TotpEnabled
	}
	return false
}

func (x *Account) GetPendingDelete() bool {
	if x != nil {
		return x.PendingDelete
	}
	return false
}

// settings.changePassword -> ()
type ChangePassword struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	RevokeSessions  bool                   `protobuf:"varint,3,opt,name=revoke_sessions,json=revokeSessions,proto3" json:"revoke_sessions,omitempty"` // Revoke all other sessions after password change
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePassword) Reset() {
	*x = ChangePassword{}
	mi := &file_settings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePassword) ProtoMessage() {}

func (x *ChangePassword) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePassword.ProtoReflect.Descriptor instead.
func (*ChangePassword) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{10}
}

func (x *ChangePassword) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePassword) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ChangePassword) GetRevokeSessions() bool {
	if x != nil {
		return x.RevokeSessions
	}
	return false
}

// settings.changeEmail -> ()
type ChangeEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewEmail      string                 `protobuf:"bytes,1,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEmail) Reset() {
	*x = ChangeEmail{}
	mi := &file_settings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEmail) ProtoMessage() {}

func (x *ChangeEmail) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEmail.ProtoReflect.Descriptor instead.
func (*ChangeEmail) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeEmail) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

// settings.changeStatus -> ()
type ChangeStatus struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        types.UserStatus_Status      `protobuf:"varint,2,opt,name=status,proto3,enum=osmium.client.types.UserStatus_Status" json:"status,omitempty"`
	Activities    []*types.UserStatus_Activity `protobuf:"bytes,3,rep,name=activities,proto3" json:"activities,omitempty"`
	LastActive    *uint64                      `protobuf:"fixed64,4,opt,name=last_active,json=lastActive,proto3,oneof" json:"last_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStatus) Reset() {
	*x = ChangeStatus{}
	mi := &file_settings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStatus) ProtoMessage() {}

func (x *ChangeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStatus.ProtoReflect.Descriptor instead.
func (*ChangeStatus) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeStatus) GetStatus() types.UserStatus_Status {
	if x != nil {
		return x.Status
	}
	return types.UserStatus_Status(0)
}

func (x *ChangeStatus) GetActivities() []*types.UserStatus_Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ChangeStatus) GetLastActive() uint64 {
	if x != nil && x.LastActive != nil {
		return *x.LastActive
	}
	return 0
}

// settings.setupTotp -> settings.Totp
type SetupTotp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Code          *string                `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	StepUpToken   *string                `protobuf:"bytes,3,opt,name=step_up_token,json=stepUpToken,proto3,oneof" json:"step_up_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupTotp) Reset() {
	*x = SetupTotp{}
	mi := &file_settings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupTotp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupTotp) ProtoMessage() {}

func (x *SetupTotp) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupTotp.ProtoReflect.Descriptor instead.
func (*SetupTotp) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{13}
}

func (x *SetupTotp) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SetupTotp) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *SetupTotp) GetStepUpToken() string {
	if x != nil && x.StepUpToken != nil {
		return *x.StepUpToken
	}
	return ""
}

type Totp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Url           *string                `protobuf:"bytes,2,opt,name=url,proto3,oneof" json:"url,omitempty"`
	BackupCodes   []*BackupCode          `protobuf:"bytes,3,rep,name=backup_codes,json=backupCodes,proto3" json:"backup_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Totp) Reset() {
	*x = Totp{}
	mi := &file_settings_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Totp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Totp) ProtoMessage() {}

func (x *Totp) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Totp.ProtoReflect.Descriptor instead.
func (*Totp) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{14}
}

func (x *Totp) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Totp) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Totp) GetBackupCodes() []*BackupCode {
	if x != nil {
		return x.BackupCodes
	}
	return nil
}

type BackupCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Used          bool                   `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCode) Reset() {
	*x = BackupCode{}
	mi := &file_settings_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCode) ProtoMessage() {}

func (x *BackupCode) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCode.ProtoReflect.Descriptor instead.
func (*BackupCode) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{15}
}

func (x *BackupCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BackupCode) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

// settings.setupWebauthn -> settings.Webauthn
type SetupWebauthn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CredentialJson *string                `protobuf:"bytes,2,opt,name=credential_json,json=credentialJson,proto3,oneof" json:"credential_json,omitempty"`
	// @snowflake<AccountMfa>
	CredentialId  *uint64 `protobuf:"fixed64,3,opt,name=credential_id,json=credentialId,proto3,oneof" json:"credential_id,omitempty"`
	DisplayName   *string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	StepUpToken   *string `protobuf:"bytes,5,opt,name=step_up_token,json=stepUpToken,proto3,oneof" json:"step_up_token,omitempty"`
	ChallengeId   *string `protobuf:"bytes,6,opt,name=challenge_id,json=challengeId,proto3,oneof" json:"challenge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupWebauthn) Reset() {
	*x = SetupWebauthn{}
	mi := &file_settings_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupWebauthn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupWebauthn) ProtoMessage() {}

func (x *SetupWebauthn) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupWebauthn.ProtoReflect.Descriptor instead.
func (*SetupWebauthn) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{16}
}

func (x *SetupWebauthn) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SetupWebauthn) GetCredentialJson() string {
	if x != nil && x.CredentialJson != nil {
		return *x.CredentialJson
	}
	return ""
}

func (x *SetupWebauthn) GetCredentialId() uint64 {
	if x != nil && x.CredentialId != nil {
		return *x.CredentialId
	}
	return 0
}

func (x *SetupWebauthn) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *SetupWebauthn) GetStepUpToken() string {
	if x != nil && x.StepUpToken != nil {
		return *x.StepUpToken
	}
	return ""
}

func (x *SetupWebauthn) GetChallengeId() string {
	if x != nil && x.ChallengeId != nil {
		return *x.ChallengeId
	}
	return ""
}

type Webauthn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionsJson   *string                `protobuf:"bytes,1,opt,name=options_json,json=optionsJson,proto3,oneof" json:"options_json,omitempty"`
	Credential    *WebauthnCredential    `protobuf:"bytes,2,opt,name=credential,proto3,oneof" json:"credential,omitempty"`
	RecoveryCodes []*BackupCode          `protobuf:"bytes,3,rep,name=recovery_codes,json=recoveryCodes,proto3" json:"recovery_codes,omitempty"`
	ChallengeId   *string                `protobuf:"bytes,4,opt,name=challenge_id,json=challengeId,proto3,oneof" json:"challenge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Webauthn) Reset() {
	*x = Webauthn{}
	mi := &file_settings_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webauthn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webauthn) ProtoMessage() {}

func (x *Webauthn) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webauthn.ProtoReflect.Descriptor instead.
func (*Webauthn) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{17}
}

func (x *Webauthn) GetOptionsJson() string {
	if x != nil && x.OptionsJson != nil {
		return *x.OptionsJson
	}
	return ""
}

func (x *Webauthn) GetCredential() *WebauthnCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *Webauthn) GetRecoveryCodes() []*BackupCode {
	if x != nil {
		return x.RecoveryCodes
	}
	return nil
}

func (x *Webauthn) GetChallengeId() string {
	if x != nil && x.ChallengeId != nil {
		return *x.ChallengeId
	}
	return ""
}

type WebauthnCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<AccountMfa>
	Id            uint64  `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	CredentialId  string  `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	DisplayName   string  `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CreatedAt     uint64  `protobuf:"fixed64,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *uint64 `protobuf:"fixed64,5,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebauthnCredential) Reset() {
	*x = WebauthnCredential{}
	mi := &file_settings_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebauthnCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebauthnCredential) ProtoMessage() {}

func (x *WebauthnCredential) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebauthnCredential.ProtoReflect.Descriptor instead.
func (*WebauthnCredential) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{18}
}

func (x *WebauthnCredential) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebauthnCredential) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *WebauthnCredential) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *WebauthnCredential) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WebauthnCredential) GetLastUsedAt() uint64 {
	if x != nil && x.LastUsedAt != nil {
		return *x.LastUsedAt
	}
	return 0
}

// settings.getMfaMethods -> settings.MfaMethods
type GetMfaMethods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMfaMethods) Reset() {
	*x = GetMfaMethods{}
	mi := &file_settings_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMfaMethods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMfaMethods) ProtoMessage() {}

func (x *GetMfaMethods) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMfaMethods.ProtoReflect.Descriptor instead.
func (*GetMfaMethods) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{19}
}

type MfaMethods struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotpEnabled            bool                   `protobuf:"varint,1,opt,name=totp_enabled,json=totpEnabled,proto3" json:"totp_enabled,omitempty"`
	WebauthnCredentials    []*WebauthnCredential  `protobuf:"bytes,2,rep,name=webauthn_credentials,json=webauthnCredentials,proto3" json:"webauthn_credentials,omitempty"`
	RecoveryCodesRemaining uint32                 `protobuf:"varint,3,opt,name=recovery_codes_remaining,json=recoveryCodesRemaining,proto3" json:"recovery_codes_remaining,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MfaMethods) Reset() {
	*x = MfaMethods{}
	mi := &file_settings_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaMethods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaMethods) ProtoMessage() {}

func (x *MfaMethods) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaMethods.ProtoReflect.Descriptor instead.
func (*MfaMethods) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{20}
}

func (x *MfaMethods) GetTotpEnabled() bool {
	if x != nil {
		return x.TotpEnabled
	}
	return false
}

func (x *MfaMethods) GetWebauthnCredentials() []*WebauthnCredential {
	if x != nil {
		return x.WebauthnCredentials
	}
	return nil
}

func (x *MfaMethods) GetRecoveryCodesRemaining() uint32 {
	if x != nil {
		return x.RecoveryCodesRemaining
	}
	return 0
}

// settings.beginMfaStepUp -> settings.MfaStepUp
type BeginMfaStepUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginMfaStepUp) Reset() {
	*x = BeginMfaStepUp{}
	mi := &file_settings_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginMfaStepUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginMfaStepUp) ProtoMessage() {}

func (x *BeginMfaStepUp) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginMfaStepUp.ProtoReflect.Descriptor instead.
func (*BeginMfaStepUp) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{21}
}

func (x *BeginMfaStepUp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type MfaStepUp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StepUpToken         *string                `protobuf:"bytes,1,opt,name=step_up_token,json=stepUpToken,proto3,oneof" json:"step_up_token,omitempty"`
	ChallengeId         *string                `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3,oneof" json:"challenge_id,omitempty"`
	ExpiresAt           *uint64                `protobuf:"fixed64,3,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	Totp                bool                   `protobuf:"varint,4,opt,name=totp,proto3" json:"totp,omitempty"`
	RecoveryCodes       bool                   `protobuf:"varint,5,opt,name=recovery_codes,json=recoveryCodes,proto3" json:"recovery_codes,omitempty"`
	WebauthnOptionsJson *string                `protobuf:"bytes,6,opt,name=webauthn_options_json,json=webauthnOptionsJson,proto3,oneof" json:"webauthn_options_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MfaStepUp) Reset() {
	*x = MfaStepUp{}
	mi := &file_settings_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaStepUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaStepUp) ProtoMessage() {}

func (x *MfaStepUp) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaStepUp.ProtoReflect.Descriptor instead.
func (*MfaStepUp) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{22}
}

func (x *MfaStepUp) GetStepUpToken() string {
	if x != nil && x.StepUpToken != nil {
		return *x.StepUpToken
	}
	return ""
}

func (x *MfaStepUp) GetChallengeId() string {
	if x != nil && x.ChallengeId != nil {
		return *x.ChallengeId
	}
	return ""
}

func (x *MfaStepUp) GetExpiresAt() uint64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *MfaStepUp) GetTotp() bool {
	if x != nil {
		return x.Totp
	}
	return false
}

func (x *MfaStepUp) GetRecoveryCodes() bool {
	if x != nil {
		return x.RecoveryCodes
	}
	return false
}

func (x *MfaStepUp) GetWebauthnOptionsJson() string {
	if x != nil && x.WebauthnOptionsJson != nil {
		return *x.WebauthnOptionsJson
	}
	return ""
}

// settings.completeMfaStepUp -> settings.MfaStepUp
type CompleteMfaStepUp struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// Types that are valid to be assigned to Proof:
	//
	//	*CompleteMfaStepUp_Totp
	//	*CompleteMfaStepUp_RecoveryCode
	//	*CompleteMfaStepUp_WebauthnCredentialJson
	Proof         isCompleteMfaStepUp_Proof `protobuf_oneof:"proof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMfaStepUp) Reset() {
	*x = CompleteMfaStepUp{}
	mi := &file_settings_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMfaStepUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMfaStepUp) ProtoMessage() {}

func (x *CompleteMfaStepUp) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMfaStepUp.ProtoReflect.Descriptor instead.
func (*CompleteMfaStepUp) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{23}
}

func (x *CompleteMfaStepUp) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CompleteMfaStepUp) GetProof() isCompleteMfaStepUp_Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *CompleteMfaStepUp) GetTotp() string {
	if x != nil {
		if x, ok := x.Proof.(*CompleteMfaStepUp_Totp); ok {
			return x.Totp
		}
	}
	return ""
}

func (x *CompleteMfaStepUp) GetRecoveryCode() string {
	if x != nil {
		if x, ok := x.Proof.(*CompleteMfaStepUp_RecoveryCode); ok {
			return x.RecoveryCode
		}
	}
	return ""
}

func (x *CompleteMfaStepUp) GetWebauthnCredentialJson() string {
	if x != nil {
		if x, ok := x.Proof.(*CompleteMfaStepUp_WebauthnCredentialJson); ok {
			return x.WebauthnCredentialJson
		}
	}
	return ""
}

type isCompleteMfaStepUp_Proof interface {
	isCompleteMfaStepUp_Proof()
}

type CompleteMfaStepUp_Totp struct {
	Totp string `protobuf:"bytes,2,opt,name=totp,proto3,oneof"`
}

type CompleteMfaStepUp_RecoveryCode struct {
	RecoveryCode string `protobuf:"bytes,3,opt,name=recovery_code,json=recoveryCode,proto3,oneof"`
}

type CompleteMfaStepUp_WebauthnCredentialJson struct {
	WebauthnCredentialJson string `protobuf:"bytes,4,opt,name=webauthn_credential_json,json=webauthnCredentialJson,proto3,oneof"`
}

func (*CompleteMfaStepUp_Totp) isCompleteMfaStepUp_Proof() {}

func (*CompleteMfaStepUp_RecoveryCode) isCompleteMfaStepUp_Proof() {}

func (*CompleteMfaStepUp_WebauthnCredentialJson) isCompleteMfaStepUp_Proof() {}

// settings.regenerateRecoveryCodes -> settings.RecoveryCodes
type RegenerateRecoveryCodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepUpToken   string                 `protobuf:"bytes,1,opt,name=step_up_token,json=stepUpToken,proto3" json:"step_up_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateRecoveryCodes) Reset() {
	*x = RegenerateRecoveryCodes{}
	mi := &file_settings_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateRecoveryCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateRecoveryCodes) ProtoMessage() {}

func (x *RegenerateRecoveryCodes) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateRecoveryCodes.ProtoReflect.Descriptor instead.
func (*RegenerateRecoveryCodes) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{24}
}

func (x *RegenerateRecoveryCodes) GetStepUpToken() string {
	if x != nil {
		return x.StepUpToken
	}
	return ""
}

// settings.getRecoveryCodes -> settings.RecoveryCodes
type GetRecoveryCodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecoveryCodes) Reset() {
	*x = GetRecoveryCodes{}
	mi := &file_settings_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecoveryCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecoveryCodes) ProtoMessage() {}

func (x *GetRecoveryCodes) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecoveryCodes.ProtoReflect.Descriptor instead.
func (*GetRecoveryCodes) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{25}
}

func (x *GetRecoveryCodes) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RecoveryCodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecoveryCodes []*BackupCode          `protobuf:"bytes,1,rep,name=recovery_codes,json=recoveryCodes,proto3" json:"recovery_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryCodes) Reset() {
	*x = RecoveryCodes{}
	mi := &file_settings_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryCodes) ProtoMessage() {}

func (x *RecoveryCodes) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryCodes.ProtoReflect.Descriptor instead.
func (*RecoveryCodes) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{26}
}

func (x *RecoveryCodes) GetRecoveryCodes() []*BackupCode {
	if x != nil {
		return x.RecoveryCodes
	}
	return nil
}

// settings.requestTakeout -> ()
type RequestTakeout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTakeout) Reset() {
	*x = RequestTakeout{}
	mi := &file_settings_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTakeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTakeout) ProtoMessage() {}

func (x *RequestTakeout) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTakeout.ProtoReflect.Descriptor instead.
func (*RequestTakeout) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{27}
}

// settings.deleteAccount -> ()
type DeleteAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancel        *bool                  `protobuf:"varint,1,opt,name=cancel,proto3,oneof" json:"cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccount) Reset() {
	*x = DeleteAccount{}
	mi := &file_settings_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccount) ProtoMessage() {}

func (x *DeleteAccount) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccount.ProtoReflect.Descriptor instead.
func (*DeleteAccount) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteAccount) GetCancel() bool {
	if x != nil && x.Cancel != nil {
		return *x.Cancel
	}
	return false
}

type RegisterPushSubscription_WebPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	P256Dh        string                 `protobuf:"bytes,2,opt,name=p256dh,proto3" json:"p256dh,omitempty"`
	Auth          string                 `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPushSubscription_WebPush) Reset() {
	*x = RegisterPushSubscription_WebPush{}
	mi := &file_settings_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPushSubscription_WebPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPushSubscription_WebPush) ProtoMessage() {}

func (x *RegisterPushSubscription_WebPush) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPushSubscription_WebPush.ProtoReflect.Descriptor instead.
func (*RegisterPushSubscription_WebPush) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RegisterPushSubscription_WebPush) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterPushSubscription_WebPush) GetP256Dh() string {
	if x != nil {
		return x.P256Dh
	}
	return ""
}

func (x *RegisterPushSubscription_WebPush) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type RegisterPushSubscription_Push struct {
	state                protoimpl.MessageState                        `protogen:"open.v1"`
	Type                 RegisterPushSubscription_PushType             `protobuf:"varint,1,opt,name=type,proto3,enum=osmium.client.settings.RegisterPushSubscription_PushType" json:"type,omitempty"`
	Token                string                                        `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	EncryptionPublicKey  *string                                       `protobuf:"bytes,3,opt,name=encryption_public_key,json=encryptionPublicKey,proto3,oneof" json:"encryption_public_key,omitempty"`
	EncryptionAuthSecret *string                                       `protobuf:"bytes,4,opt,name=encryption_auth_secret,json=encryptionAuthSecret,proto3,oneof" json:"encryption_auth_secret,omitempty"`
	EncryptionKeyId      *string                                       `protobuf:"bytes,5,opt,name=encryption_key_id,json=encryptionKeyId,proto3,oneof" json:"encryption_key_id,omitempty"`
	EncryptionScheme     RegisterPushSubscription_PushEncryptionScheme `protobuf:"varint,6,opt,name=encryption_scheme,json=encryptionScheme,proto3,enum=osmium.client.settings.RegisterPushSubscription_PushEncryptionScheme" json:"encryption_scheme,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterPushSubscription_Push) Reset() {
	*x = RegisterPushSubscription_Push{}
	mi := &file_settings_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPushSubscription_Push) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPushSubscription_Push) ProtoMessage() {}

func (x *RegisterPushSubscription_Push) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPushSubscription_Push.ProtoReflect.Descriptor instead.
func (*RegisterPushSubscription_Push) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{2, 1}
}

func (x *RegisterPushSubscription_Push) GetType() RegisterPushSubscription_PushType {
	if x != nil {
		return x.Type
	}
	return RegisterPushSubscription_UNKNOWN
}

func (x *RegisterPushSubscription_Push) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterPushSubscription_Push) GetEncryptionPublicKey() string {
	if x != nil && x.EncryptionPublicKey != nil {
		return *x.EncryptionPublicKey
	}
	return ""
}

func (x *RegisterPushSubscription_Push) GetEncryptionAuthSecret() string {
	if x != nil && x.EncryptionAuthSecret != nil {
		return *x.EncryptionAuthSecret
	}
	return ""
}

func (x *RegisterPushSubscription_Push) GetEncryptionKeyId() string {
	if x != nil && x.EncryptionKeyId != nil {
		return *x.EncryptionKeyId
	}
	return ""
}

func (x *RegisterPushSubscription_Push) GetEncryptionScheme() RegisterPushSubscription_PushEncryptionScheme {
	if x != nil {
		return x.EncryptionScheme
	}
	return RegisterPushSubscription_PUSH_ENCRYPTION_UNKNOWN
}

type UserSettings_CommunityOrder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @snowflake<Community>
	CommunityIds  []uint64 `protobuf:"fixed64,1,rep,packed,name=community_ids,json=communityIds,proto3" json:"community_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSettings_CommunityOrder) Reset() {
	*x = UserSettings_CommunityOrder{}
	mi := &file_settings_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings_CommunityOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings_CommunityOrder) ProtoMessage() {}

func (x *UserSettings_CommunityOrder) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings_CommunityOrder.ProtoReflect.Descriptor instead.
func (*UserSettings_CommunityOrder) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UserSettings_CommunityOrder) GetCommunityIds() []uint64 {
	if x != nil {
		return x.CommunityIds
	}
	return nil
}

type UserSettings_EmailPreferences struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transactional emails for missed calls, messages, and friend requests.
	CommunicationEmails *bool `protobuf:"varint,1,opt,name=communication_emails,json=communicationEmails,proto3,oneof" json:"communication_emails,omitempty"`
	// Promotion emails for update announcements.
	AnnouncementEmails *bool `protobuf:"varint,2,opt,name=announcement_emails,json=announcementEmails,proto3,oneof" json:"announcement_emails,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserSettings_EmailPreferences) Reset() {
	*x = UserSettings_EmailPreferences{}
	mi := &file_settings_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings_EmailPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings_EmailPreferences) ProtoMessage() {}

func (x *UserSettings_EmailPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings_EmailPreferences.ProtoReflect.Descriptor instead.
func (*UserSettings_EmailPreferences) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{6, 1}
}

func (x *UserSettings_EmailPreferences) GetCommunicationEmails() bool {
	if x != nil && x.CommunicationEmails != nil {
		return *x.CommunicationEmails
	}
	return false
}

func (x *UserSettings_EmailPreferences) GetAnnouncementEmails() bool {
	if x != nil && x.AnnouncementEmails != nil {
		return *x.AnnouncementEmails
	}
	return false
}

var File_settings_proto protoreflect.FileDescriptor

const file_settings_proto_rawDesc = "" +
	"\n" +
	"\x0esettings.proto\x12\x16osmium.client.settings\x1a\vmedia.proto\x1a\n" +
	"refs.proto\x1a\vtypes.proto\"Z\n" +
	"\x10EditProfilePhoto\x12=\n" +
	"\x04file\x18\x01 \x01(\v2$.osmium.client.media.UploadedFileRefH\x00R\x04file\x88\x01\x01B\a\n" +
	"\x05_file\"[\n" +
	"\x11EditProfileBanner\x12=\n" +
	"\x04file\x18\x01 \x01(\v2$.osmium.client.media.UploadedFileRefH\x00R\x04file\x88\x01\x01B\a\n" +
	"\x05_file\"\xfe\x06\n" +
	"\x18RegisterPushSubscription\x12L\n" +
	"\x03web\x18\x01 \x01(\v28.osmium.client.settings.RegisterPushSubscription.WebPushH\x00R\x03web\x12K\n" +
	"\x04push\x18\x02 \x01(\v25.osmium.client.settings.RegisterPushSubscription.PushH\x00R\x04push\x1aQ\n" +
	"\aWebPush\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06p256dh\x18\x02 \x01(\tR\x06p256dh\x12\x12\n" +
	"\x04auth\x18\x03 \x01(\tR\x04auth\x1a\xcf\x03\n" +
	"\x04Push\x12M\n" +
	"\x04type\x18\x01 \x01(\x0e29.osmium.client.settings.RegisterPushSubscription.PushTypeR\x04type\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x127\n" +
	"\x15encryption_public_key\x18\x03 \x01(\tH\x00R\x13encryptionPublicKey\x88\x01\x01\x129\n" +
	"\x16encryption_auth_secret\x18\x04 \x01(\tH\x01R\x14encryptionAuthSecret\x88\x01\x01\x12/\n" +
	"\x11encryption_key_id\x18\x05 \x01(\tH\x02R\x0fencryptionKeyId\x88\x01\x01\x12r\n" +
	"\x11encryption_scheme\x18\x06 \x01(\x0e2E.osmium.client.settings.RegisterPushSubscription.PushEncryptionSchemeR\x10encryptionSchemeB\x18\n" +
	"\x16_encryption_public_keyB\x19\n" +
	"\x17_encryption_auth_secretB\x14\n" +
	"\x12_encryption_key_id\":\n" +
	"\bPushType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03WEB\x10\x01\x12\a\n" +
	"\x03IOS\x10\x02\x12\x0f\n" +
	"\vANDROID_FCM\x10\x03\"V\n" +
	"\x14PushEncryptionScheme\x12\x1b\n" +
	"\x17PUSH_ENCRYPTION_UNKNOWN\x10\x00\x12!\n" +
	"\x1dP256_HKDF_SHA256_AES256GCM_V1\x10\x01B\x0e\n" +
	"\fsubscription\"\x1c\n" +
	"\x1aUnregisterPushSubscription\"\xbe\x01\n" +
	"\x1dChangeNotificationPreferences\x125\n" +
	"\x05prefs\x18\x01 \x01(\x0e2\x1f.osmium.client.types.NotifPrefsR\x05prefs\x128\n" +
	"\bchat_ref\x18\x02 \x01(\v2\x1b.osmium.client.refs.ChatRefH\x00R\achatRef\x12#\n" +
	"\fcommunity_id\x18\x03 \x01(\x06H\x00R\vcommunityIdB\a\n" +
	"\x05scope\"f\n" +
	"\x10EditUserSettings\x12E\n" +
	"\bsettings\x18\x01 \x01(\v2$.osmium.client.settings.UserSettingsH\x00R\bsettings\x88\x01\x01B\v\n" +
	"\t_settings\"\xef\x03\n" +
	"\fUserSettings\x12a\n" +
	"\x0fcommunity_order\x18\x01 \x01(\v23.osmium.client.settings.UserSettings.CommunityOrderH\x00R\x0ecommunityOrder\x88\x01\x01\x12g\n" +
	"\x11email_preferences\x18\x02 \x01(\v25.osmium.client.settings.UserSettings.EmailPreferencesH\x01R\x10emailPreferences\x88\x01\x01\x1a5\n" +
	"\x0eCommunityOrder\x12#\n" +
	"\rcommunity_ids\x18\x01 \x03(\x06R\fcommunityIds\x1a\xb1\x01\n" +
	"\x10EmailPreferences\x126\n" +
	"\x14communication_emails\x18\x01 \x01(\bH\x00R\x13communicationEmails\x88\x01\x01\x124\n" +
	"\x13announcement_emails\x18\x02 \x01(\bH\x01R\x12announcementEmails\x88\x01\x01B\x17\n" +
	"\x15_communication_emailsB\x16\n" +
	"\x14_announcement_emailsB\x12\n" +
	"\x10_community_orderB\x14\n" +
	"\x12_email_preferences\"\xc8\x02\n" +
	"\vEditProfile\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x01R\busername\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\x03 \x01(\tH\x02R\x03bio\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x04 \x01(\x06H\x03R\x04icon\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x05 \x01(\rH\x04R\x05color\x88\x01\x01\x12$\n" +
	"\vtheme_color\x18\x06 \x01(\x04H\x05R\n" +
	"themeColor\x88\x01\x01\x124\n" +
	"\x14show_banner_in_voice\x18\a \x01(\bH\x06R\x11showBannerInVoice\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_usernameB\x06\n" +
	"\x04_bioB\a\n" +
	"\x05_iconB\b\n" +
	"\x06_colorB\x0e\n" +
	"\f_theme_colorB\x17\n" +
	"\x15_show_banner_in_voice\"\f\n" +
	"\n" +
	"GetAccount\"\xb9\x01\n" +
	"\aAccount\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x1c\n" +
	"\tconfirmed\x18\x02 \x01(\bR\tconfirmed\x12!\n" +
	"\fhas_password\x18\x03 \x01(\bR\vhasPassword\x12!\n" +
	"\ftotp_enabled\x18\x04 \x01(\bR\vtotpEnabled\x12%\n" +
	"\x0epending_delete\x18\x05 \x01(\bR\rpendingDeleteB\b\n" +
	"\x06_email\"\x87\x01\n" +
	"\x0eChangePassword\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12'\n" +
	"\x0frevoke_sessions\x18\x03 \x01(\bR\x0erevokeSessions\"*\n" +
	"\vChangeEmail\x12\x1b\n" +
	"\tnew_email\x18\x01 \x01(\tR\bnewEmail\"\xce\x01\n" +
	"\fChangeStatus\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.osmium.client.types.UserStatus.StatusR\x06status\x12H\n" +
	"\n" +
	"activities\x18\x03 \x03(\v2(.osmium.client.types.UserStatus.ActivityR\n" +
	"activities\x12$\n" +
	"\vlast_active\x18\x04 \x01(\x06H\x00R\n" +
	"lastActive\x88\x01\x01B\x0e\n" +
	"\f_last_active\"\x82\x01\n" +
	"\tSetupTotp\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tH\x00R\x04code\x88\x01\x01\x12'\n" +
	"\rstep_up_token\x18\x03 \x01(\tH\x01R\vstepUpToken\x88\x01\x01B\a\n" +
	"\x05_codeB\x10\n" +
	"\x0e_step_up_token\"\x86\x01\n" +
	"\x04Totp\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x15\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03url\x88\x01\x01\x12E\n" +
	"\fbackup_codes\x18\x03 \x03(\v2\".osmium.client.settings.BackupCodeR\vbackupCodesB\x06\n" +
	"\x04_url\"4\n" +
	"\n" +
	"BackupCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04used\x18\x02 \x01(\bR\x04used\"\xd4\x02\n" +
	"\rSetupWebauthn\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12,\n" +
	"\x0fcredential_json\x18\x02 \x01(\tH\x00R\x0ecredentialJson\x88\x01\x01\x12(\n" +
	"\rcredential_id\x18\x03 \x01(\x06H\x01R\fcredentialId\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x04 \x01(\tH\x02R\vdisplayName\x88\x01\x01\x12'\n" +
	"\rstep_up_token\x18\x05 \x01(\tH\x03R\vstepUpToken\x88\x01\x01\x12&\n" +
	"\fchallenge_id\x18\x06 \x01(\tH\x04R\vchallengeId\x88\x01\x01B\x12\n" +
	"\x10_credential_jsonB\x10\n" +
	"\x0e_credential_idB\x0f\n" +
	"\r_display_nameB\x10\n" +
	"\x0e_step_up_tokenB\x0f\n" +
	"\r_challenge_id\"\xa7\x02\n" +
	"\bWebauthn\x12&\n" +
	"\foptions_json\x18\x01 \x01(\tH\x00R\voptionsJson\x88\x01\x01\x12O\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2*.osmium.client.settings.WebauthnCredentialH\x01R\n" +
	"credential\x88\x01\x01\x12I\n" +
	"\x0erecovery_codes\x18\x03 \x03(\v2\".osmium.client.settings.BackupCodeR\rrecoveryCodes\x12&\n" +
	"\fchallenge_id\x18\x04 \x01(\tH\x02R\vchallengeId\x88\x01\x01B\x0f\n" +
	"\r_options_jsonB\r\n" +
	"\v_credentialB\x0f\n" +
	"\r_challenge_id\"\xc3\x01\n" +
	"\x12WebauthnCredential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x06R\x02id\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\tR\fcredentialId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x06R\tcreatedAt\x12%\n" +
	"\flast_used_at\x18\x05 \x01(\x06H\x00R\n" +
	"lastUsedAt\x88\x01\x01B\x0f\n" +
	"\r_last_used_at\"\x0f\n" +
	"\rGetMfaMethods\"\xc8\x01\n" +
	"\n" +
	"MfaMethods\x12!\n" +
	"\ftotp_enabled\x18\x01 \x01(\bR\vtotpEnabled\x12]\n" +
	"\x14webauthn_credentials\x18\x02 \x03(\v2*.osmium.client.settings.WebauthnCredentialR\x13webauthnCredentials\x128\n" +
	"\x18recovery_codes_remaining\x18\x03 \x01(\rR\x16recoveryCodesRemaining\",\n" +
	"\x0eBeginMfaStepUp\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"\xc0\x02\n" +
	"\tMfaStepUp\x12'\n" +
	"\rstep_up_token\x18\x01 \x01(\tH\x00R\vstepUpToken\x88\x01\x01\x12&\n" +
	"\fchallenge_id\x18\x02 \x01(\tH\x01R\vchallengeId\x88\x01\x01\x12\"\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x06H\x02R\texpiresAt\x88\x01\x01\x12\x12\n" +
	"\x04totp\x18\x04 \x01(\bR\x04totp\x12%\n" +
	"\x0erecovery_codes\x18\x05 \x01(\bR\rrecoveryCodes\x127\n" +
	"\x15webauthn_options_json\x18\x06 \x01(\tH\x03R\x13webauthnOptionsJson\x88\x01\x01B\x10\n" +
	"\x0e_step_up_tokenB\x0f\n" +
	"\r_challenge_idB\r\n" +
	"\v_expires_atB\x18\n" +
	"\x16_webauthn_options_json\"\xb8\x01\n" +
	"\x11CompleteMfaStepUp\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x14\n" +
	"\x04totp\x18\x02 \x01(\tH\x00R\x04totp\x12%\n" +
	"\rrecovery_code\x18\x03 \x01(\tH\x00R\frecoveryCode\x12:\n" +
	"\x18webauthn_credential_json\x18\x04 \x01(\tH\x00R\x16webauthnCredentialJsonB\a\n" +
	"\x05proof\"=\n" +
	"\x17RegenerateRecoveryCodes\x12\"\n" +
	"\rstep_up_token\x18\x01 \x01(\tR\vstepUpToken\".\n" +
	"\x10GetRecoveryCodes\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"Z\n" +
	"\rRecoveryCodes\x12I\n" +
	"\x0erecovery_codes\x18\x01 \x03(\v2\".osmium.client.settings.BackupCodeR\rrecoveryCodes\"\x10\n" +
	"\x0eRequestTakeout\"7\n" +
	"\rDeleteAccount\x12\x1b\n" +
	"\x06cancel\x18\x01 \x01(\bH\x00R\x06cancel\x88\x01\x01B\t\n" +
	"\a_cancelb\x06proto3"

var (
	file_settings_proto_rawDescOnce sync.Once
	file_settings_proto_rawDescData []byte
)

func file_settings_proto_rawDescGZIP() []byte {
	file_settings_proto_rawDescOnce.Do(func() {
		file_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)))
	})
	return file_settings_proto_rawDescData
}

var file_settings_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_settings_proto_goTypes = []any{
	(RegisterPushSubscription_PushType)(0),             // 0: osmium.client.settings.RegisterPushSubscription.PushType
	(RegisterPushSubscription_PushEncryptionScheme)(0), // 1: osmium.client.settings.RegisterPushSubscription.PushEncryptionScheme
	(*EditProfilePhoto)(nil),                           // 2: osmium.client.settings.EditProfilePhoto
	(*EditProfileBanner)(nil),                          // 3: osmium.client.settings.EditProfileBanner
	(*RegisterPushSubscription)(nil),                   // 4: osmium.client.settings.RegisterPushSubscription
	(*UnregisterPushSubscription)(nil),                 // 5: osmium.client.settings.UnregisterPushSubscription
	(*ChangeNotificationPreferences)(nil),              // 6: osmium.client.settings.ChangeNotificationPreferences
	(*EditUserSettings)(nil),                           // 7: osmium.client.settings.EditUserSettings
	(*UserSettings)(nil),                               // 8: osmium.client.settings.UserSettings
	(*EditProfile)(nil),                                // 9: osmium.client.settings.EditProfile
	(*GetAccount)(nil),                                 // 10: osmium.client.settings.GetAccount
	(*Account)(nil),                                    // 11: osmium.client.settings.Account
	(*ChangePassword)(nil),                             // 12: osmium.client.settings.ChangePassword
	(*ChangeEmail)(nil),                                // 13: osmium.client.settings.ChangeEmail
	(*ChangeStatus)(nil),                               // 14: osmium.client.settings.ChangeStatus
	(*SetupTotp)(nil),                                  // 15: osmium.client.settings.SetupTotp
	(*Totp)(nil),                                       // 16: osmium.client.settings.Totp
	(*BackupCode)(nil),                                 // 17: osmium.client.settings.BackupCode
	(*SetupWebauthn)(nil),                              // 18: osmium.client.settings.SetupWebauthn
	(*Webauthn)(nil),                                   // 19: osmium.client.settings.Webauthn
	(*WebauthnCredential)(nil),                         // 20: osmium.client.settings.WebauthnCredential
	(*GetMfaMethods)(nil),                              // 21: osmium.client.settings.GetMfaMethods
	(*MfaMethods)(nil),                                 // 22: osmium.client.settings.MfaMethods
	(*BeginMfaStepUp)(nil),                             // 23: osmium.client.settings.BeginMfaStepUp
	(*MfaStepUp)(nil),                                  // 24: osmium.client.settings.MfaStepUp
	(*CompleteMfaStepUp)(nil),                          // 25: osmium.client.settings.CompleteMfaStepUp
	(*RegenerateRecoveryCodes)(nil),                    // 26: osmium.client.settings.RegenerateRecoveryCodes
	(*GetRecoveryCodes)(nil),                           // 27: osmium.client.settings.GetRecoveryCodes
	(*RecoveryCodes)(nil),                              // 28: osmium.client.settings.RecoveryCodes
	(*RequestTakeout)(nil),                             // 29: osmium.client.settings.RequestTakeout
	(*DeleteAccount)(nil),                              // 30: osmium.client.settings.DeleteAccount
	(*RegisterPushSubscription_WebPush)(nil),           // 31: osmium.client.settings.RegisterPushSubscription.WebPush
	(*RegisterPushSubscription_Push)(nil),              // 32: osmium.client.settings.RegisterPushSubscription.Push
	(*UserSettings_CommunityOrder)(nil),                // 33: osmium.client.settings.UserSettings.CommunityOrder
	(*UserSettings_EmailPreferences)(nil),              // 34: osmium.client.settings.UserSettings.EmailPreferences
	(*media.UploadedFileRef)(nil),                      // 35: osmium.client.media.UploadedFileRef
	(types.NotifPrefs)(0),                              // 36: osmium.client.types.NotifPrefs
	(*refs.ChatRef)(nil),                               // 37: osmium.client.refs.ChatRef
	(types.UserStatus_Status)(0),                       // 38: osmium.client.types.UserStatus.Status
	(*types.UserStatus_Activity)(nil),                  // 39: osmium.client.types.UserStatus.Activity
}
var file_settings_proto_depIdxs = []int32{
	35, // 0: osmium.client.settings.EditProfilePhoto.file:type_name -> osmium.client.media.UploadedFileRef
	35, // 1: osmium.client.settings.EditProfileBanner.file:type_name -> osmium.client.media.UploadedFileRef
	31, // 2: osmium.client.settings.RegisterPushSubscription.web:type_name -> osmium.client.settings.RegisterPushSubscription.WebPush
	32, // 3: osmium.client.settings.RegisterPushSubscription.push:type_name -> osmium.client.settings.RegisterPushSubscription.Push
	36, // 4: osmium.client.settings.ChangeNotificationPreferences.prefs:type_name -> osmium.client.types.NotifPrefs
	37, // 5: osmium.client.settings.ChangeNotificationPreferences.chat_ref:type_name -> osmium.client.refs.ChatRef
	8,  // 6: osmium.client.settings.EditUserSettings.settings:type_name -> osmium.client.settings.UserSettings
	33, // 7: osmium.client.settings.UserSettings.community_order:type_name -> osmium.client.settings.UserSettings.CommunityOrder
	34, // 8: osmium.client.settings.UserSettings.email_preferences:type_name -> osmium.client.settings.UserSettings.EmailPreferences
	38, // 9: osmium.client.settings.ChangeStatus.status:type_name -> osmium.client.types.UserStatus.Status
	39, // 10: osmium.client.settings.ChangeStatus.activities:type_name -> osmium.client.types.UserStatus.Activity
	17, // 11: osmium.client.settings.Totp.backup_codes:type_name -> osmium.client.settings.BackupCode
	20, // 12: osmium.client.settings.Webauthn.credential:type_name -> osmium.client.settings.WebauthnCredential
	17, // 13: osmium.client.settings.Webauthn.recovery_codes:type_name -> osmium.client.settings.BackupCode
	20, // 14: osmium.client.settings.MfaMethods.webauthn_credentials:type_name -> osmium.client.settings.WebauthnCredential
	17, // 15: osmium.client.settings.RecoveryCodes.recovery_codes:type_name -> osmium.client.settings.BackupCode
	0,  // 16: osmium.client.settings.RegisterPushSubscription.Push.type:type_name -> osmium.client.settings.RegisterPushSubscription.PushType
	1,  // 17: osmium.client.settings.RegisterPushSubscription.Push.encryption_scheme:type_name -> osmium.client.settings.RegisterPushSubscription.PushEncryptionScheme
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_settings_proto_init() }
func file_settings_proto_init() {
	if File_settings_proto != nil {
		return
	}
	file_settings_proto_msgTypes[0].OneofWrappers = []any{}
	file_settings_proto_msgTypes[1].OneofWrappers = []any{}
	file_settings_proto_msgTypes[2].OneofWrappers = []any{
		(*RegisterPushSubscription_Web)(nil),
		(*RegisterPushSubscription_Push_)(nil),
	}
	file_settings_proto_msgTypes[4].OneofWrappers = []any{
		(*ChangeNotificationPreferences_ChatRef)(nil),
		(*ChangeNotificationPreferences_CommunityId)(nil),
	}
	file_settings_proto_msgTypes[5].OneofWrappers = []any{}
	file_settings_proto_msgTypes[6].OneofWrappers = []any{}
	file_settings_proto_msgTypes[7].OneofWrappers = []any{}
	file_settings_proto_msgTypes[9].OneofWrappers = []any{}
	file_settings_proto_msgTypes[12].OneofWrappers = []any{}
	file_settings_proto_msgTypes[13].OneofWrappers = []any{}
	file_settings_proto_msgTypes[14].OneofWrappers = []any{}
	file_settings_proto_msgTypes[16].OneofWrappers = []any{}
	file_settings_proto_msgTypes[17].OneofWrappers = []any{}
	file_settings_proto_msgTypes[18].OneofWrappers = []any{}
	file_settings_proto_msgTypes[22].OneofWrappers = []any{}
	file_settings_proto_msgTypes[23].OneofWrappers = []any{
		(*CompleteMfaStepUp_Totp)(nil),
		(*CompleteMfaStepUp_RecoveryCode)(nil),
		(*CompleteMfaStepUp_WebauthnCredentialJson)(nil),
	}
	file_settings_proto_msgTypes[28].OneofWrappers = []any{}
	file_settings_proto_msgTypes[30].OneofWrappers = []any{}
	file_settings_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settings_proto_goTypes,
		DependencyIndexes: file_settings_proto_depIdxs,
		EnumInfos:         file_settings_proto_enumTypes,
		MessageInfos:      file_settings_proto_msgTypes,
	}.Build()
	File_settings_proto = out.File
	file_settings_proto_goTypes = nil
	file_settings_proto_depIdxs = nil
}
